<template>
  <view class="leave-detail-page">
    <view class="leave-detail-nav"><button class="leave-back" @click="$emit('close')">返回列表</button><text>请假详情</text><button class="leave-back" :disabled="loading" @click="$emit('retry')">刷新</button></view>
    <scroll-view scroll-y class="leave-detail-scroll">
      <view class="leave-detail-content">
        <MobileGlobalState v-if="loading || error" :state="loading ? 'loading' : 'error'" :description="error" @retry="$emit('retry')" />
        <template v-else-if="detail">
          <view class="card leave-overview"><view class="row-between"><text class="leave-eyebrow">{{ teacher ? detail.studentName : '我的申请' }}</text><MobileStatusTag :label="detail.statusLabel" :type="detail.tone" /></view><text class="leave-title">{{ detail.leaveTypeLabel }} <text class="leave-duration">{{ detail.days }} 天</text></text><text v-if="teacher" class="leave-muted">{{ detail.className }} · {{ detail.studentNo }}</text><text v-else class="leave-muted">{{ detail.nextHint }}</text><view v-if="detail.handler" class="leave-handler"><text>当前处理人</text><text>{{ detail.handler }}</text></view></view>
          <view class="card leave-section"><text class="leave-section-title">申请信息</text><view class="leave-fact"><text>开始时间</text><text>{{ date(detail.startTime, true) }}</text></view><view class="leave-fact"><text>结束时间</text><text>{{ date(detail.endTime, true) }}</text></view><view class="leave-reason"><text class="leave-muted">请假事由</text><text>{{ detail.reason || '未填写' }}</text></view><view v-if="detail.returnReason" class="leave-opinion"><text>处理意见</text><text>{{ detail.returnReason }}</text></view></view>
          <view v-if="detail.extensions.length" class="card leave-section"><text class="leave-section-title">续假记录</text><view v-for="item in detail.extensions" :key="item.id" class="leave-history"><view class="row-between"><text>{{ date(item.oldEndTime) }} → {{ date(item.newEndTime) }}</text><text>{{ item.statusLabel }}</text></view><text class="leave-muted">{{ item.reason }}</text></view></view>
          <view v-if="detail.cancelRecords.length" class="card leave-section"><text class="leave-section-title">返校核实</text><view v-for="item in detail.cancelRecords" :key="item.id" class="leave-history"><text>{{ item.statusLabel }}<text v-if="item.actualReturnAt"> · {{ date(item.actualReturnAt, true) }}</text></text><text class="leave-muted">{{ item.proofNote || '已提交返校申请' }}</text><text v-if="item.confirmNote" class="leave-muted">{{ item.confirmNote }}</text></view></view>
          <slot name="materials" />
          <view class="card leave-section"><text class="leave-section-title">办理记录</text><text v-if="!detail.timeline.length" class="leave-muted">暂无办理记录</text><view v-for="event in detail.timeline" :key="event.eventId" class="leave-event"><view><text>{{ event.actionLabel }}</text><text class="leave-muted">{{ event.operator || '系统' }}</text></view><text class="leave-time">{{ date(event.occurredAt, true) }}</text></view></view>
        </template>
      </view>
    </scroll-view>
    <view v-if="detail && !loading && !error" class="leave-action-footer"><slot :item="detail" /></view>
  </view>
</template>
<script>
import { leaveDate } from '@/services/leavePresentation'
export default { props: { detail: { type: Object, default: null }, loading: Boolean, error: { type: String, default: '' }, teacher: Boolean }, emits: ['close', 'retry'], methods: { date: leaveDate } }
</script>
<style scoped>
.leave-detail-page{position:fixed;inset:0;z-index:80;display:flex;flex-direction:column;background:var(--bg-page,#f5f7f8);color:var(--text-primary,#18232f)}.leave-detail-nav{display:flex;align-items:center;justify-content:space-between;min-height:52px;padding:env(safe-area-inset-top) 12px 0;background:var(--bg-card,#fff);border-bottom:1px solid var(--border-color,#e5e9ed);font-size:15px;font-weight:600}.leave-back{padding:0 8px;min-height:44px;margin:0;border:0;background:transparent;color:var(--teacher-600,var(--brand-primary,#337e75));font-size:13px;line-height:44px}.leave-back::after{border:0}.leave-detail-scroll{flex:1;min-height:0;height:0}.leave-detail-content{padding:16px 16px 28px}.leave-overview{padding:20px}.leave-eyebrow{font-size:13px;color:var(--text-secondary)}.leave-title{display:block;font-size:27px;font-weight:600;margin:18px 0 8px}.leave-duration{font-size:17px;font-weight:400;margin-left:8px;color:var(--text-secondary)}.leave-muted{display:block;font-size:12px;color:var(--text-secondary,#667581);line-height:1.8;overflow-wrap:anywhere}.leave-handler{display:flex;justify-content:space-between;margin-top:16px;padding-top:14px;border-top:1px solid var(--border-color,#e5e9ed);font-size:12px}.leave-section{margin-top:12px;padding:18px}.leave-section-title{display:block;font-size:15px;font-weight:600;margin-bottom:14px}.leave-fact{display:flex;justify-content:space-between;gap:12px;font-size:13px;padding:10px 0}.leave-fact>text:first-child{color:var(--text-secondary)}.leave-reason{display:flex;flex-direction:column;gap:6px;font-size:14px;line-height:1.8;margin-top:12px}.leave-opinion{display:flex;flex-direction:column;gap:8px;padding:12px;margin-top:14px;border-left:3px solid var(--teacher-600,#328175);background:var(--bg-page,#f4f7f7);font-size:13px;line-height:1.8}.leave-history{padding:10px 0;font-size:12px}.leave-event{display:flex;align-items:start;justify-content:space-between;gap:12px;font-size:13px;padding:13px 0;border-top:1px solid var(--border-color,#e5e9ed)}.leave-time{color:var(--text-tertiary);font-size:11px;white-space:nowrap}.leave-action-footer{padding:12px 16px calc(12px + env(safe-area-inset-bottom));background:var(--bg-card,#fff);border-top:1px solid var(--border-color,#e5e9ed)}
</style>
