"""教务中心服务包。

本包集中声明各业务域的正式公开入口。兼容模块只保留历史导入路径，Router 不得自行选择
旧实现或依赖导入顺序抢占函数。
"""

# 各域最终公开入口。
from . import academic_affairs_dashboard_scope_facade as academic_affairs_service
from . import academic_affairs_archive_textbook_facade as academic_affairs_archive_service
from . import academic_affairs_attendance_public_service as academic_affairs_attendance_service
from . import academic_affairs_stats_public_service as academic_affairs_stats_service
from . import academic_affairs_evaluation_term_facade as academic_affairs_evaluation_service
from . import academic_affairs_selection_final_service as academic_affairs_selection_service
from . import academic_affairs_scheduling_public_service as academic_affairs_scheduling_service
from . import academic_affairs_autoschedule_final_service as academic_affairs_autoschedule_service
from . import academic_affairs_schedule_final_service as academic_affairs_schedule_service
from . import academic_affairs_exam_facade as academic_affairs_exam_service
from . import academic_affairs_textbook_final_facade as academic_affairs_textbook_service
from . import academic_affairs_recognition_public_service as academic_affairs_recognition_service
from . import academic_affairs_major_split_public_service as academic_affairs_major_split_service
from . import mobile_academic_affairs_facade as mobile_academic_affairs_service
