import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('../', import.meta.url))
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8')

const sdk = read('src/services/fileSdk.js')
const request = read('src/services/request.js')
const compatibility = read('src/components/file/FilePreviewer.vue')
const viewer = read('src/components/file/viewer/StudentDocumentViewer.vue')
const versionBar = read('src/components/file/viewer/StudentDocumentVersionBar.vue')
const session = read('src/components/file/viewer/useStudentPreviewSession.js')
const materials = read('src/views/graduation/GraduationMaterialsView.vue')
const workbench = read('src/views/graduation/GraduationWorkbenchView.vue')
const docxRenderer = read('src/components/file/viewer/adapters/docx-preview-renderer.js')
const docxViewer = read('src/components/file/viewer/adapters/StudentDocxViewer.vue')

test('W3 student File SDK separates preview bytes from download side effects', () => {
  assert.match(request, /export async function fetchFileBlob\(/)
  assert.match(request, /credentials: 'include', signal/)
  assert.match(request, /if \(error\?\.name === 'AbortError'\) throw error/)
  assert.match(request, /await refreshOnce\(\)/)
  assert.match(sdk, /async fetchPreviewBlob\(/)
  assert.match(sdk, /async fetchPreviewBlobFrom\(/)
  assert.match(sdk, /async fetchPeerPreviewBlob\(peerId, fileId, options = \{\}\)/)
  assert.match(sdk, /\/mobile\/graduation\/peer\/\$\{enc\(peerId\)\}\/files\/\$\{enc\(fileId\)\}\/preview/)
  assert.match(sdk, /async preview\([^)]*\)[\s\S]*?return this\.fetchPreviewBlob\(/)
  assert.match(sdk, /async previewFrom\([^)]*\)[\s\S]*?return this\.fetchPreviewBlobFrom\(/)
  assert.doesNotMatch(sdk, /async preview\([^)]*\)[\s\S]{0,180}?this\.download\(/)
  assert.doesNotMatch(sdk, /async previewFrom\([^)]*\)[\s\S]{0,180}?this\.downloadFrom\(/)
})

test('W3 compatibility FilePreviewer routes into the in-site reader without owning transport primitives', () => {
  assert.match(compatibility, /StudentDocumentViewer/)
  assert.match(compatibility, />站内查看</)
  assert.match(compatibility, /props\.file\?\.canPreview !== true/)
  assert.match(compatibility, /file\?\.canPreview !== true/)
  assert.match(compatibility, /file\?\.canDownload !== true/)
  for (const forbidden of ['window.open(', 'URL.createObjectURL(', "request('/files", 'document.createElement']) assert.equal(compatibility.includes(forbidden), false, `FilePreviewer must not own ${forbidden}`)
})

test('W3 StudentDocumentViewer stays presentation-only and fences Blob lifecycle by canonical file identity', () => {
  assert.match(viewer, /useStudentPreviewSession/)
  assert.match(versionBar, /item\.fileVersionId \|\| item\.versionId \|\| item\.fileId/)
  assert.match(viewer, /selectedFile\.value\?\.isCurrent === false/)
  assert.match(viewer, /selectedFile\.value\?\.canDownload === true/)
  assert.match(viewer, /只读冻结版本/)
  for (const forbidden of ['portalApi', 'issueGraduationMaterialTicket', '/material-center/', 'downloadGraduationMaterial', 'window.open(']) assert.equal(viewer.includes(forbidden), false, `Viewer must not own business transport: ${forbidden}`)
  assert.match(session, /file\.fileId/)
  assert.match(session, /file\.fileVersionId \|\| file\.versionId/)
  assert.match(session, /file\.sourceSha256 \|\| file\.sha256/)
  assert.match(session, /if \(file\?\.canPreview !== true\)/)
  assert.match(session, /当前文件未授予站内预览权限/)
  assert.match(session, /new AbortController\(\)/)
  assert.match(session, /URL\.revokeObjectURL\(objectUrl\.value\)/)
  assert.match(session, /currentGeneration !== generation/)
})

test('W3 graduation materials use audited business preview tickets for bound current and immutable history versions', () => {
  assert.match(materials, /查看当前版/)
  assert.match(materials, /查看历史版/)
  assert.match(materials, /历史版本 · 只读|历史只读/)
  assert.match(materials, /预览我将提交的文件/)
  assert.match(materials, /issueGraduationMaterialTicket\(file\.fileId, 'preview'\)/)
  assert.match(materials, /fileSdk\.fetchPreviewBlobFrom\(ticket, options\)/)
  assert.match(materials, /fileVersionId: material\.currentVersion\.fileVersionId \|\| material\.currentVersionId/)
  assert.match(materials, /temporaryPreview: true/)
})

test('W3 graduation workbench separates current-version viewing/download and requires safe pending bytes before submit', () => {
  assert.match(workbench, />查看当前版</)
  assert.match(workbench, /@click="downloadMaterial\(file\)"/)
  assert.match(workbench, /预览我将提交的文件/)
  assert.match(workbench, /canPreviewPending\(attachments\.proposal\[0\]\)/)
  assert.match(workbench, /!attachments\.final\[0\]\.readyForBusiness/)
  assert.match(workbench, /issueGraduationMaterialTicket\(file\.fileId, 'preview'\)/)
  assert.match(workbench, /fileSdk\.fetchPreviewBlobFrom\(ticket, options\)/)
  assert.match(workbench, /peerId \+ 冻结定稿 \+ 附件 fileId/)
  assert.match(workbench, /仅支持站内查看，不提供跨学生下载/)
  assert.match(workbench, /openPeerReader\(p, file\)/)
  assert.match(workbench, /peerId: String\(task\.id\)/)
  assert.match(workbench, /canDownload: false/)
  assert.match(workbench, /if \(file\?\.peerId\)[\s\S]{0,160}?return/)
  assert.match(workbench, /fileSdk\.fetchPeerPreviewBlob\(file\.peerId, file\.fileId, options\)/)
  assert.match(workbench, /:read-only="Boolean\(readerFile\?\.peerId\)"/)
  const peerSection = workbench.slice(workbench.indexOf('<section v-if="hasPeerWork"'), workbench.indexOf('</section>', workbench.indexOf('<section v-if="hasPeerWork"')) + 10)
  assert.doesNotMatch(peerSection, /@click="downloadMaterial\(file\)"/)
})

test('W6 student PC renders DOCX locally from authorized bytes without widening XLSX/PPTX', () => {
  assert.match(viewer, /StudentDocxViewer/)
  assert.match(viewer, /kind === 'docx'/)
  assert.match(viewer, /wordprocessingml\.document/)
  assert.match(session, /const blob = shallowRef\(null\)/)
  assert.match(session, /25 \* 1024 \* 1024/)
  assert.match(docxRenderer, /DecompressionStream\('deflate-raw'\)/)
  assert.match(docxRenderer, /const reader = stream\.getReader\(\)/)
  assert.match(docxRenderer, /reader\.cancel\(/)
  assert.match(docxRenderer, /MAX_TOTAL_UNCOMPRESSED = 80 \* 1024 \* 1024/)
  assert.match(docxRenderer, /MAX_RENDER_NODES = 50000/)
  assert.match(docxRenderer, /actualDecodedTotal/)
  assert.match(docxRenderer, /this\.cache = new Map\(\)/)
  assert.match(docxRenderer, /TargetMode/)
  assert.match(docxRenderer, /if \(!mime\) continue/)
  assert.doesNotMatch(docxRenderer, /image\/svg\+xml/)
  assert.doesNotMatch(docxRenderer, /window\.open|officeapps\.live|docs\.google|fetch\(/i)
  assert.doesNotMatch(docxViewer, /portalApi|issueGraduationMaterialTicket|annotation|批注/i)
})
