<template>
  <view class="page-wrap">
    <MobileNavBar variant="brand" title="勤工助学" subtitle="审核、上岗与月度考核" show-back />
    <MobileGlobalState :state="state" @retry="load">
      <view v-if="state === 'ready'" class="page-pad stack">
        <view class="card wt__summary">
          <view><text class="wt__eyebrow">今日先处理</text><text class="wt__headline">{{ count('APPLIED') }} 笔待审核 · {{ count('ONBOARD') }} 人在岗</text></view>
          <text class="hint">手机端用于随时处理申请和登记月度结果；岗位发布与大批量核对建议在教师 PC 完成。</text>
        </view>
        <view class="wt__search"><input v-model.trim="keyword" class="input" maxlength="100" placeholder="搜索学生、学号或岗位" confirm-type="search" @confirm="search" /><button class="btn btn-secondary" :disabled="refreshing" @click="search">查询</button></view>
        <scroll-view class="wt__filters" scroll-x><button v-for="item in statuses" :key="item.value" class="wt__filter" :class="{ on: status === item.value }" @click="changeStatus(item.value)">{{ item.label }}{{ item.value ? ` ${count(item.value)}` : '' }}</button></scroll-view>
        <view v-if="records.length" class="stack">
          <view v-for="record in records" :key="record.recordId" class="card wt__record">
            <view class="row-between"><view class="flex-1"><text class="wt__student">{{ record.studentName }} · {{ record.studentNo }}</text><text class="card-title">{{ record.post?.postName || `岗位 ${record.postId}` }}</text><text class="hint">{{ record.post?.deptName }} · {{ record.post?.workLocation || '地点待通知' }}</text></view><MobileStatusTag :status="record.status" :label="statusLabel(record.status)" /></view>
            <view class="wt__detail"><text>申请说明：{{ record.applyStatement || '未填写' }}</text><text>可工作时段：{{ record.availability || '未填写' }}</text><text>累计补贴：{{ money(record.subsidyTotal) }}</text></view>
            <view class="wt__actions"><button v-if="allows(record, 'APPROVE')" class="btn btn-primary" :disabled="!!busy" @click="confirmSimple(record)">录用</button><button v-if="allows(record, 'REJECT')" class="btn btn-danger" :disabled="!!busy" @click="openAction(record, 'REJECT')">拒绝</button><button v-if="allows(record, 'ONBOARD')" class="btn btn-primary" :disabled="!!busy" @click="openAction(record, 'ONBOARD')">核验协议并上岗</button><button v-if="allows(record, 'MONTHLY')" class="btn btn-primary" :disabled="!!busy" @click="openMonthly(record)">登记月度考核</button><button v-if="allows(record, 'TERMINATE')" class="btn btn-secondary" :disabled="!!busy" @click="openAction(record, 'TERMINATE')">结束岗位</button></view>
          </view>
          <button v-if="records.length < total" class="btn btn-secondary" :disabled="refreshing" @click="loadRecords(true)">加载更多</button>
        </view>
        <MobileGlobalState v-else state="empty" title="当前没有匹配记录" description="可以切换状态或修改搜索条件。" />
      </view>
    </MobileGlobalState>
    <view v-if="actionTarget" class="wt__mask" @click.self="closeAction"><view class="card wt__sheet"><text class="card-title">{{ actionTitle }}</text><text class="hint">{{ actionTarget.studentName }} · {{ actionTarget.post?.postName }}</text><label v-if="actionType === 'ONBOARD'" class="wt__check" @click="agreementConfirmed = !agreementConfirmed"><text class="wt__box">{{ agreementConfirmed ? '✓' : '' }}</text><text>已核对学生与用人部门签署的勤工助学协议</text></label><view v-else class="fld"><text class="lbl">处理原因（5–500字）</text><textarea v-model.trim="reason" class="ta" maxlength="500" :placeholder="actionType === 'REJECT' ? '说明未录用原因' : '说明岗位结束原因'" /></view><text v-if="actionError" class="wt__error">{{ actionError }}</text><view class="wt__sheet-actions"><button class="btn btn-secondary flex-1" :disabled="!!busy" @click="closeAction">取消</button><button class="btn flex-1" :disabled="!!busy || !actionValid" @click="submitAction">确认{{ actionType === 'ONBOARD' ? '上岗' : actionType === 'REJECT' ? '拒绝' : '结束' }}</button></view></view></view>
    <view v-if="monthlyTarget" class="wt__mask" @click.self="closeMonthly"><view class="card wt__sheet"><text class="card-title">登记月度考核</text><text class="hint">{{ monthlyTarget.studentName }} · {{ monthlyTarget.post?.postName }}</text><view class="wt__form"><view class="fld"><text class="lbl">考核月（YYYY-MM）</text><input v-model.trim="monthly.monthCode" class="input" maxlength="7" /></view><view class="fld"><text class="lbl">实际工时（0–40）</text><input v-model="monthly.workHours" class="input" type="digit" /></view><view class="fld"><text class="lbl">考核结果</text><picker mode="selector" :range="ratingOptions" range-key="label" :value="ratingIndex" @change="monthly.rating = ratingOptions[$event.detail.value].value"><view class="input wt__picker">{{ ratingLabel(monthly.rating) }}</view></picker></view><view class="fld"><text class="lbl">补贴金额（元）</text><input v-model="monthly.subsidyAmount" class="input" type="digit" /></view><view class="fld"><text class="lbl">备注（选填）</text><textarea v-model.trim="monthly.remark" class="ta" maxlength="500" /></view></view><text v-if="monthlyError" class="wt__error">{{ monthlyError }}</text><view class="wt__sheet-actions"><button class="btn btn-secondary flex-1" :disabled="!!busy" @click="closeMonthly">取消</button><button class="btn flex-1" :disabled="!!busy || !monthlyValid" @click="submitMonthly">保存考核</button></view></view></view>
  </view>
</template>

<script>
import { teacherApi } from '@/services/teacherApi'
import { normalizeError } from '@/services/request'
import { toast } from '@/utils/nav'
export default {
  data() { return { state: 'loading', records: [], total: 0, statusCounts: {}, page: 1, keyword: '', appliedKeyword: '', status: 'APPLIED', refreshing: false, busy: '', actionTarget: null, actionType: '', reason: '', agreementConfirmed: false, actionError: '', monthlyTarget: null, monthlyError: '', monthly: { monthCode: '', workHours: '', rating: 'PASS', subsidyAmount: '', remark: '' }, statuses: [{ value: '', label: '全部' }, { value: 'APPLIED', label: '待审核' }, { value: 'APPROVED', label: '已录用' }, { value: 'ONBOARD', label: '在岗' }, { value: 'TERMINATED', label: '已结束' }], ratingOptions: [{ value: 'GOOD', label: '优秀' }, { value: 'PASS', label: '合格' }, { value: 'FAIL', label: '不合格' }] } },
  computed: { actionTitle() { return this.actionType === 'ONBOARD' ? '核验协议并确认上岗' : this.actionType === 'REJECT' ? '拒绝勤工申请' : '结束勤工岗位' }, actionValid() { return this.actionType === 'ONBOARD' ? this.agreementConfirmed : this.reason.length >= 5 && this.reason.length <= 500 }, ratingIndex() { return Math.max(0, this.ratingOptions.findIndex(x => x.value === this.monthly.rating)) }, monthlyValid() { const subsidyValid = this.monthly.rating === 'FAIL' || (Number.isFinite(Number(this.monthly.subsidyAmount)) && Number(this.monthly.subsidyAmount) >= 0); return /^\d{4}-(0[1-9]|1[0-2])$/.test(this.monthly.monthCode) && Number.isFinite(Number(this.monthly.workHours)) && Number(this.monthly.workHours) >= 0 && Number(this.monthly.workHours) <= 40 && subsidyValid } },
  onLoad() { this.load() }, onPullDownRefresh() { this.load().finally(() => uni.stopPullDownRefresh()) }, onBackPress() { if (this.actionTarget) { this.closeAction(); return true } if (this.monthlyTarget) { this.closeMonthly(); return true } return false },
  methods: {
    allows(row, action) { return Array.isArray(row.allowedActions) && row.allowedActions.includes(action) }, count(status) { return Number(this.statusCounts[status] || 0) }, statusLabel(s) { return ({ APPLIED: '待审核', APPROVED: '已录用', ONBOARD: '在岗', REJECTED: '未录用', WITHDRAWN: '已撤回', TERMINATED: '已结束' })[s] || '状态待确认' }, ratingLabel(s) { return ({ GOOD: '优秀', PASS: '合格', FAIL: '不合格' })[s] || '合格' }, money(v) { return v === null || v === undefined || v === '' || !Number.isFinite(Number(v)) ? '¥0.00' : `¥${Number(v).toFixed(2)}` }, currentMonth() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}` },
    async load() { this.state = 'loading'; try { await this.loadRecords(); this.state = 'ready' } catch (e) { this.state = 'error'; toast(normalizeError(e).text || '勤工记录加载失败') } }, async loadRecords(more = false) { this.refreshing = true; try { const next = more ? this.page + 1 : 1; const d = await teacherApi.getWorkStudyRecords({ page: next, pageSize: 20, status: this.status, keyword: this.appliedKeyword }); this.records = more ? [...this.records, ...(d.items || [])] : (d.items || []); this.total = Number(d.total || 0); this.statusCounts = d.statusCounts || {}; this.page = next } finally { this.refreshing = false } }, search() { this.appliedKeyword = this.keyword.trim(); return this.loadRecords() }, changeStatus(value) { if (this.status === value) return; this.status = value; this.loadRecords() },
    confirmSimple(record) { uni.showModal({ title: '确认录用？', content: `录用 ${record.studentName} 到“${record.post?.postName || '勤工岗位'}”？系统会校验剩余名额。`, success: (res) => { if (res.confirm) this.runAction(record, 'APPROVE', '', false) } }) }, openAction(record, action) { this.actionTarget = record; this.actionType = action; this.reason = ''; this.agreementConfirmed = false; this.actionError = '' }, closeAction() { if (!this.busy) this.actionTarget = null }, async runAction(record, action, reason, agreementConfirmed) { this.busy = `${action}-${record.recordId}`; try { await teacherApi.actWorkStudy(record.recordId, { action, reason, version: record.version, agreementConfirmed }); toast('状态已更新'); this.actionTarget = null; await this.loadRecords() } catch (e) { const text = normalizeError(e).text || '处理失败，请刷新后重试'; this.actionError = text; toast(text) } finally { this.busy = '' } }, submitAction() { if (!this.actionTarget || !this.actionValid) return; return this.runAction(this.actionTarget, this.actionType, this.reason, this.agreementConfirmed) },
    openMonthly(record) { this.monthlyTarget = record; this.monthly = { monthCode: this.currentMonth(), workHours: '', rating: 'PASS', subsidyAmount: '', remark: '' }; this.monthlyError = '' }, closeMonthly() { if (!this.busy) this.monthlyTarget = null }, async submitMonthly() { if (!this.monthlyTarget || !this.monthlyValid) { this.monthlyError = '请填写有效月份、0–40小时工时和非负补贴金额'; return } this.busy = `monthly-${this.monthlyTarget.recordId}`; try { await teacherApi.addWorkStudyMonthly(this.monthlyTarget.recordId, { ...this.monthly, workHours: String(this.monthly.workHours), subsidyAmount: this.monthly.rating === 'FAIL' ? '0' : String(this.monthly.subsidyAmount) }); toast('月度考核已登记'); this.monthlyTarget = null; await this.loadRecords() } catch (e) { this.monthlyError = normalizeError(e).text || '登记失败，请重试' } finally { this.busy = '' } }
  }
}
</script>

<style scoped>
.wt__summary { display:flex; flex-direction:column; gap:6px; }.wt__eyebrow { display:block; color:var(--brand-primary); font-size:11px; font-weight:700; letter-spacing:1px; }.wt__headline { display:block; margin-top:4px; color:var(--text-primary); font-size:19px; font-weight:700; }.wt__search { display:flex; gap:8px; }.wt__search .input { flex:1; }.wt__filters { white-space:nowrap; }.wt__filter { display:inline-flex; margin-right:8px; padding:8px 12px; border:1px solid var(--border-light); border-radius:18px; color:var(--text-secondary); background:var(--bg-card); font-size:12px; }.wt__filter.on { border-color:var(--brand-primary); color:#fff; background:var(--brand-primary); }.wt__record { display:flex; flex-direction:column; gap:10px; }.wt__student { display:block; color:var(--text-secondary); font-size:12px; }.wt__detail { display:flex; flex-direction:column; gap:5px; padding:10px; border-radius:9px; color:var(--text-secondary); background:var(--bg-page); font-size:12px; line-height:1.5; }.wt__actions { display:flex; flex-wrap:wrap; gap:8px; }.wt__actions .btn { margin:0; font-size:12px; }.wt__mask { position:fixed; z-index:1000; inset:0; display:flex; align-items:flex-end; background:rgba(15,23,42,.52); }.wt__sheet { width:100%; padding:18px; border-radius:18px 18px 0 0; }.wt__check { display:flex; gap:8px; align-items:flex-start; margin-top:14px; color:var(--text-secondary); font-size:13px; line-height:1.5; }.wt__box { width:18px; height:18px; border:1px solid var(--border-default); border-radius:4px; color:var(--brand-primary); text-align:center; line-height:18px; flex-shrink:0; }.wt__form { display:grid; grid-template-columns:1fr 1fr; gap:0 10px; }.wt__form .fld:last-child { grid-column:1 / -1; }.wt__picker { display:flex; align-items:center; }.wt__error { display:block; margin-top:8px; color:var(--danger-600); font-size:12px; }.wt__sheet-actions { display:flex; gap:10px; margin-top:14px; }
</style>
