"""/api/v1 路由聚合。注册逻辑拆至 route_registration，路径与依赖保持兼容。"""
from __future__ import annotations

from fastapi import APIRouter

from app.api.v1.route_registration import register_all_routes

api_router = APIRouter()
register_all_routes(api_router)

# 学工四端补充路由必须在既有路由完成注册后挂载；契约安装器随后修补已加载服务的
# version/permission/scope 绑定，不改任何其他业务域状态机。
from app.api.v1.affairs_activity_mobile import router as affairs_activity_mobile_router
from app.api.v1.affairs_appeal_mobile import router as affairs_appeal_mobile_router
from app.api.v1.affairs_appeal_repair_api import router as affairs_appeal_repair_router
from app.api.v1.affairs_four_end import router as affairs_four_end_router
from app.api.v1.affairs_student_dorm import router as affairs_student_dorm_router
from app.api.v1.affairs_student_returned import router as affairs_student_returned_router
from app.services.affairs_activity_accounting_guard import install as install_activity_accounting_guard
from app.services.affairs_activity_authority_guard import install as install_activity_authority_guard
from app.services.affairs_activity_code_service import install as install_activity_checkin_code
from app.services.affairs_activity_reliability_service import install as install_activity_reliability
from app.services.affairs_appeal_repair_scheduler import install as install_appeal_repair_scheduler
from app.services.affairs_appeal_repair_service import install as install_appeal_repair
from app.services.affairs_appeal_todo_service import install as install_appeal_todo_reconciliation
from app.services.affairs_archive_file_guard import install as install_archive_file_guard
from app.services.affairs_archive_guard import install as install_archive_guard
from app.services.affairs_counselor_eval_guard import install as install_counselor_eval_guard
from app.services.affairs_counselor_handover_guard import install as install_counselor_handover_guard
from app.services.affairs_credit_appeal_reliability import install as install_credit_appeal_reliability
from app.services.affairs_data_integrity_guard import install as install_data_integrity_guard
from app.services.affairs_dorm_projection_service import install as install_dorm_projection
from app.services.affairs_dorm_reliability_service import install as install_dorm_reliability
from app.services.affairs_four_end_contract import install as install_affairs_four_end_contract
from app.services.affairs_four_end_review_guard import install as install_affairs_four_end_review_guard
from app.services.affairs_four_end_terminal_guard import install as install_affairs_four_end_terminal_guard
from app.services.affairs_funding_ext_guard import install as install_funding_ext_guard
from app.services.affairs_returned_view_service import install as install_returned_view_projection
from app.services.affairs_risk_evidence_guard import install as install_risk_evidence_guard
from app.services.affairs_self_scope_guard import install as install_self_scope_guard
from app.services.affairs_sensitive_audit_guard import install as install_sensitive_audit_guard
from app.services.affairs_stats_integrity_guard import install as install_stats_integrity_guard
from app.services.affairs_student_application_lock import install as install_student_application_lock
from app.services.affairs_student_atomic_service import install as install_atomic_student_applications
from app.services.affairs_talk_guard import install as install_talk_guard

api_router.include_router(affairs_four_end_router)
api_router.include_router(affairs_student_dorm_router)
api_router.include_router(affairs_activity_mobile_router)
api_router.include_router(affairs_appeal_mobile_router)
api_router.include_router(affairs_appeal_repair_router)
api_router.include_router(affairs_student_returned_router)
install_affairs_four_end_contract()
install_sensitive_audit_guard()
install_returned_view_projection()
install_activity_checkin_code()
install_activity_reliability()
install_credit_appeal_reliability()
install_dorm_reliability()
install_dorm_projection()
install_atomic_student_applications()
# 原子申请入口安装后，再把本人解析收紧为同学生行锁，序列化并发重复提交。
install_student_application_lock()
# 必须在核心申诉实现完成后安装，包装具体受理人待办和结果消息。
install_appeal_todo_reconciliation()
install_appeal_repair()
# 将补偿队列接入现有学工周期扫描，避免一次孤立失败长期等待人工或下一次写请求。
install_appeal_repair_scheduler()
# SELF 必须先由服务端账号关系解析，后续画像、二课和申诉只能访问本人。
install_self_scope_guard()
# 核心审计安全门必须在既有兼容层之后安装，避免后续补丁再次放宽数据口径。
install_data_integrity_guard()
install_counselor_handover_guard()
install_risk_evidence_guard()
install_counselor_eval_guard()
install_funding_ext_guard()
install_archive_guard()
install_archive_file_guard()
install_talk_guard()
install_activity_accounting_guard()
install_activity_authority_guard()
install_stats_integrity_guard()
# 必须最后安装：收紧前述兼容层的 fail-closed、显式 version 与学生宿舍范围边界。
install_affairs_four_end_review_guard()
# 终态安全门在所有兼容层之后执行：强制学生本人身份，并机械检查教师移动读写权限登记。
install_affairs_four_end_terminal_guard(api_router)
