/** 学生端数据服务：关键业务走真实接口，岗位实习禁止回落 mock 假状态。 */
import { mockRequest, realFirst, realFirstStrict, realRequest } from './request'
import * as real from './realApi'
import * as internship from './internshipApi'
import * as M from '@/mock'

function mapInternshipDashboard(r) {
  if (!r || !r.hasData) {
    return {
      hasBatch: false,
      needSelect: !!r?.needSelect,
      candidates: r?.candidates || [],
      message: r?.message || '暂无实习记录',
      _real: true,
      company: '', post: '', schoolMentor: '', companyMentor: '', batch: '', batchId: '',
      timeline: [], weekly: { week: '第 1 周', submitted: false, lastFeedback: '' },
      checkin: { done: false, time: '', totalDays: 0, place: '', note: '仅在点击时采集定位，不后台定位' },
      status: { todayCheckin: 'PENDING', weekly: 'PENDING_SUBMIT', agreement: 'PENDING', insurance: 'PENDING', onboard: 'PENDING', leave: 'NONE' }
    }
  }
  return {
    hasBatch: true, needSelect: false, candidates: r.candidates || [],
    historyMode: !!r.historyMode, recordId: r.recordId || '', batchId: r.batchId || '',
    batch: r.batchName || '实习批次', company: r.enterpriseName || '', post: r.positionName || '',
    schoolMentor: r.advisorName || '待分配', companyMentor: r.enterpriseMentor || '待分配',
    statusText: r.recordStatus || '', timeline: r.timeline || [], _real: true,
    weekly: {
      week: `第 ${Number(r.weekly?.weekNumber || 1)} 周`,
      submitted: !!r.weekly?.submitted,
      lastFeedback: r.weekly?.lastFeedback || ''
    },
    checkin: {
      done: !!r.todayCheckin?.done,
      time: r.todayCheckin?.time || '',
      totalDays: Number(r.todayCheckin?.totalDays || 0),
      place: r.workLocation || r.enterpriseName || '实习地点待定',
      note: '仅在点击时采集定位，不后台定位'
    },
    status: {
      todayCheckin: r.todayCheckin?.done ? 'COMPLETED' : 'PENDING',
      weekly: r.weekly?.submitted ? 'COMPLETED' : 'PENDING_SUBMIT',
      agreement: r.agreementStatus || 'PENDING',
      insurance: r.insuranceStatus || 'PENDING',
      onboard: r.recordStatus || 'PENDING',
      leave: r.leaveStatus || 'NONE'
    }
  }
}

export const studentApi = {
  getHome: () =>
    realFirstStrict('student.home',
      () => real.studentHomeReal(),
      () => mockRequest(M.studentHome)),
  getProfile: () =>
    realFirstStrict('student.profile',
      () => real.enrichProfileReal(M.studentProfile),
      () => mockRequest(M.studentProfile)),
  getOrientation: () =>
    realFirstStrict('student.orientation',
      () => real.enrichOrientation(M.studentOrientation),
      () => mockRequest(M.studentOrientation)),
  getOrientationBatchStatus: () => real.orientationBatchStatus(),
  submitOrientationCollect: (body) => real.orientationCollectSubmit(body),
  submitOrientationGreenChannel: (body) => real.orientationGreenChannelSubmit(body),
  getServices: () =>
    realFirstStrict('student.campus',
      () => real.enrichCampusService({ categories: M.serviceCategories, items: M.serviceItems }),
      () => mockRequest({ categories: M.serviceCategories, items: M.serviceItems })),
  getAcademic: () =>
    realFirstStrict('student.academic',
      () => real.enrichAcademic(M.studentAcademic),
      () => mockRequest(M.studentAcademic)),
  getInternship: (batchId) => internship.studentInternshipDashboard(batchId).then(mapInternshipDashboard),
  getInternshipCompliance: (operation, batchId) => internship.studentInternshipCompliance(operation, batchId),
  getInternshipConsents: () => internship.studentInternshipConsents(),
  getInternshipConsentDetail: (id) => internship.studentInternshipConsentDetail(id),
  viewInternshipConsent: (id) => internship.studentInternshipConsentView(id),
  confirmInternshipConsent: (id, body) => internship.studentInternshipConsentConfirm(id, body),
  rejectInternshipConsent: (id, body) => internship.studentInternshipConsentReject(id, body),
  getInternshipSafetyCourses: (batchId) => internship.studentInternshipSafetyCourses(batchId),
  getInternshipSafetyCompletions: (batchId) => internship.studentInternshipSafetyCompletions(batchId),
  getInternshipSafetyCourseDetail: (id) => internship.studentInternshipSafetyCourseDetail(id),
  startInternshipSafetyCourse: (id) => internship.studentInternshipSafetyStart(id),
  submitInternshipSafetyCourse: (id, body) => internship.studentInternshipSafetySubmit(id, body),
  commitInternshipSafety: (id, body) => internship.studentInternshipSafetyCommit(id, body),
  getGraduation: () => real.enrichGraduation(),
  getGraduationActiveRound: () => real.gdActiveRound(),
  getGraduationTopics: (batchId) => real.gdTopics(batchId),
  getMyGraduationChangeRequests: () => real.gdMyChangeRequests(),
  submitGraduationChoices: (roundId, choices) => real.gdSubmitChoices(roundId, choices),
  withdrawGraduationChoices: (roundId) => real.gdWithdrawChoices(roundId),
  requestGraduationTopicChange: (newTopicId, reason) => real.gdRequestChange(newTopicId, reason),
  getGraduationProposal: () => real.gdProposal(),
  submitGraduationProposal: (body) => real.gdSubmitProposal(body),
  getGraduationFinal: () => real.gdFinal(),
  submitGraduationFinal: (body) => real.gdSubmitFinal(body),
  getGraduationTaskbook: () => real.gdTaskbook(),
  // 必须携带页面实际展示的版本；后端据此拒绝过期页面确认新版本任务书。
  confirmGraduationTaskbook: (taskbookVersion) =>
    realRequest('/mobile/graduation/taskbook/confirm', {
      method: 'POST', data: { taskbookVersion }
    }),
  getGraduationMidterm: () => real.gdMidterm(),
  submitGraduationMidtermRectify: (content) => real.gdMidtermRectify(content),
  getGraduationDefense: () => real.gdDefense(),
  getGraduationGrade: () => real.gdGrade(),
  appealGraduationGrade: (reason) => real.gdGradeAppeal(reason),
  getGraduationPeerTasks: () => real.gdPeerTasks(),
  submitGraduationPeer: (pid, opinion) => real.gdPeerSubmit(pid, opinion),
  rectifyGraduationPeer: (pid, note) => real.gdPeerRectify(pid, note),
  getGraduationArchive: () => real.gdArchive(),
  getEmployment: () => real.employmentMy(),
  getApplications: () =>
    realFirst('student.applications',
      () => real.selfApplications(),
      () => mockRequest({ tabs: M.applicationTabs, list: M.applications })),
  getMessagesPage: (tab = 'todo', page = 1, pageSize = 20) =>
    realFirstStrict('student.messages.page',
      () => real.selfMessagesPage(tab, page, pageSize),
      () => mockRequest({ tabs: M.studentMessageTabs, groups: M.studentMessages })),
  getMessages: () =>
    realFirstStrict('student.messages',
      () => real.selfMessages({ tabs: M.studentMessageTabs, groups: M.studentMessages }),
      () => mockRequest({ tabs: M.studentMessageTabs, groups: M.studentMessages })),
  submitServiceApply: (body) => real.submitServiceApply(body),
  submitWeeklyReport: (body) => real.submitWeeklyReport(body),
  submitCheckin: (body) => real.submitCheckin(body),
  getCheckinWeek: () => real.internshipCheckinWeek(),
  getInternshipEnterprises: (city) => real.internshipEnterprises(city),
  markMessageRead: (id) => real.markMessageRead(id),
  getMessageDetail: (id) => real.getMessageDetail(id),
  ackMessageReceipt: (id) => real.ackMessageReceipt(id),
  getInternshipAgreements: () => real.internshipAgreements(),
  getInternshipAgreementDetail: (id) => real.internshipAgreementDetail(id),
  confirmInternshipAgreement: (id, body) => real.confirmInternshipAgreement(id, body),
  getInternshipLeaves: () => real.internshipLeaves(),
  applyInternshipLeave: (body) => real.applyInternshipLeave(body),
  withdrawInternshipLeave: (id) => real.withdrawInternshipLeave(id),
  returnInternshipLeave: (id, body) => real.returnInternshipLeave(id, body),
  reportInternshipHelp: (body) => real.internshipHelpReport(body),
  getInternshipMakeups: () => real.internshipMakeups(),
  applyInternshipMakeup: (body) => real.applyInternshipMakeup(body),
  withdrawInternshipMakeup: (id) => real.withdrawInternshipMakeup(id),
  getInternshipSelfEval: () => real.internshipSelfEval(),
  submitInternshipSelfEval: (body) => real.submitInternshipSelfEval(body),
  getInternshipIntention: () => real.internshipIntentionMy(),
  saveInternshipIntention: (body) => real.saveInternshipIntention(body),
  submitInternshipIntention: () => real.submitInternshipIntention(),
  withdrawInternshipIntention: () => real.withdrawInternshipIntention(),
  getInternshipChangeRequests: () => real.internshipChangeRequests(),
  applyInternshipChange: (body) => real.applyInternshipChange(body),
  getInternshipApplications: () => real.internshipApplications(),
  saveInternshipApplication: (body) => real.saveInternshipApplication(body),
  submitInternshipApplication: (id) => real.submitInternshipApplication(id),
  withdrawInternshipApplication: (id) => real.withdrawInternshipApplication(id),
  getInternshipInsurance: () => real.internshipInsuranceMy(),
  submitInternshipInsurance: (body) => real.submitInternshipInsurance(body),
  getInternshipPlan: () => real.internshipPlanMy(),
  getInternshipPlanTasks: () => real.internshipPlanTasksMy(),
  ackInternshipPlan: () => real.ackInternshipPlan(),
  submitInternshipPlanTask: (sortOrder, body) => real.submitInternshipPlanTask(sortOrder, body),
  submitProcessReport: (body) => real.submitProcessReport(body),
  getAffairsOverview: () => real.affairsOverview(),
  getMyLeaves: () => real.affairsLeaveMy(),
  applyLeave: (body) => real.affairsLeaveApply(body),
  resubmitLeave: (leaveId, body) => real.affairsLeaveResubmit(leaveId, body),
  cancelLeave: (leaveId, body) => real.affairsLeaveCancel(leaveId, body),
  extendLeave: (leaveId, body) => real.affairsLeaveExtend(leaveId, body),
  getMyAid: () => real.affairsAidMy(),
  getAidBatches: () => real.affairsAidBatches(),
  applyAid: (body) => real.affairsAidApply(body),
  objectAid: (body) => real.affairsAidObjection(body),
  getMyTalks: () => real.affairsTalkMy(),
  getMyFunding: () => real.affairsFundingMy(),
  getFundingBatches: () => real.affairsFundingBatches(),
  applyFunding: (body) => real.affairsFundingApply(body),
  getMyDiscipline: () => real.affairsDisciplineMy(),
  appealDiscipline: (body) => real.affairsDisciplineAppeal(body),
  getMyDorm: () => real.affairsDormMy(),
  getDormOptions: () => real.affairsDormOptions(),
  getDormRooms: (buildingId, floor) => real.affairsDormRooms(buildingId, floor),
  getDormBeds: (roomId) => real.affairsDormBeds(roomId),
  selfSelectBed: (bedId) => real.affairsDormSelfSelect(bedId),
  getMyActivities: () => real.affairsMyActivities(),
  enrollActivity: (activityId, action) => real.affairsActivityEnroll(activityId, action),
  checkinActivity: (activityId, method) => real.affairsActivityCheckin(activityId, method),
  getPsySurveyQuestions: () => real.psySurveyQuestions(),
  submitPsySurvey: (answers, wantsContact) => real.psySurveySubmit(answers, wantsContact),
  getPsySurveyHistory: () => real.psySurveyHistory(),
  getNotifyPreferences: () => real.notifyPreferences(),
  setNotifyPreference: (key, enabled) => real.notifySetPreference(key, enabled),
  getMySchedule: () => real.acadScheduleMy(),
  getMyTranscript: () => real.acadTranscriptMy(),
  getMyAcadStatus: () => real.acadStatusMy(),
  getTransferOptions: () => real.acadTransferOptions(),
  submitStatusChange: (body) => real.acadStatusChange(body),
  printMyTranscript: (reason) => real.acadTranscriptPrint(reason),
  printMySchedule: (reason) => real.acadSchedulePrint(reason),
  getMyGraduation: () => real.acadGraduationMy(),
  getMyCredits: () => real.acadCreditsMy(),
  getMyWarnings: () => real.acadWarningMy(),
  getMyMakeup: () => real.acadMakeupMy(),
  getMakeupOptions: () => real.acadMakeupOptions(),
  applyRetake: (payload) => real.acadRetakeApply(payload),
  applyExemption: (payload) => real.acadExemptionApply(payload),
  getMyRegistration: () => real.acadRegistrationMy(),
  registerSelf: (batchId) => real.acadRegistrationRegister(batchId),
  deferRegistration: (batchId, reason, requestedUntil) => real.acadRegistrationDefer(batchId, reason, requestedUntil),
  getMyAttendance: () => real.acadAttendanceMy(),
  getMyCalendar: () => real.acadCalendarMy(),
  getMyClearance: () => real.acadClearanceMy(),
  printExamTicket: (reason) => real.acadExamTicketPrint(reason),
  printStatusChange: (body) => real.acadStatusChangePrint(body),
  getSelectionCourses: (batchId) => real.acadSelectionCourses(batchId),
  enrollSelection: (selectionCourseId) => real.acadSelectionEnroll(selectionCourseId),
  dropSelection: (selectionCourseId) => real.acadSelectionDrop(selectionCourseId),
  getMySelections: (batchId) => real.acadSelectionMy(batchId),
  getMyExamSchedule: () => real.acadExamMy(),
  getMyDeferOptions: () => real.acadExamDeferOptions(),
  getMyDeferrals: (status) => real.acadExamDeferMy(status),
  applyDefer: (examCourseId, reasonType, reason) => real.acadExamDeferApply(examCourseId, reasonType, reason),
  resubmitDefer: (deferId) => real.acadExamDeferResubmit(deferId),
  getMyRecognition: () => real.acadRecognitionMy(),
  submitRecognition: (body) => real.acadRecognitionSubmit(body),
  getMyRecheck: () => real.acadRecheckMy(),
  submitRecheck: (body) => real.acadRecheckSubmit(body),
  getMyTextbook: () => real.acadTextbookMy(),
  signTextbook: (recordId) => real.acadTextbookSign(recordId),
  getMyLevelExam: () => real.acadLevelExamMy(),
  registerLevelExam: (examId) => real.acadLevelRegister(examId),
  cancelLevelExam: (examId) => real.acadLevelCancel(examId),
  getMyMajorSplit: () => real.acadMajorSplitMy(),
  submitMajorSplit: (batchId, choices) => real.acadMajorSplitSubmit(batchId, choices),
  getMyEvaluationTasks: () => real.acadEvaluationTasks(),
  submitEvaluation: (body) => real.acadEvaluationSubmit(body),
  exportMyData: () => realRequest('/mobile/me/export-data')
}
export default studentApi
