/** 学生端数据服务：真实后端优先（主链：首页/档案/消息），其余仍 mock；失败自动回退。 */
import { mockRequest, realFirst, realFirstStrict, realRequest } from './request'
import * as real from './realApi'
import * as M from '@/mock'

export const studentApi = {
  getHome: () =>
    realFirst('student.home',
      () => mockRequest(M.studentHome).then((d) => real.enrichHome(d)),
      () => mockRequest(M.studentHome)),
  getProfile: () =>
    realFirstStrict('student.profile',
      () => real.enrichProfileReal(M.studentProfile),
      () => mockRequest(M.studentProfile)),
  getOrientation: () =>
    realFirstStrict('student.orientation',
      () => real.enrichOrientation(M.studentOrientation),
      () => mockRequest(M.studentOrientation)),
  getOrientationBatchStatus: () => real.orientationBatchStatus(),
  submitOrientationCollect: (body) => real.orientationCollectSubmit(body),
  submitOrientationGreenChannel: (body) => real.orientationGreenChannelSubmit(body),
  getServices: () =>
    realFirstStrict('student.campus',
      () => real.enrichCampusService({ categories: M.serviceCategories, items: M.serviceItems }),
      () => mockRequest({ categories: M.serviceCategories, items: M.serviceItems })),
  getAcademic: () =>
    realFirstStrict('student.academic',
      () => real.enrichAcademic(M.studentAcademic),
      () => mockRequest(M.studentAcademic)),
  getInternship: () => real.enrichInternship(),
  getGraduation: () => real.enrichGraduation(),
  // 毕业设计·选题/任务书/开题/中期/成果/答辩/成绩（真实接口，无 mock 兜底，业务错误透出）
  getGraduationActiveRound: () => real.gdActiveRound(),
  getGraduationTopics: (batchId) => real.gdTopics(batchId),
  getMyGraduationChangeRequests: () => real.gdMyChangeRequests(),
  submitGraduationChoices: (roundId, choices) => real.gdSubmitChoices(roundId, choices),
  withdrawGraduationChoices: (roundId) => real.gdWithdrawChoices(roundId),
  requestGraduationTopicChange: (newTopicId, reason) => real.gdRequestChange(newTopicId, reason),
  getGraduationProposal: () => real.gdProposal(),
  submitGraduationProposal: (body) => real.gdSubmitProposal(body),
  getGraduationFinal: () => real.gdFinal(),
  submitGraduationFinal: (body) => real.gdSubmitFinal(body),
  getGraduationTaskbook: () => real.gdTaskbook(),
  confirmGraduationTaskbook: () => real.gdTaskbookConfirm(),
  getGraduationMidterm: () => real.gdMidterm(),
  submitGraduationMidtermRectify: (content) => real.gdMidtermRectify(content),
  getGraduationDefense: () => real.gdDefense(),
  getGraduationGrade: () => real.gdGrade(),
  appealGraduationGrade: (reason) => real.gdGradeAppeal(reason),
  getGraduationPeerTasks: () => real.gdPeerTasks(),
  submitGraduationPeer: (pid, opinion) => real.gdPeerSubmit(pid, opinion),
  rectifyGraduationPeer: (pid, note) => real.gdPeerRectify(pid, note),
  getGraduationArchive: () => real.gdArchive(),
  // 就业去向：真实接口，无 mock 兜底（旧 intention/recommendedJobs/steps 字段无真实数据源，页面已不再展示）
  getEmployment: () => real.employmentMy(),
  getApplications: () =>
    realFirst('student.applications',
      () => real.selfApplications(),
      () => mockRequest({ tabs: M.applicationTabs, list: M.applications })),
  getMessages: () =>
    realFirstStrict('student.messages',
      () => real.selfMessages({ tabs: M.studentMessageTabs, groups: M.studentMessages }),
      () => mockRequest({ tabs: M.studentMessageTabs, groups: M.studentMessages })),
  // 写操作：业务错误（401/403/409/422）透出，不兜底成成功
  submitServiceApply: (body) => real.submitServiceApply(body),
  submitWeeklyReport: (body) => real.submitWeeklyReport(body),
  submitCheckin: (body) => real.submitCheckin(body),
  getCheckinWeek: () => real.internshipCheckinWeek(),
  getInternshipEnterprises: (city) => real.internshipEnterprises(city),
  markMessageRead: (id) => real.markMessageRead(id),
  // 岗位实习·学生自助（三方协议 / 请假 / 意向 / 自评 / 调岗退岗 / 保险 / 计划 / 过程报告）
  // 真实优先无 mock 兜底，业务错误（401/403/409/422）透出
  getInternshipAgreements: () => real.internshipAgreements(),
  getInternshipAgreementDetail: (id) => real.internshipAgreementDetail(id),
  confirmInternshipAgreement: (id, body) => real.confirmInternshipAgreement(id, body),
  getInternshipLeaves: () => real.internshipLeaves(),
  applyInternshipLeave: (body) => real.applyInternshipLeave(body),
  withdrawInternshipLeave: (id) => real.withdrawInternshipLeave(id),
  returnInternshipLeave: (id, body) => real.returnInternshipLeave(id, body),
  getInternshipMakeups: () => real.internshipMakeups(),
  applyInternshipMakeup: (body) => real.applyInternshipMakeup(body),
  withdrawInternshipMakeup: (id) => real.withdrawInternshipMakeup(id),
  getInternshipSelfEval: () => real.internshipSelfEval(),
  submitInternshipSelfEval: (body) => real.submitInternshipSelfEval(body),
  getInternshipIntention: () => real.internshipIntentionMy(),
  saveInternshipIntention: (body) => real.saveInternshipIntention(body),
  submitInternshipIntention: () => real.submitInternshipIntention(),
  withdrawInternshipIntention: () => real.withdrawInternshipIntention(),
  getInternshipChangeRequests: () => real.internshipChangeRequests(),
  applyInternshipChange: (body) => real.applyInternshipChange(body),
  getInternshipApplications: () => real.internshipApplications(),
  saveInternshipApplication: (body) => real.saveInternshipApplication(body),
  submitInternshipApplication: (id) => real.submitInternshipApplication(id),
  withdrawInternshipApplication: (id) => real.withdrawInternshipApplication(id),
  getInternshipInsurance: () => real.internshipInsuranceMy(),
  submitInternshipInsurance: (body) => real.submitInternshipInsurance(body),
  getInternshipPlan: () => real.internshipPlanMy(),
  getInternshipPlanTasks: () => real.internshipPlanTasksMy(),
  ackInternshipPlan: () => real.ackInternshipPlan(),
  submitInternshipPlanTask: (sortOrder, body) => real.submitInternshipPlanTask(sortOrder, body),
  submitProcessReport: (body) => real.submitProcessReport(body),
  // 13A 学工中心（P7 多端收口，真实优先无 mock 兜底，业务错误透出）
  getAffairsOverview: () => real.affairsOverview(),
  getMyLeaves: () => real.affairsLeaveMy(),
  resubmitLeave: (leaveId, body) => real.affairsLeaveResubmit(leaveId, body),
  cancelLeave: (leaveId, body) => real.affairsLeaveCancel(leaveId, body),
  extendLeave: (leaveId, body) => real.affairsLeaveExtend(leaveId, body),
  getMyAid: () => real.affairsAidMy(),
  getAidBatches: () => real.affairsAidBatches(),
  applyAid: (body) => real.affairsAidApply(body),
  objectAid: (body) => real.affairsAidObjection(body),
  getMyTalks: () => real.affairsTalkMy(),
  getMyFunding: () => real.affairsFundingMy(),
  getFundingBatches: () => real.affairsFundingBatches(),
  applyFunding: (body) => real.affairsFundingApply(body),
  getMyDiscipline: () => real.affairsDisciplineMy(),
  appealDiscipline: (body) => real.affairsDisciplineAppeal(body),
  getMyDorm: () => real.affairsDormMy(),
  getDormOptions: () => real.affairsDormOptions(),
  getDormRooms: (buildingId, floor) => real.affairsDormRooms(buildingId, floor),
  getDormBeds: (roomId) => real.affairsDormBeds(roomId),
  selfSelectBed: (bedId) => real.affairsDormSelfSelect(bedId),
  // 学工中心·学生活动与第二课堂（真实接口，无 mock 兜底）
  getMyActivities: () => real.affairsMyActivities(),
  enrollActivity: (activityId, action) => real.affairsActivityEnroll(activityId, action),
  checkinActivity: (activityId, method) => real.affairsActivityCheckin(activityId, method),
  // 心理健康自评（真实接口，无 mock 兜底）
  getPsySurveyQuestions: () => real.psySurveyQuestions(),
  submitPsySurvey: (answers, wantsContact) => real.psySurveySubmit(answers, wantsContact),
  getPsySurveyHistory: () => real.psySurveyHistory(),
  // 消息通知设置（真实接口，无 mock 兜底）
  getNotifyPreferences: () => real.notifyPreferences(),
  setNotifyPreference: (key, enabled) => real.notifySetPreference(key, enabled),
  // 13B 教务中心（P7 真实优先无 mock 兜底）
  getMySchedule: () => real.acadScheduleMy(),
  getMyTranscript: () => real.acadTranscriptMy(),
  getMyAcadStatus: () => real.acadStatusMy(),
  getTransferOptions: () => real.acadTransferOptions(),
  submitStatusChange: (body) => real.acadStatusChange(body),
  printMyTranscript: (reason) => real.acadTranscriptPrint(reason),
  printMySchedule: (reason) => real.acadSchedulePrint(reason),
  getMyGraduation: () => real.acadGraduationMy(),
  // 教务中心·学分修读/学业预警/补考重修/网上选课（真实接口，无 mock 兜底）
  getMyCredits: () => real.acadCreditsMy(),
  getMyWarnings: () => real.acadWarningMy(),
  getMyMakeup: () => real.acadMakeupMy(),
  getMakeupOptions: () => real.acadMakeupOptions(),
  applyRetake: (payload) => real.acadRetakeApply(payload),
  applyExemption: (payload) => real.acadExemptionApply(payload),
  getMyRegistration: () => real.acadRegistrationMy(),
  registerSelf: (batchId) => real.acadRegistrationRegister(batchId),
  deferRegistration: (batchId, reason, requestedUntil) => real.acadRegistrationDefer(batchId, reason, requestedUntil),
  getMyAttendance: () => real.acadAttendanceMy(),
  getMyCalendar: () => real.acadCalendarMy(),
  getMyClearance: () => real.acadClearanceMy(),
  printExamTicket: (reason) => real.acadExamTicketPrint(reason),
  printStatusChange: (body) => real.acadStatusChangePrint(body),
  getSelectionCourses: (batchId) => real.acadSelectionCourses(batchId),
  enrollSelection: (selectionCourseId) => real.acadSelectionEnroll(selectionCourseId),
  dropSelection: (selectionCourseId) => real.acadSelectionDrop(selectionCourseId),
  getMySelections: (batchId) => real.acadSelectionMy(batchId),
  // 缓考申请（真实接口，无 mock 兜底）
  getMyExamSchedule: () => real.acadExamMy(),
  getMyDeferOptions: () => real.acadExamDeferOptions(),
  getMyDeferrals: (status) => real.acadExamDeferMy(status),
  applyDefer: (examCourseId, reasonType, reason) => real.acadExamDeferApply(examCourseId, reasonType, reason),
  resubmitDefer: (deferId) => real.acadExamDeferResubmit(deferId),
  // 成绩认定/课程替代（学生自助，对标正方 3.16/3.27）
  getMyRecognition: () => real.acadRecognitionMy(),
  submitRecognition: (body) => real.acadRecognitionSubmit(body),
  getMyRecheck: () => real.acadRecheckMy(),
  submitRecheck: (body) => real.acadRecheckSubmit(body),
  getMyTextbook: () => real.acadTextbookMy(),
  signTextbook: (recordId) => real.acadTextbookSign(recordId),
  // 等级考务报名（学生自助，对标正方 3.13）
  getMyLevelExam: () => real.acadLevelExamMy(),
  registerLevelExam: (examId) => real.acadLevelRegister(examId),
  cancelLevelExam: (examId) => real.acadLevelCancel(examId),
  // 专业分流志愿（学生自助）
  getMyMajorSplit: () => real.acadMajorSplitMy(),
  submitMajorSplit: (batchId, choices) => real.acadMajorSplitSubmit(batchId, choices),
  // 学生评教（匿名）
  getMyEvaluationTasks: () => real.acadEvaluationTasks(),
  submitEvaluation: (body) => real.acadEvaluationSubmit(body),
  exportMyData: () => realRequest('/mobile/me/export-data')
}
export default studentApi
