/** 教师端数据服务：真实后端优先（主链：学生/审批/待办/消息/学生360），失败自动回退 mock。 */
import { mockRequest, realFirst, realFirstStrict, realRequest } from './request'
import * as real from './realApi'
import * as M from '@/mock'

export const teacherApi = {
  /** 与 PC 同源：/todos/summary + teacher-mobile todos；生产不得回落 mock 假工作台 */
  getWorkbench: (roleKey) =>
    realFirstStrict('teacher.workbench',
      () => real.teacherWorkbenchReal(roleKey),
      () => mockRequest(M.workbenchByRole[roleKey] || M.workbenchByRole.counselor)),
  getTodosPage: (group = 'all', page = 1, pageSize = 20) =>
    realFirstStrict('teacher.todos.page',
      () => real.teacherTodosPage(group, page, pageSize),
      () => mockRequest({ filters: M.todoFilters, list: M.teacherTodos })),
  getTodos: () => realFirst('teacher.todos', () => real.teacherTodosReal(), () => mockRequest({ filters: M.todoFilters, list: M.teacherTodos })),
  getApprovals: () => realFirst('teacher.approvals', () => real.teacherApprovalsReal(M.approvals), () => mockRequest(M.approvals)),
  actApproval: (id, type, reason) => real.actApproval(id, type, reason),
  reviewWeekly: (id, action, comment) => real.reviewWeeklyReal(id, action, comment),
  reviewProposal: (id, action, comment) => real.reviewProposalReal(id, action, comment),
  handleWarning: (id, action, note) => real.handleWarningReal(id, action, note),
  handleCheckin: (id, action, comment) => real.handleCheckinReal(id, action, comment),
  remindWeekly: (id) => real.remindWeeklyReal(id),
  createFollowup: (body) => real.createFollowupReal(body),
  getAffairs: () => real.teacherAffairs(),
  getMySchedule: () => real.acadTeacherScheduleMy(),
  getRiskStudentsPage: (level = 'all', page = 1, pageSize = 20) =>
    realFirstStrict('teacher.risk.page',
      () => real.teacherRiskStudentsPage(level, page, pageSize),
      () => mockRequest({ list: M.students.filter((s) => s.risk === 'HIGH' || s.risk === 'MEDIUM') })),
  getRiskStudents: () => realFirst('teacher.risk', () => real.teacherRiskStudents(), () => mockRequest(M.students.filter((s) => s.risk === 'HIGH' || s.risk === 'MEDIUM'))),
  getStudents: () => mockRequest(M.students),
  getStudent360: (id) => realFirstStrict('teacher.student360', () => real.teacherStudent360(id), () => mockRequest(M.student360[id] || null)),
  getMyClasses: () => real.teacherMyClasses(),
  getMyStudents: (classId) => real.teacherMyStudents(classId),
  getTalkList: (params) => real.teacherTalkList(params),
  getTalkDetail: (talkId) => real.teacherTalkDetail(talkId),
  createTalk: (body) => real.teacherTalkCreate(body),
  recordTalk: (talkId, body) => real.teacherTalkRecord(talkId, body),
  talkFollowUp: (talkId, action, content) => real.teacherTalkFollowUp(talkId, action, content),
  getMentalList: (level) => real.teacherMentalList(level),
  getMentalDetail: (refId, reason) => real.teacherMentalDetail(refId, reason),
  createMentalReferral: (body) => real.teacherMentalCreate(body),
  followMentalReferral: (refId, content) => real.teacherMentalFollow(refId, content),
  escalateMentalReferral: (refId, content) => real.teacherMentalEscalate(refId, content),
  closeMentalReferral: (refId, conclusion) => real.teacherMentalClose(refId, conclusion),
  getNotifyPreferences: () => real.teacherNotifyPreferences(),
  setNotifyPreference: (key, enabled) => real.teacherNotifySetPreference(key, enabled),
  publishNotice: (body) => real.teacherNotifyPublish(body),
  getDashboard: () => real.teacherDashboard(),
  getWeeklyReports: () => realFirstStrict('teacher.internship', () => real.teacherInternshipReal({ reports: M.weeklyReports, abnormal: M.abnormalCheckins }), () => mockRequest({ reports: M.weeklyReports, abnormal: M.abnormalCheckins })),
  getWeeklyDetail: (id) => real.teacherWeeklyDetail(id),
  getGdStudents: () => realFirst('teacher.graduation', () => real.teacherGraduationReal({ list: M.gdStudents, detail: M.gdReviewDetail }), () => mockRequest({ list: M.gdStudents, detail: M.gdReviewDetail })),
  createGuidance: (gdStudentId, body) => real.teacherGraduationGuidanceCreate(gdStudentId, body),
  getGraduationProposalDetail: (id) => real.gdTeacherProposalDetail(id),
  getGraduationFinalDetail: (id) => real.gdTeacherFinalDetail(id),
  getGraduationMaterialLibrary: (gdStudentId) =>
    realRequest(`/mobile/graduation/material-center/library?gdStudentId=${encodeURIComponent(gdStudentId)}&includeHistory=true`),
  reviewGraduationMaterial: (materialId, body) =>
    realRequest(`/mobile/graduation/material-center/materials/${encodeURIComponent(materialId)}/review`, {
      method: 'POST', data: body
    }),
  reviewFinal: (id, action, comment) => real.gdTeacherFinalReview(id, action, comment),
  getGraduationMidtermQueue: () => real.gdTeacherMidtermQueue(),
  getGraduationMidtermDetail: (id) => real.gdTeacherMidtermDetail(id),
  midtermCheck: (id, conclusion, comment, deadline) => real.gdTeacherMidtermCheck(id, conclusion, comment, deadline),
  midtermRectifyReview: (id, action, comment) => real.gdTeacherMidtermRectifyReview(id, action, comment),
  getGraduationMyReviews: () => real.gdTeacherReviewsMy(),
  submitReview: (id, score, opinion) => real.gdTeacherReviewSubmit(id, score, opinion),
  getGraduationChoicesPending: () => real.gdTeacherChoicesPending(),
  reviewGraduationChoice: (choiceId, action, reason) => real.gdTeacherChoiceReview(choiceId, action, reason),
  getGraduationChangeRequestsPending: () => real.gdTeacherChangeRequestsPending(),
  reviewGraduationChangeRequest: (requestId, action, comment) => real.gdTeacherChangeRequestReview(requestId, action, comment),
  getTalkStats: () => real.teacherTalkStats(),
  getMentalStats: () => real.teacherMentalStats(),
  getCampusServicePending: () => real.teacherCampusServicePending(),
  getAcademicWarnings: () => real.teacherAcademicWarnings(),
  getGraduationDefenseArrangements: () => real.gdTeacherDefenseArrangements(),
  getGraduationGradeQueue: () => real.gdTeacherGradeQueue(),
  getGraduationGradeDetail: (id) => real.gdTeacherGradeDetail(id),
  reviewGrade: (id, action, comment) => real.gdTeacherGradeReview(id, action, comment),
  getEmployment: () => realFirst('teacher.employment', () => real.teacherEmploymentReal({ stats: M.employmentStats, tabs: M.employmentTabs, list: M.employmentStudents, jobs: M.jobPool }), () => mockRequest({ stats: M.employmentStats, tabs: M.employmentTabs, list: M.employmentStudents, jobs: M.jobPool })),
  getEmploymentMyStudents: () => real.teacherEmploymentMyStudents(),
  transferEmploymentStudent: (studentId, newTeacher) => real.teacherEmploymentTransferStudent(studentId, newTeacher),
  getEmploymentCompanies: (status) => real.teacherEmploymentCompanies(status),
  createEmploymentCompany: (body) => real.teacherEmploymentCompanyCreate(body),
  disableEmploymentCompany: (companyId, reason) => real.teacherEmploymentCompanyDisable(companyId, reason),
  getEmploymentJobs: (companyId, status) => real.teacherEmploymentJobs(companyId, status),
  createEmploymentJob: (body) => real.teacherEmploymentJobCreate(body),
  disableEmploymentJob: (jobId, reason) => real.teacherEmploymentJobDisable(jobId, reason),
  getMessages: () => realFirstStrict('teacher.messages', () => real.teacherMessagesReal({ tabs: M.teacherMessageTabs, groups: M.teacherMessages }), () => mockRequest({ tabs: M.teacherMessageTabs, groups: M.teacherMessages })),
  orientationCheckin: (admissionNo) => real.teacherOrientationCheckin(admissionNo),
  getOrientationTodayCheckins: () => real.teacherOrientationTodayCheckins(),
  getOrientationDashboard: () => real.teacherOrientationDashboard(),
  getInternshipVisitPlans: () => real.teacherInternshipVisitPlans(),
  recordInternshipVisit: (internshipId) => real.teacherInternshipVisitRecord(internshipId),
  getMakeupPending: () => real.teacherMakeupPending(),
  reviewMakeup: (makeupId, action, comment) => real.teacherMakeupReview(makeupId, action, comment),
  getLeavePending: () => real.teacherLeavePending(),
  reviewLeave: (leaveId, action, comment) => real.teacherLeaveReview(leaveId, action, comment),
  getLeaveOverdue: () => real.teacherLeaveOverdue(),
  ackLeaveReturn: (leaveId, note) => real.teacherLeaveAckReturn(leaveId, note),
  getInternshipRisks: () => real.teacherInternshipRisks(),
  handleInternshipRisk: (riskId, body) => real.teacherInternshipRiskHandle(riskId, body),
  followInternshipRisk: (riskId, note) => real.teacherInternshipRiskFollow(riskId, note),
  closeInternshipRisk: (riskId, body) => real.teacherInternshipRiskClose(riskId, body),
  createInternshipGuidance: (body) => real.teacherInternshipGuidanceCreate(body),
  getStudentEvalPending: () => real.teacherStudentEvalPending(),
  getStudentEvalDetail: (evalId) => real.teacherStudentEvalDetail(evalId),
  submitStudentEvalAdvisorComment: (evalId, body) => real.teacherStudentEvalAdvisorComment(evalId, body),
  reviewStudentEval: (evalId, action, comment) => real.teacherStudentEvalReview(evalId, action, comment),
  getEnterpriseEvalPending: () => real.teacherEnterpriseEvalPending(),
  createEnterpriseEval: (body) => real.teacherEnterpriseEvalCreate(body),
  reviewEnterpriseEval: (evalId, action, comment, expectedVersion) => real.teacherEnterpriseEvalReview(evalId, action, comment, expectedVersion),
  getInsurancePending: () => real.teacherInsurancePending(),
  verifyInsurance: (insuranceId, action, comment) => real.teacherInsuranceVerify(insuranceId, action, comment),
  getInternshipChangePending: () => real.teacherInternshipChangePending(),
  reviewInternshipChange: (changeId, action, comment) => real.teacherInternshipChangeReview(changeId, action, comment),
  // 成绩列表由 batch-aware internshipApi 提供；教师仅核算，不发布。
  computeInternshipScore: (body) => real.teacherInternshipScoreCompute(body),
  // 教师只查看待学校终审协议，学校确认动作仅在管理端存在。
  getAgreementPendingSchool: () => real.teacherAgreementPendingSchool(),
  getProcessReportPending: () => real.teacherProcessReportPending(),
  getProcessReportDetail: (reportId) => real.teacherProcessReportDetail(reportId),
  reviewProcessReport: (reportId, action, comment) => real.teacherProcessReportReview(reportId, action, comment),
  getPlanTaskPending: () => real.teacherPlanTaskPending(),
  reviewPlanTask: (progressId, action, comment) => real.teacherPlanTaskReview(progressId, action, comment),
  getInternshipApplicationPending: () => real.teacherInternshipApplicationPending(),
  reviewInternshipApplication: (applicationId, action, comment) => real.teacherInternshipApplicationReview(applicationId, action, comment),
  getGraduationMyStudents: () => real.gdTeacherMyStudents(),
  getGraduationTaskbookList: () => real.teacherGraduationTaskbookList(),
  issueGraduationTaskbook: (gdStudentId, body) => real.teacherGraduationTaskbookIssue(gdStudentId, body),
  changeGraduationTaskbook: (gdStudentId, body) => real.teacherGraduationTaskbookChange(gdStudentId, body),
  getGraduationDefenseScorePending: () => real.teacherGraduationDefenseScorePending(),
  submitGraduationDefenseScore: (gdStudentId, body) => real.teacherGraduationDefenseScoreEntry(gdStudentId, body),
  getFamilyContactStudents: () => real.teacherFamilyContactStudents(),
  getFamilyContactList: (receiptStatus) => real.teacherFamilyContactList(receiptStatus),
  createFamilyContact: (studentId, body) => real.teacherFamilyContactCreate(studentId, body),
  markFamilyContactReceipt: (contactId, note) => real.teacherFamilyContactReceipt(contactId, note),
  getAffairsLeavePending: () => real.teacherAffairsLeavePending(),
  getAffairsLeaveFollowup: () => real.teacherAffairsLeaveFollowup(),
  getAffairsLeaveDetail: (leaveId) => real.teacherAffairsLeaveDetail(leaveId),
  approveAffairsLeave: (leaveId, comment) => real.teacherAffairsLeaveApprove(leaveId, comment),
  rejectAffairsLeave: (leaveId, reason) => real.teacherAffairsLeaveReject(leaveId, reason),
  returnAffairsLeave: (leaveId, reason) => real.teacherAffairsLeaveReturn(leaveId, reason),
  cancelConfirmAffairsLeave: (leaveId, action, body) => real.teacherAffairsLeaveCancelConfirm(leaveId, action, body),
  proxyCancelAffairsLeave: (leaveId, actualReturnAt, note) => real.teacherAffairsLeaveProxyCancel(leaveId, actualReturnAt, note),
  overdueHandleAffairsLeave: (leaveId, handleType, note) => real.teacherAffairsLeaveOverdueHandle(leaveId, handleType, note),
  extensionApproveAffairsLeave: (leaveId, action, reason) => real.teacherAffairsLeaveExtensionApprove(leaveId, action, reason),
  getAffairsAidPending: () => real.teacherAffairsAidPending(),
  getAffairsAidDetail: (applyId) => real.teacherAffairsAidDetail(applyId),
  reviewAffairsAid: (applyId, body) => real.teacherAffairsAidReview(applyId, body),
  getAffairsFundingPending: () => real.teacherAffairsFundingPending(),
  getAffairsFundingDetail: (appId) => real.teacherAffairsFundingDetail(appId),
  reviewAffairsFunding: (appId, body) => real.teacherAffairsFundingReview(appId, body),
  getAffairsDisciplinePending: () => real.teacherAffairsDisciplinePending(),
  getAffairsDisciplineDetail: (caseId) => real.teacherAffairsDisciplineDetail(caseId),
  reviewAffairsDiscipline: (caseId, body) => real.teacherAffairsDisciplineReview(caseId, body),
  getAffairsRiskPending: () => real.teacherAffairsRiskPending(),
  getAffairsRiskDetail: (riskId) => real.teacherAffairsRiskDetail(riskId),
  processAffairsRisk: (riskId, content) => real.teacherAffairsRiskProcess(riskId, content),
  closeAffairsRisk: (riskId, conclusion) => real.teacherAffairsRiskClose(riskId, conclusion),
  getAffairsDormPending: () => real.teacherAffairsDormPending(),
  reviewAffairsDormTransfer: (transferId, body) => real.teacherAffairsDormTransferReview(transferId, body),
  handleAffairsDormException: (exceptionId, note) => real.teacherAffairsDormExceptionHandle(exceptionId, note),
  getAffairsMyClasses: () => real.teacherAffairsMyClasses(),
  getAffairsClassStudents: (classId) => real.teacherAffairsClassStudents(classId),
  getAffairsCadreList: (classId) => real.teacherAffairsCadreList(classId),
  appointAffairsCadre: (classId, body) => real.teacherAffairsCadreAppoint(classId, body),
  removeAffairsCadre: (cadreId, reason) => real.teacherAffairsCadreRemove(cadreId, reason),
  getAffairsClassMaterials: (classId, materialType) => real.teacherAffairsClassMaterials(classId, materialType),
  addAffairsClassMaterial: (classId, body) => real.teacherAffairsClassMaterialAdd(classId, body),
  voidAffairsClassMaterial: (materialId, reason) => real.teacherAffairsClassMaterialVoid(materialId, reason),
  getAcademicMyTasks: (status) => real.teacherAcademicMyTasks(status),
  actAcademicTask: (taskId, action, reason) => real.teacherAcademicTaskAct(taskId, action, reason),
  getAcademicMySchedule: (termId, week) => real.teacherAcademicMySchedule(termId, week),
  academicScheduleConflictCheck: (body) => real.teacherAcademicScheduleConflictCheck(body),
  submitAcademicScheduleChange: (body) => real.teacherAcademicScheduleSubmit(body),
  getAcademicScheduleChanges: (status) => real.teacherAcademicScheduleChanges(status),
  getAcademicScheduleChangeDetail: (changeId) => real.teacherAcademicScheduleChangeDetail(changeId),
  cancelAcademicScheduleChange: (changeId, reason) => real.teacherAcademicScheduleCancel(changeId, reason),
  getAcademicDeferPending: () => real.teacherAcademicDeferPending(),
  reviewAcademicDefer: (deferId, action, reason) => real.teacherAcademicDeferReview(deferId, action, reason),
  getScheduleChangePending: () => real.teacherAcademicScheduleChangePending(),
  reviewScheduleChange: (changeId, action, comment) => real.teacherAcademicScheduleChangeReview(changeId, action, comment),
  getStatusChangePending: () => real.teacherAcademicStatusChangePending(),
  reviewStatusChange: (changeId, action, reason) => real.teacherAcademicStatusChangeReview(changeId, action, reason),
  getAcademicEvaluationBatches: () => real.teacherAcademicEvaluationBatches(),
  getAcademicEvaluationMyTasks: (evaluatorType, batchId) => real.teacherAcademicEvaluationMyTasks(evaluatorType, batchId),
  submitAcademicEvaluation: (taskId, body) => real.teacherAcademicEvaluationSubmit(taskId, body),
  getAcademicEvaluationResults: () => real.teacherAcademicEvaluationResults(),
  appealAcademicEvaluation: (resultId, reason) => real.teacherAcademicEvaluationAppeal(resultId, reason),
  getGradeTasks: (status) => real.teacherGradeTasks(status),
  getGradeRoster: (taskId) => real.teacherGradeRoster(taskId),
  enterGradeScore: (taskId, body) => real.teacherGradeEnterScore(taskId, body),
  submitGradeTask: (taskId) => real.teacherGradeSubmitTask(taskId),
  getAttendanceSessions: () => real.teacherAttendanceSessions(),
  getAttendanceClassOptions: () => real.teacherAttendanceClassOptions(),
  createAttendanceSession: (body) => real.teacherAttendanceCreate(body),
  getAttendanceDetail: (sessionId) => real.teacherAttendanceDetail(sessionId),
  markAttendance: (sessionId, studentId, status) => real.teacherAttendanceMark(sessionId, studentId, status),
  submitAttendanceSession: (sessionId) => real.teacherAttendanceSubmit(sessionId),
  getWorkloadDeclarations: () => real.teacherWorkloadMy(),
  submitWorkload: (body) => real.teacherWorkloadSubmit(body)
}
export default teacherApi
