"""20K 演示校就业时点与规模合同；纯单元测试，不连接数据库。"""
from app.services.sandbox_school_employment_seed import (
    DESTINATION_COUNTS,
    EXPECTED_EMPLOYMENT_COMPANIES,
    EXPECTED_EMPLOYMENT_FOLLOWUPS,
    EXPECTED_EMPLOYMENT_JOBS,
    EXPECTED_EMPLOYMENT_MATERIALS,
    EXPECTED_EMPLOYMENT_STUDENTS,
    EXPECTED_EMPLOYMENT_TODOS,
    EXPECTED_FROM_INTERNSHIP_SIGNED,
    EXPECTED_KEY_HELP,
)


def test_employment_cohort_is_exactly_2027_graduating_grade():
    assert EXPECTED_EMPLOYMENT_STUDENTS == 6400
    assert sum(DESTINATION_COUNTS.values()) == EXPECTED_EMPLOYMENT_STUDENTS
    assert DESTINATION_COUNTS["UNEMPLOYED"] == 5344
    assert DESTINATION_COUNTS["SIGNED"] == 768
    assert DESTINATION_COUNTS["SIGNED"] / EXPECTED_EMPLOYMENT_STUDENTS == 0.12


def test_employment_reuses_professional_enterprise_master():
    assert EXPECTED_EMPLOYMENT_COMPANIES == 80
    assert EXPECTED_EMPLOYMENT_JOBS == 160
    assert EXPECTED_FROM_INTERNSHIP_SIGNED == 640
    assert EXPECTED_FROM_INTERNSHIP_SIGNED < DESTINATION_COUNTS["SIGNED"]


def test_employment_support_workload_is_realistic_and_bounded():
    assert EXPECTED_KEY_HELP == 320
    assert EXPECTED_EMPLOYMENT_TODOS == EXPECTED_KEY_HELP
    assert EXPECTED_EMPLOYMENT_FOLLOWUPS == EXPECTED_KEY_HELP * 2 + 160
    assert EXPECTED_EMPLOYMENT_MATERIALS == EXPECTED_EMPLOYMENT_STUDENTS
