# 与 docker-compose.yml 一起使用，为 Nginx 增加 HTTPS。
services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx.https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
