<template>
  <view class="page-wrap">
    <MobilePrivacyGate />
    <MobileNavBar variant="teacher" title="迎新办理" show-back />
    <view class="page-pad">
      <view class="ow-tools"><input v-model="keyword" placeholder="搜索姓名 / 录取编号" confirm-type="search" @confirm="search" /><button size="mini" @click="search">查询</button></view>
      <view class="ow-tabs"><button v-for="t in tabs" :key="t.key" size="mini" :class="{ active: filter === t.key }" @click="filter = t.key; search()">{{ t.label }}</button></view>
      <MobileGlobalState :state="state" :description="loadError" @retry="load" @back="closePage">
        <view v-for="r in visibleRows" :key="r.id" class="ow-row" @click="open(r)"><view><text class="ow-name">{{ r.name }}</text><text class="ow-sub">{{ r.className || '待分班' }} · {{ reportLabel(r.reportStatus, r.stage) }}</text><text v-if="r.blockers?.length" class="ow-reason">{{ r.blockers.map(b => b.message).join('；') }}</text></view><text class="ow-link">{{ r.reportStatus === 'COLLEGE_CONFIRMED' ? '查看' : '办理' }}</text></view>
        <view v-if="!visibleRows.length" class="ow-empty">没有匹配事项。</view>
      </MobileGlobalState>
      <button v-if="needsLogin" @click="login">重新登录</button>
      <view class="ow-pages"><button size="mini" :disabled="page <= 1 || state === 'loading'" @click="page--; load()">上一页</button><text>{{ page }} / {{ Math.max(1, Math.ceil(total / 30)) }}</text><button size="mini" :disabled="page * 30 >= total || state === 'loading'" @click="page++; load()">下一页</button></view>
      <text class="ow-sub">现场报到请使用扫码入口。</text>
    </view>
    <view v-if="selected" class="ow-mask" @click.self="close"><view class="ow-sheet"><view class="ow-sheet-head"><text class="ow-name">{{ selected.name }}</text><button size="mini" :disabled="busy" @click="close">关闭</button></view><scroll-view scroll-y class="ow-body"><text class="ow-sub">{{ selected.studentNo || selected.admissionNo }} · {{ reportLabel(selected.reportStatus, selected.stage) }}</text><text class="ow-section">办理情况</text><text class="ow-sub">{{ selected.verdictLabel }}</text><text v-for="b in selected.blockers || []" :key="b.code" class="ow-reason">{{ b.message }}</text><text v-if="detail?.student" class="ow-section">住宿：{{ detail.student.dormStatusLabel }}</text><text v-if="detail?.student?.building" class="ow-sub">{{ detail.student.building }} {{ detail.student.room }}</text><text class="ow-section">迎新材料</text><text v-if="!materials.length" class="ow-sub">尚未提交迎新材料</text><view v-for="material in materials" :key="material.id" class="ow-material"><view class="ow-material-head"><text>{{ material.materialTypeLabel }}</text><MobileStatusTag :label="material.statusLabel" :type="material.status === 'APPROVED' ? 'success' : material.status === 'UPLOADED' ? 'warning' : 'danger'" /></view><FilePreviewer v-if="material.fileId" :file="material" @error="fileError" /><text v-if="material.returnReason" class="ow-reason">上次退回：{{ material.returnReason }}</text><template v-if="canManage && material.status === 'UPLOADED'"><textarea v-model="materialReasons[material.id]" class="ow-reason-input" maxlength="200" placeholder="退回时写明具体补充要求（不少于5字）" /><view class="ow-material-actions"><button size="mini" :disabled="busy || materialBusy" @click="reviewMaterial(material, 'return')">退回修改</button><button size="mini" class="btn-primary" :disabled="busy || materialBusy" @click="reviewMaterial(material, 'approve')">审核通过</button></view></template></view><text v-if="error" class="ow-error">{{ error }}</text>
          <view v-if="detail && canManage" class="ow-actions"><button v-if="detail.student.steps?.INFO !== 'DONE'" :disabled="busy" @click="confirmVerify">信息核验通过</button><button :disabled="busy || !selected.canFinalize" class="btn-primary" @click="confirmFinalize">学院确认入学</button></view>
          <text v-if="selected.reportStatus !== 'CHECKED_IN' && selected.reportStatus !== 'COLLEGE_CONFIRMED'" class="ow-sub">请先完成现场报到；材料、缴费与住宿等事项齐备后，再确认入学。</text>
        </scroll-view></view></view>
  </view>
</template>
<script>
import { realRequest } from '@/services/request'
import { toast } from '@/utils/nav'
import FilePreviewer from '@/components/file/FilePreviewer.vue'
export default {
  components: { FilePreviewer },
  data() { return { canManage: false, loadError: '', needsLogin: false, loadSerial: 0, state: 'loading', rows: [], total: 0, page: 1, keyword: '', filter: '', selected: null, detail: null, materials: [], materialReasons: {}, materialBusy: '', error: '', busy: false, requestId: '', tabs: [{ key: '', label: '全部' }, { key: 'ready', label: '可确认入学' }, { key: 'blocked', label: '待补办' }] } },
  computed: { visibleRows() { return this.rows } },
  onShow() { this.loadPermissions(); this.load() },
  methods: {
    async loadPermissions() { this.canManage = false; try { const ctx = await realRequest('/rbac/current-context'); const code = 'studentAffairs.orientation.manage'; this.canManage = ctx.moduleAccessHealthy !== false && !ctx.readonlyTenant && (ctx.permissionPatterns || []).some(p => p === '*' || p === code || (p.endsWith('.*') && code.startsWith(p.slice(0, -1))) || (p.startsWith('*.') && code.endsWith(p.slice(1)))) } catch { this.canManage = false } },
    reportLabel(v, stage) { if (stage === 'CANCELLED') return '已取消入学'; return ({ NOT_REPORTED: '未报到', PREPARED: '预报到完成', CHECKED_IN: '已现场报到', COLLEGE_CONFIRMED: '已确认入学', NO_SHOW: '未到校', DELAYED: '延迟报到' })[v] || '待核查' },
    search() { this.page = 1; this.load() },
    login() { uni.navigateTo({ url: '/pages/login/teacher/index' }) },
    closePage() { uni.navigateBack() },
    async load() { const serial = ++this.loadSerial; this.state = 'loading'; this.loadError = ''; this.needsLogin = false; try { const d = await realRequest('/orientation/qualifications', { data: { keyword: this.keyword, page: this.page, pageSize: 30, ...(this.filter ? { queue: this.filter } : {}) } }); if (serial !== this.loadSerial) return; this.rows = d.items || []; this.total = d.total || 0; this.state = 'ready' } catch (e) { if (serial !== this.loadSerial) return; this.loadError = e.message || '加载失败，请重试'; this.needsLogin = e.code === 401001; this.state = e.code === 403001 ? 'forbidden' : 'error' } },
    async open(row) { this.selected = row; this.detail = null; this.materials = []; this.materialReasons = {}; this.error = ''; this.requestId = `mp-orientation-finalize-${Date.now()}-${Math.random().toString(36).slice(2)}`; try { const [d, materialPage] = await Promise.all([realRequest(`/orientation/students/${row.id}`), realRequest('/orientation/materials', { data: { orientationStudentId: row.id, page: 1, pageSize: 50 } })]); if (this.selected?.id === row.id) { this.detail = d; this.materials = materialPage.items || [] } } catch (e) { this.error = e.message || '读取失败' } },
    close() { if (!this.busy && !this.materialBusy) { this.selected = null; this.materials = []; this.materialReasons = {} } },
    fileError(error) { toast(error?.message || '材料暂时无法打开') },
    async reviewMaterial(material, action) { if (this.busy || this.materialBusy || !this.canManage) return; const reason = String(this.materialReasons[material.id] || '').trim(); if (action === 'return' && reason.length < 5) return toast('请填写不少于5字的具体补充要求'); this.materialBusy = String(material.id); this.error = ''; try { await realRequest(`/orientation/materials/${material.id}/${action}`, { method: 'POST', data: action === 'return' ? { reason } : { comment: '移动端核验通过' } }); toast(action === 'return' ? '材料已退回' : '材料已通过'); const page = await realRequest('/orientation/materials', { data: { orientationStudentId: this.selected.id, page: 1, pageSize: 50 } }); this.materials = page.items || [] } catch (e) { this.error = e.message || '材料审核失败，请重试' } finally { this.materialBusy = '' } },
    confirmVerify() { uni.showModal({ title: '信息核验', content: `确认已核对 ${this.selected.name} 的个人信息？`, success: r => { if (r.confirm) this.perform('verify') } }) },
    confirmFinalize() { if (!this.selected.canFinalize) return; uni.showModal({ title: '学院确认入学', content: `确认 ${this.selected.name} 已完成报到及必办事项？`, success: r => { if (r.confirm) this.perform('finalize') } }) },
    async perform(action) { if (this.busy || !this.detail || !this.canManage) return; this.busy = true; this.error = ''; const row = this.selected; try { await realRequest(`/orientation/students/${row.id}/${action}`, { method: 'POST', data: action === 'verify' ? { passed: true } : { expectedVersion: this.detail.student.version, studentNo: row.studentNo, clientRequestId: this.requestId } }); toast(action === 'verify' ? '信息已核验' : '入学已确认'); this.selected = null; await this.load() } catch (e) { this.error = e.message || '操作失败，请刷新后核对'; } finally { this.busy = false } }
  }
}
</script>
<style scoped>
.ow-tools,.ow-tabs,.ow-pages,.ow-sheet-head{display:flex;gap:10px;align-items:center;margin-bottom:16px}.ow-tools input{flex:1;background:var(--bg-card,#fff);padding:10px;font-size:14px}.ow-tabs button{margin:0}.ow-tabs .active{color:var(--teacher-700);background:var(--teacher-50)}.ow-row{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:18px 0;border-bottom:1px solid var(--border-light,#e4e9f0)}.ow-name{font-size:16px;font-weight:600}.ow-sub,.ow-reason{display:block;font-size:12px;color:var(--text-secondary);line-height:1.7;margin-top:6px}.ow-reason,.ow-error{color:var(--danger-600)}.ow-link{font-size:13px;color:var(--teacher-700);flex-shrink:0}.ow-pages{justify-content:space-between;margin-top:20px;font-size:13px}.ow-empty{padding:24px 0;color:var(--text-secondary)}.ow-mask{position:fixed;inset:0;background:rgba(15,23,42,.4);z-index:1000;display:flex;align-items:flex-end}.ow-sheet{background:var(--bg-card,#fff);width:100%;padding:20px;box-sizing:border-box;border-radius:16px 16px 0 0}.ow-sheet-head{justify-content:space-between}.ow-sheet-head button{margin:0}.ow-body{max-height:65vh}.ow-section{display:block;font-size:14px;font-weight:600;margin-top:20px}.ow-actions{display:flex;flex-direction:column;gap:10px;margin:20px 0}.ow-actions button{width:100%;font-size:14px}.ow-error{display:block;font-size:13px;margin-top:14px}
.ow-material{display:grid;gap:10px;padding:12px 0;border-bottom:1px solid var(--border-light,#e4e9f0)}.ow-material-head,.ow-material-actions{display:flex;align-items:center;justify-content:space-between;gap:10px}.ow-reason-input{box-sizing:border-box;width:100%;min-height:72px;padding:10px;border:1px solid var(--border-base);border-radius:10px;background:var(--bg-page);font-size:13px}.ow-material-actions button{flex:1;margin:0}
</style>
