"""Canonical audit facade with Control Plane critical-action extensions."""
from __future__ import annotations

from app.services import audit_log_legacy as _legacy

_legacy.CRITICAL_ACTIONS = frozenset(set(_legacy.CRITICAL_ACTIONS) | {
    "PASSWORD_CHANGE",
    "PHONE_CANDIDATE_CHANGE",
    "PHONE_BINDING_CHANGE",
    "PHONE_POLICY_CHANGE",
    "PHONE_BINDING_LOOKUP",
    "PHONE_LEDGER_EXPORT",
    "PHONE_VERIFY_REMINDER",
    "ONBOARD_IMPORT",
    "WX_BIND_APPROVAL_AUTHORIZED",
    "WX_BINDING_ACTIVATED",
    "SECURITY_CHANGE_ACTIVATE",
    "SECURITY_CHANGE_ROLLBACK",
    "PLATFORM_DUTY_CHANGE",
    "PLATFORM_ELEVATION_CHANGE",
    "PLATFORM_SUPPORT_SESSION_CHANGE",
    "PLATFORM_ACCESS_REVIEW_CHANGE",
    "ROLE_TEMPLATE_PUBLISH",
    "ROLE_CREATE",
    "PLATFORM_PRODUCT_IAM_PUBLISH",
    "CUSTOM_ROLE_BINDING_RECONCILE",
    "USER_DISABLE",
    "USER_ENABLE",
    "USER_UNLOCK",
    "ROLE_DISABLE",
    "ROLE_ENABLE",
    "BRAND_CONFIG",
    "BRAND_CONFIG_RESET",
    "USER_BATCH_DISABLE",
    "USER_BATCH_ENABLE",
    "CONFIG_OVERRIDE_RESTORE_INHERITANCE",
    "ORG_NODE_DISABLE",
    "ORG_NODE_ENABLE",
    "PLATFORM_TENANT_PROFILE_UPDATE",
    "ACCOUNT_BINDING_REPAIR",
    "ACCOUNT_BINDING_REVOKE",
    "ACCOUNT_COMPROMISE_CONTAINED",
    "PLATFORM_SUPPORT_TICKET_CREATE",
    "PLATFORM_SUPPORT_TICKET_TRANSITION",
    "PLATFORM_TRAINING_CREATE",
    "PLATFORM_TRAINING_COMPLETE",
    "PLATFORM_RENEWAL_TASK_CREATE",
    "PLATFORM_RENEWAL_TASK_TRANSITION",
    "PLATFORM_DELIVERY_CONSUMER_SMOKE_RECORDED",
    "PLATFORM_DELIVERY_ACCEPTED",
    "PLATFORM_ORDER_PAID",
    "PLATFORM_ORDER_CANCEL",
    "PLATFORM_ORDER_ACTIVATION_REPAIRED",
    "COMMERCIAL_SKU_PUBLISH",
    "COMMERCIAL_ITEMIZED_ORDER_CREATE",
    "COMMERCIAL_SALES_LEDGER_EXPORT",
    "COMMERCIAL_MODULE_SOURCE_ACTIVATE",
    "COMMERCIAL_MODULE_SOURCE_CANCEL",
    "COMMERCIAL_MODULE_SOURCE_CANCEL_SCHEDULE",
    "COMMERCIAL_MODULE_SOURCE_CANCEL_UNDO",
    "COMMERCIAL_MODULE_DELIVERY_ACCEPT",
    "COMMERCIAL_MODULE_OFFBOARD_FREEZE",
    "COMMERCIAL_MODULE_OFFBOARD_CANCEL",
    "COMMERCIAL_MODULE_EXPORT_BIND",
    "COMMERCIAL_MODULE_EXPORT_ACCEPT",
    "COMMERCIAL_READER_CUTOVER",
    "COMMERCIAL_REFUND_REQUEST",
    "COMMERCIAL_REFUND_APPROVE",
    "COMMERCIAL_REFUND_REJECT",
    "COMMERCIAL_REFUND_SETTLE",
    "COMMERCIAL_INVOICE_REQUEST",
    "COMMERCIAL_INVOICE_ISSUE",
    "COMMERCIAL_INVOICE_VOID",
    "COMMERCIAL_REFUND_AFTERSALES_LINK",
    "COMMERCIAL_SERVICE_COST_RECORD",
    "COMMERCIAL_SLA_POLICY_UPDATE",
    "COMMERCIAL_SLA_POLICY_RESET",
})

from app.services.audit_log_legacy import *  # noqa: F401,F403,E402

CRITICAL_ACTIONS = _legacy.CRITICAL_ACTIONS


def __getattr__(name: str):
    return getattr(_legacy, name)


def __dir__():
    return sorted(set(globals()) | set(dir(_legacy)))
