"""公共文件中心扫描状态常量。"""
from __future__ import annotations

SCAN_NOT_REQUIRED = "NOT_REQUIRED"
SCAN_PENDING = "PENDING"
SCAN_RUNNING = "RUNNING"
SCAN_CLEAN = "CLEAN"
SCAN_INFECTED = "INFECTED"
SCAN_ERROR = "ERROR"

JOB_PENDING = "PENDING"
JOB_RUNNING = "RUNNING"
JOB_RETRY = "RETRY"
JOB_SUCCEEDED = "SUCCEEDED"
JOB_DEAD = "DEAD"
JOB_CANCELLED = "CANCELLED"

SCAN_JOB_TYPE = "FILE_SCAN"

TERMINAL_SCAN_STATES = frozenset({SCAN_CLEAN, SCAN_INFECTED, SCAN_ERROR})
READY_SCAN_STATES = frozenset({SCAN_NOT_REQUIRED, SCAN_CLEAN})
