"""007 当前 2026 秋季实习批次的真实可演示过程链。"""
from __future__ import annotations
from datetime import date, datetime, timedelta
from sqlalchemy import func, select

REFERENCE_NOW = datetime(2026, 8, 28, 10, 30)
MARKER = "007-INT-OP-2026"

def _one(db, model, tenant_id, **where):
    terms=[model.tenant_id == tenant_id]
    if hasattr(model, "is_deleted"): terms.append(model.is_deleted.is_(False))
    terms.extend(getattr(model,k)==v for k,v in where.items())
    return db.scalars(select(model).where(*terms)).first()
def _put(db, model, tenant_id, key, vals):
    row=_one(db, model, tenant_id, **key)
    if row is None:
        row=model(tenant_id=tenant_id, **key, **vals); db.add(row); db.flush()
    return row

def seed_internship_operational_coverage(db, tenant_id: int) -> dict:
    from app.core.field_crypto import encrypt_sensitive, hash_sensitive
    from app.services.sandbox_school_credentials import opaque_background_password_hash
    from app.models import (EmpCompany, InternshipBatch, InternshipRecord, InternshipPosition, Major, StudentProfile, User)
    from app.models.employment import EmpJob, InternshipEnterpriseContact
    from app.models.internship_enterprise_portal import (InternshipCampaignEnterprise, InternshipEnterpriseAccessGrant,
        InternshipEnterpriseMember, InternshipRecruitmentCampaign, StudentInternshipProfile, StudentInternshipProfileItem,
        InternshipApplicationMaterialSnapshot, InternshipEnterpriseApplicationDecision, InternshipPlacementSnapshot,
        InternshipVolunteerGroup)
    from app.models.file import FileObject
    from app.models.internship import (InternshipAgreement, InternshipArchive, InternshipBatchParticipant,
        InternshipBatchScopeRule,
        InternshipBatchPlan, InternshipChangeRequest, InternshipCommunicationLog, InternshipComplaint,
        InternshipEnterpriseEval, InternshipFinalScore, InternshipGuidance, InternshipInsurance, InternshipLeave,
        InternshipMakeup, InternshipPlanAck, InternshipPlanTaskProgress, InternshipProcessReport, InternshipAuditTrail,
        InternshipScoreConfig, InternshipStudentEval, InternshipVisit, InternshipVisitPlan)
    from app.models.internship_agreement_template import InternshipAgreementTemplate
    from app.models.internship_compliance import (InternshipComplianceExemption, InternshipComplianceTemplate,
        InternshipConsent, InternshipEmergencyPlan, InternshipEnterpriseInspection, InternshipEvidencePackage,
        InternshipIncident, InternshipRemunerationRecord, InternshipSafetyCompletion, InternshipSafetyCourse,
        InternshipSpecialFiling)
    from app.models.internship_match import InternshipApplication, InternshipIntention, InternshipMatch

    batch=_one(db, InternshipBatch, tenant_id, batch_no="INT-2024-2026FALL")
    records=list(db.scalars(select(InternshipRecord).where(InternshipRecord.tenant_id==tenant_id, InternshipRecord.batch_id==batch.id, InternshipRecord.is_deleted.is_(False), InternshipRecord.destination_type=="ASSIGNED").order_by(InternshipRecord.id).limit(6)).all()) if batch else []
    admin=_one(db, User, tenant_id, login_name="admin2")
    evidence=_one(db, FileObject, tenant_id, file_key="007-GOV-2026/leave-approval-evidence.md")
    if not batch or not admin or not evidence or len(records)<6: raise RuntimeError("internship operational seed prerequisites unavailable")
    _put(db, InternshipBatchScopeRule, tenant_id, {"batch_id": batch.id}, {
        "rule_json": {"grades": ["2024"], "collegeIds": [], "majorIds": [], "classIds": [],
                      "studentIds": [], "excludeStudentIds": []},
        "last_preview_count": 6400, "last_preview_at": REFERENCE_NOW-timedelta(days=60),
        "frozen_at": REFERENCE_NOW-timedelta(days=58), "frozen_by": admin.real_name,
    })
    rec, rec2, rec3, rec4, rec5, rec6=records
    company=db.get(EmpCompany, rec.enterprise_id); position=db.get(InternshipPosition, rec.position_id)
    advisor=db.get(User, rec.advisor_user_id) or admin
    if not company or not position: raise RuntimeError("assigned internship record lacks real enterprise/position")
    file_id=str(evidence.id)
    # 企业协同链只使用已准入的真实企业、岗位与资格合格的在册学生；第二轮补录尚未落岗，
    # 因而不会虚构完成结果，也不会改变现有 6,100 人已分配容量口径。
    candidates=list(db.scalars(select(InternshipRecord).join(StudentProfile, StudentProfile.id==InternshipRecord.student_id).where(InternshipRecord.tenant_id==tenant_id, InternshipRecord.batch_id==batch.id, InternshipRecord.destination_type=="NONE", InternshipRecord.is_deleted.is_(False), StudentProfile.is_deleted.is_(False)).order_by(InternshipRecord.id).limit(4)).all())
    candidate_major=db.get(Major,db.get(StudentProfile,candidates[0].student_id).major_id) if candidates else None
    if len(candidates)<4 or not candidate_major or any(db.get(StudentProfile,row.student_id).major_id!=candidate_major.id for row in candidates): raise RuntimeError("internship recruitment seed requires four unassigned students in the same major")
    for candidate in candidates:
        if candidate.eligibility_status != "QUALIFIED":
            candidate.eligibility_status="QUALIFIED";candidate.remark="第二轮补录前完成实习资格复核，允许进入岗位志愿环节。"
            db.add(InternshipAuditTrail(tenant_id=tenant_id,target_id=candidate.id,target_type="RECORD",action="ELIGIBILITY_APPROVE",operator_name=advisor.real_name,detail_json={"from":"PENDING","to":"QUALIFIED","reason":"第二轮补录资格材料复核通过"},occurred_at=REFERENCE_NOW-timedelta(days=2)))
        candidate_profile=db.get(StudentProfile,candidate.student_id)
        _put(db,InternshipBatchParticipant,tenant_id,{"batch_id":batch.id,"student_id":candidate.student_id},{"source":"MANUAL","snapshot_student_no":candidate_profile.student_no,"snapshot_name":candidate_profile.real_name,"snapshot_class_name":None,"snapshot_college_name":None,"internship_id":candidate.id,"status":"ACTIVE","remove_reason":None})
    recruitment_row=db.execute(select(InternshipRecord,InternshipPosition,EmpCompany).join(InternshipPosition,InternshipPosition.id==InternshipRecord.position_id).join(EmpCompany,EmpCompany.id==InternshipRecord.enterprise_id).join(StudentProfile,StudentProfile.id==InternshipRecord.student_id).where(InternshipRecord.tenant_id==tenant_id,InternshipRecord.destination_type=="ASSIGNED",InternshipRecord.is_deleted.is_(False),StudentProfile.major_id==candidate_major.id).order_by(InternshipRecord.id)).first()
    if not recruitment_row: raise RuntimeError("internship recruitment seed requires an existing professional position pair")
    _,recruitment_position,recruitment_company=recruitment_row
    campaign=_put(db,InternshipRecruitmentCampaign,tenant_id,{"campaign_code":f"{MARKER}-ROUND2"},{"batch_id":batch.id,"campaign_name":"2026 秋季岗位实习第二轮补录","round_no":2,"status":"OPEN","invite_start_at":REFERENCE_NOW-timedelta(days=8),"invite_end_at":REFERENCE_NOW-timedelta(days=2),"position_submit_start_at":REFERENCE_NOW-timedelta(days=7),"position_submit_end_at":REFERENCE_NOW-timedelta(days=1),"student_select_start_at":REFERENCE_NOW-timedelta(days=1),"student_select_end_at":REFERENCE_NOW+timedelta(days=7),"enterprise_decision_start_at":REFERENCE_NOW+timedelta(days=1),"enterprise_decision_end_at":REFERENCE_NOW+timedelta(days=12),"school_confirm_start_at":REFERENCE_NOW+timedelta(days=2),"school_confirm_end_at":REFERENCE_NOW+timedelta(days=14),"enterprise_access_end_at":REFERENCE_NOW+timedelta(days=20),"enterprise_confirm_required":True,"application_material_policy_json":{"resume":True,"certificate":True,"consentVersion":"2026.2"},"teacher_confirm_sla_hours":48,"remark":"面向尚未落岗学生的真实第二轮补录，不改变已分配学生去向。"})
    archived_campaign=_put(db,InternshipRecruitmentCampaign,tenant_id,{"campaign_code":f"{MARKER}-ROUND1"},{"batch_id":batch.id,"campaign_name":"2026 秋季岗位实习企业资源预征集","round_no":1,"status":"ARCHIVED","invite_start_at":REFERENCE_NOW-timedelta(days=80),"invite_end_at":REFERENCE_NOW-timedelta(days=70),"position_submit_start_at":REFERENCE_NOW-timedelta(days=69),"position_submit_end_at":REFERENCE_NOW-timedelta(days=60),"student_select_start_at":REFERENCE_NOW-timedelta(days=59),"student_select_end_at":REFERENCE_NOW-timedelta(days=55),"enterprise_decision_start_at":REFERENCE_NOW-timedelta(days=54),"enterprise_decision_end_at":REFERENCE_NOW-timedelta(days=50),"school_confirm_start_at":REFERENCE_NOW-timedelta(days=49),"school_confirm_end_at":REFERENCE_NOW-timedelta(days=45),"enterprise_access_end_at":REFERENCE_NOW-timedelta(days=40),"enterprise_confirm_required":True,"application_material_policy_json":{"preSurvey":True},"teacher_confirm_sla_hours":48,"remark":"已结束的企业资源预征集留痕；正式学生志愿在第二轮进行。"})
    company_rows=list(db.scalars(select(EmpCompany).where(EmpCompany.tenant_id==tenant_id,EmpCompany.coop_status=="ACTIVE",EmpCompany.qualification_status=="PASSED",EmpCompany.blacklist.is_(False),EmpCompany.is_deleted.is_(False)).order_by(EmpCompany.id).limit(3)).all())
    if len(company_rows)<3: raise RuntimeError("internship recruitment seed requires three admitted enterprises")
    company2,company3=company_rows[1],company_rows[2]
    contact=_put(db,InternshipEnterpriseContact,tenant_id,{"company_id":recruitment_company.id,"email":"hr.tourism007@example.edu.cn"},{"contact_type":"CONTACT","name":"周雯","title":"人力资源专员","phone_encrypted":encrypt_sensitive("13900000071","phone"),"is_primary":True,"remark":"007 演示企业协同联系人，已完成学校资质核验。","status":"ACTIVE"})
    enterprise_user=_one(db,User,tenant_id,login_name="sandbox-tourism-company-hr")
    if enterprise_user is None:
        enterprise_user=User(tenant_id=tenant_id,login_name="sandbox-tourism-company-hr",real_name=contact.name,password_hash=opaque_background_password_hash(),user_type="ENTERPRISE_MENTOR",phone_encrypted=encrypt_sensitive("13900000071","phone"),phone_hash=hash_sensitive("13900000071","phone"),status="ACTIVE",must_change_password=True);db.add(enterprise_user);db.flush()
    member=_put(db,InternshipEnterpriseMember,tenant_id,{"company_id":recruitment_company.id,"user_id":enterprise_user.id},{"contact_id":contact.id,"member_role":"HR","status":"ACTIVE","is_primary":True,"invited_phone_hash":hash_sensitive("13900000071","phone"),"invite_token_hash":hash_sensitive(f"{MARKER}-enterprise-invite","internship_enterprise_invite"),"invite_expires_at":REFERENCE_NOW-timedelta(days=5),"invited_at":REFERENCE_NOW-timedelta(days=8),"accepted_at":REFERENCE_NOW-timedelta(days=7),"last_active_at":REFERENCE_NOW-timedelta(hours=3)})
    for camp,comp,status,source in ((campaign,company,"ACCEPTED","MANUAL"),(campaign,company2,"INVITED","REUSE"),(campaign,company3,"DECLINED","MANUAL"),(archived_campaign,company,"ACCEPTED","REUSE")):
        _put(db,InternshipCampaignEnterprise,tenant_id,{"campaign_id":camp.id,"company_id":comp.id},{"status":status,"invite_source":source,"invited_by_user_id":admin.id,"invited_at":REFERENCE_NOW-timedelta(days=8),"accepted_at":REFERENCE_NOW-timedelta(days=7) if status=="ACCEPTED" else None,"declined_at":REFERENCE_NOW-timedelta(days=6) if status=="DECLINED" else None,"revoked_at":None,"revoke_reason":None})
    _put(db,InternshipCampaignEnterprise,tenant_id,{"campaign_id":campaign.id,"company_id":recruitment_company.id},{"status":"ACCEPTED","invite_source":"REUSE","invited_by_user_id":admin.id,"invited_at":REFERENCE_NOW-timedelta(days=8),"accepted_at":REFERENCE_NOW-timedelta(days=7),"declined_at":None,"revoked_at":None,"revoke_reason":None})
    _put(db,InternshipEnterpriseAccessGrant,tenant_id,{"member_id":member.id,"grant_type":"RECRUITMENT","campaign_id":campaign.id,"batch_id":batch.id},{"company_id":recruitment_company.id,"valid_from":REFERENCE_NOW-timedelta(days=7),"valid_until":REFERENCE_NOW+timedelta(days=20),"status":"ACTIVE","revoked_at":None,"revoked_by_user_id":None,"revoke_reason":None})
    _put(db,InternshipEnterpriseAccessGrant,tenant_id,{"member_id":member.id,"grant_type":"INTERNSHIP_COLLAB","campaign_id":None,"batch_id":batch.id},{"company_id":recruitment_company.id,"valid_from":batch.start_date,"valid_until":batch.end_date,"status":"ACTIVE","revoked_at":None,"revoked_by_user_id":None,"revoke_reason":None})
    _put(db,InternshipEnterpriseAccessGrant,tenant_id,{"member_id":member.id,"grant_type":"RECRUITMENT","campaign_id":archived_campaign.id,"batch_id":batch.id},{"company_id":recruitment_company.id,"valid_from":REFERENCE_NOW-timedelta(days=80),"valid_until":REFERENCE_NOW-timedelta(days=40),"status":"EXPIRED","revoked_at":None,"revoked_by_user_id":None,"revoke_reason":None})
    legacy_position=_one(db,InternshipPosition,tenant_id,campaign_id=campaign.id,source_type="ENTERPRISE")
    if legacy_position and legacy_position.company_id != recruitment_company.id:
        legacy_position.company_id=recruitment_company.id;legacy_position.company_name=recruitment_company.name;legacy_position.title=recruitment_position.title;legacy_position.category=recruitment_position.category;legacy_position.major_requirement=candidate_major.major_name;legacy_position.work_location=recruitment_position.work_location;legacy_position.work_address=recruitment_position.work_address;legacy_position.salary_range=recruitment_position.salary_range;legacy_position.mentor_contact_id=contact.id
        for legacy_job in db.scalars(select(EmpJob).where(EmpJob.tenant_id==tenant_id,EmpJob.company_id==company.id,EmpJob.title=="软件测试实习生（第二轮补录）",EmpJob.is_deleted.is_(False))).all(): legacy_job.is_deleted=True;legacy_job.remark="007 补录岗位首次校验未通过后已由正确专业岗位替代。"
        db.flush()
    campaign_position=_put(db,InternshipPosition,tenant_id,{"company_id":recruitment_company.id,"campaign_id":campaign.id,"title":recruitment_position.title},{"company_name":recruitment_company.name,"batch_id":batch.id,"source_type":"ENTERPRISE","category":recruitment_position.category,"major_requirement":candidate_major.major_name,"grade_requirement":"2024","work_location":recruitment_position.work_location,"geofence_lat":recruitment_position.geofence_lat,"geofence_lng":recruitment_position.geofence_lng,"geofence_radius_m":recruitment_position.geofence_radius_m,"salary_range":recruitment_position.salary_range,"subsidy":recruitment_position.subsidy,"headcount":2,"allocated_count":0,"mentor_contact_id":contact.id,"mentor_name":"企业业务导师","risk_flag":False,"risk_note":None,"daily_hours":8,"weekly_hours":40,"shift_type":"DAY","night_shift":False,"overtime_allowed":False,"rest_days":"双休","rest_days_per_week":2,"remuneration_type":"MONTHLY","remuneration_amount":3500,"remuneration_cycle":"MONTHLY","accommodation_provided":False,"meal_provided":True,"hazardous_flag":False,"special_equipment":None,"work_content":"参与岗位服务接待、产品讲解和数据整理，按周形成学习记录。","work_address":recruitment_company.address,"prohibited_reason":None,"rights_status":"PASSED","rights_checked_at":REFERENCE_NOW-timedelta(days=3),"rights_rule_version":"2026.2","status":"PUBLISHED","remark":"007 第二轮补录企业自主发布岗位，容量尚未占用。","publish_at":REFERENCE_NOW-timedelta(days=1),"archived_at":None,"archived_by":None})
    profiles=[]
    for index,candidate in enumerate(candidates,1):
        profile=_put(db,StudentInternshipProfile,tenant_id,{"student_id":candidate.student_id},{"profile_version":1,"headline":"软件技术专业学生实习求职档案","self_intro":"已完成专业核心课程与校内项目实训，期望在开发测试岗位接受企业导师指导。","strengths":"Java 基础、接口测试、团队协作与周报复盘。","available_from":date(2026,8,28),"available_until":date(2027,1,15),"expected_locations_json":[position.work_location],"skill_tags_json":["Java","SQL","接口测试"],"resume_template_code":"INTERNSHIP_STANDARD_V1"});profiles.append(profile)
        _put(db,StudentInternshipProfileItem,tenant_id,{"profile_id":profile.id,"item_type":"PROJECT","title":"校内订单项目接口测试实训"},{"organization":"跃科职业技术学院软件技术实训中心","description":"完成接口用例、缺陷记录和迭代复盘。","start_date":date(2026,4,1),"end_date":date(2026,6,20),"level":"校级实训","source_type":"SCHOOL_FACT","source_ref_type":"PRACTICE_COURSE","source_ref_id":str(position.id),"verification_status":"VERIFIED","sort_order":index})
    group_states=(("DRAFT",None),("SUBMITTED",REFERENCE_NOW-timedelta(hours=4)),("NEEDS_REVISION",REFERENCE_NOW-timedelta(days=1)),("LOCKED",REFERENCE_NOW-timedelta(days=1)))
    groups=[]
    for candidate,profile,(group_status,submitted_at) in zip(candidates,profiles,group_states):
        group=_put(db,InternshipVolunteerGroup,tenant_id,{"record_id":candidate.id,"campaign_id":campaign.id},{"student_id":candidate.student_id,"batch_id":batch.id,"status":group_status,"submission_version":1 if group_status!="DRAFT" else 0,"current_material_snapshot_id":None,"submitted_at":submitted_at,"locked_application_id":None,"locked_at":REFERENCE_NOW-timedelta(hours=8) if group_status=="LOCKED" else None,"locked_by_decision_id":None,"teacher_confirm_deadline":REFERENCE_NOW+timedelta(hours=40) if group_status=="LOCKED" else None,"approved_at":None,"revision_requested_at":REFERENCE_NOW-timedelta(days=1) if group_status=="NEEDS_REVISION" else None,"revision_reason":"请补充项目成果说明后再次提交。" if group_status=="NEEDS_REVISION" else None,"released_at":None,"release_reason":None,"released_by_user_id":None,"unlock_requested_at":None,"unlock_request_reason":None,"contact_consent_revoked_at":None});groups.append(group)
    snapshots=[]
    for candidate,profile,group in zip(candidates[1:],profiles[1:],groups[1:]):
        snapshot=_put(db,InternshipApplicationMaterialSnapshot,tenant_id,{"volunteer_group_id":group.id,"submission_version":1},{"student_id":candidate.student_id,"campaign_id":campaign.id,"batch_id":batch.id,"profile_version":profile.profile_version,"profile_snapshot_json":{"headline":profile.headline,"skills":profile.skill_tags_json},"school_fact_snapshot_json":{"studentId":str(candidate.student_id),"majorRequirement":candidate_major.major_name,"eligibility":"QUALIFIED"},"attachment_file_ids_json":[evidence.id],"material_policy_snapshot_json":campaign.application_material_policy_json,"consent_version":"2026.2","consent_at":REFERENCE_NOW-timedelta(days=1),"contact_sharing_policy":{"enterpriseContact":"maskedUntilInterview"},"snapshot_hash":f"007-int-material-{candidate.id:08d}","generated_profile_pdf_file_id":evidence.id});group.current_material_snapshot_id=snapshot.id;snapshots.append(snapshot)
    application_states=(("DRAFT",None),("PENDING_REVIEW",REFERENCE_NOW-timedelta(hours=4)),("APPROVED",REFERENCE_NOW-timedelta(days=1)),("APPROVED",REFERENCE_NOW-timedelta(days=1)))
    applications=[]
    for candidate,group,snapshot,(app_status,submitted_at) in zip(candidates,groups,[None,*snapshots],application_states):
        app=_put(db,InternshipApplication,tenant_id,{"campaign_record_id":candidate.id,"campaign_id":campaign.id,"volunteer_no":1},{"student_id":candidate.student_id,"batch_id":batch.id,"application_type":"CAMPAIGN_POSITION","position_id":campaign_position.id,"company_name":recruitment_company.name,"position_name":campaign_position.title,"work_address":campaign_position.work_address,"contact_name":contact.name,"contact_phone":None,"evidence_file_id":file_id,"application_note":"学生根据第二轮补录岗位要求提交真实实习志愿。","application_statement":"已完成相关课程与校内项目实训，愿意接受企业面试和学校审核。","material_snapshot_id":snapshot.id if snapshot else None,"status":app_status,"submitted_at":submitted_at,"reviewed_by_name":advisor.real_name if app_status=="APPROVED" else None,"reviewed_at":REFERENCE_NOW-timedelta(hours=18) if app_status=="APPROVED" else None,"review_comment":"资格、专业要求和材料均符合岗位条件。" if app_status=="APPROVED" else None});app.company_name=recruitment_company.name;app.position_name=campaign_position.title;app.position_id=campaign_position.id;applications.append(app)
    rejected=_put(db,InternshipEnterpriseApplicationDecision,tenant_id,{"application_id":applications[2].id,"material_snapshot_id":snapshots[1].id},{"volunteer_group_id":groups[2].id,"campaign_id":campaign.id,"batch_id":batch.id,"company_id":recruitment_company.id,"position_id":campaign_position.id,"submission_version":1,"decision_status":"REJECTED","effect_status":"CONSUMED","valid_until":None,"superseded_reason":None,"interview_at":None,"interview_note":None,"decision_reason":"本轮岗位服务语言与学生提交的项目经验匹配度不足，建议补充项目成果后参加下一轮。","decided_by_member_id":member.id,"decided_by_user_id":enterprise_user.id,"decided_at":REFERENCE_NOW-timedelta(days=1)});rejected.company_id=recruitment_company.id;rejected.position_id=campaign_position.id;rejected.decided_by_member_id=member.id;rejected.decided_by_user_id=enterprise_user.id
    accepted=_put(db,InternshipEnterpriseApplicationDecision,tenant_id,{"application_id":applications[3].id,"material_snapshot_id":snapshots[2].id},{"volunteer_group_id":groups[3].id,"campaign_id":campaign.id,"batch_id":batch.id,"company_id":recruitment_company.id,"position_id":campaign_position.id,"submission_version":1,"decision_status":"ACCEPT_INTENT","effect_status":"ACTIVE","valid_until":REFERENCE_NOW+timedelta(hours=40),"superseded_reason":None,"interview_at":REFERENCE_NOW-timedelta(hours=8),"interview_note":"企业导师已完成线上交流，建议学校在 SLA 内确认。","decision_reason":"学生基础与岗位培养方向匹配，给出拟录用意向。","decided_by_member_id":member.id,"decided_by_user_id":enterprise_user.id,"decided_at":REFERENCE_NOW-timedelta(hours=7)});accepted.company_id=recruitment_company.id;accepted.position_id=campaign_position.id;accepted.decided_by_member_id=member.id;accepted.decided_by_user_id=enterprise_user.id
    groups[3].locked_application_id=applications[3].id;groups[3].locked_by_decision_id=accepted.id
    _put(db,InternshipScoreConfig,tenant_id,{"active_scope_key":f"BATCH:{batch.id}"},{"batch_id":batch.id,"checkin_weight":20,"weekly_weight":20,"monthly_weight":10,"enterprise_weight":30,"school_weight":20,"pass_line":60.0,"status":"ACTIVE"})
    score_config=_one(db,InternshipScoreConfig,tenant_id,active_scope_key=f"BATCH:{batch.id}")
    _put(db,InternshipFinalScore,tenant_id,{"internship_id":rec2.id},{"student_id":rec2.student_id,"batch_id":batch.id,"score_config_id":score_config.id,"score_config_version":score_config.version,"checkin_score":None,"weekly_score":None,"monthly_score":None,"enterprise_score":None,"school_score":None,"w_checkin":20,"w_weekly":20,"w_monthly":10,"w_enterprise":30,"w_school":20,"total_score":None,"pass_line":60.0,"is_pass":False,"incomplete":True,"incomplete_reason":"当前批次尚在进行中，月度过程材料与期末企业评价未齐。","status":"PENDING_CALC","reviewed_by_name":None,"reviewed_at":None,"published_by_name":None,"published_at":None,"remark":"仅作为进行中批次的核算待办，不代表最终成绩。"})
    _put(db,InternshipPlacementSnapshot,tenant_id,{"record_id":rec6.id,"placement_seq":1},{"snapshot_version":1,"application_id":None,"enterprise_decision_id":None,"campaign_id":None,"batch_id":batch.id,"company_id":company.id,"position_id":position.id,"company_name":company.name,"company_credit_code":company.credit_code,"position_title":position.title,"position_category":position.category,"work_location":position.work_location,"work_address":position.work_address,"work_content":position.work_content,"major_requirement":position.major_requirement,"grade_requirement":position.grade_requirement,"salary_range":position.salary_range,"subsidy":position.subsidy,"remuneration_type":position.remuneration_type,"remuneration_amount":position.remuneration_amount,"remuneration_cycle":position.remuneration_cycle,"daily_hours":position.daily_hours,"weekly_hours":position.weekly_hours,"shift_type":position.shift_type,"night_shift":position.night_shift,"overtime_allowed":position.overtime_allowed,"rest_days":position.rest_days,"rest_days_per_week":position.rest_days_per_week,"accommodation_provided":position.accommodation_provided,"meal_provided":position.meal_provided,"hazardous_flag":position.hazardous_flag,"special_equipment":position.special_equipment,"prohibited_reason":position.prohibited_reason,"enterprise_mentor_name":rec6.enterprise_mentor_name,"rights_status":position.rights_status,"rights_rule_version":position.rights_rule_version,"rights_checked_at":position.rights_checked_at,"position_version":position.version,"position_updated_at":position.updated_at,"snapshot_json":{"source":"legacy_school_position_assignment","recordId":str(rec6.id),"companyId":str(company.id),"positionId":str(position.id)},"snapshot_hash":f"007-placement-{rec6.id:08d}-v1","snapshot_sha256":f"007placement{rec6.id:052d}"[-64:],"placement_at":REFERENCE_NOW-timedelta(days=50),"captured_at":REFERENCE_NOW-timedelta(days=49),"captured_by_user_id":advisor.id})
    template=_put(db, InternshipAgreementTemplate, tenant_id, {"name":f"{MARKER}-三方实习协议"}, {"category":"TRIPARTITE", "template_version":"v1.0", "scope_college_ids":None, "scope_major_ids":None, "scope_grades":["2024"], "scope_batch_ids":[batch.id], "body":"{studentName} 与 {companyName} 的岗位实习三方协议。", "variables":[{"key":"studentName"},{"key":"companyName"},{"key":"positionName"}], "is_default":True, "status":"ENABLED", "remark":"007 当前实习批次协议模板。", "enabled_at":REFERENCE_NOW-timedelta(days=70)})
    compliance=_put(db, InternshipComplianceTemplate, tenant_id, {"template_code":f"{MARKER}-COMPLIANCE", "template_version":1}, {"template_name":"2026 秋季实习合规核验规则", "status":"ACTIVE", "config":{"agreement":True,"insurance":True,"safety":True}, "effective_at":REFERENCE_NOW-timedelta(days=80), "approved_by_name":admin.real_name, "approved_at":REFERENCE_NOW-timedelta(days=80), "change_reason":"批次启用前合规审核。", "remark":"007 实习演示规则。"})
    if batch.compliance_template_id is None:
        batch.compliance_template_id=compliance.id; batch.compliance_template_version=1; db.flush()
    plan=_put(db, InternshipBatchPlan, tenant_id, {"batch_id":batch.id}, {"title":"2026 秋季岗位实习计划书", "objectives":"岗位胜任、职业素养与安全生产教育。", "content":"按周打卡、周报、指导和企业评价形成过程闭环。", "tasks_json":[{"sort":1,"name":"完成岗前安全教育"},{"sort":2,"name":"提交首月过程报告"}], "status":"PUBLISHED", "published_at":REFERENCE_NOW-timedelta(days=60), "published_by_name":admin.real_name})
    for idx, (r,status) in enumerate(((rec,"ACKNOWLEDGED"),(rec2,"PENDING"))):
        _put(db, InternshipPlanAck, tenant_id, {"internship_id":r.id,"plan_id":plan.id}, {"student_id":r.student_id,"status":status,"acknowledged_at":REFERENCE_NOW-timedelta(days=58) if status=="ACKNOWLEDGED" else None})
    safety=_put(db, InternshipSafetyCourse, tenant_id, {"batch_id":batch.id,"title":"2026 秋季岗位实习安全教育"}, {"course_version":"v1.0","required_minutes":90,"passing_score":80,"max_attempts":3,"require_commitment":True,"content_snapshot":"岗位安全、劳动权益和应急处置学习材料。","material_file_ids":[file_id],"status":"ACTIVE","effective_at":REFERENCE_NOW-timedelta(days=70),"rule_version":"2026.1"})
    _put(db, InternshipSafetyCompletion, tenant_id, {"internship_id":rec.id,"course_id":safety.id}, {"batch_id":batch.id,"student_id":rec.student_id,"course_version":"v1.0","course_content_snapshot":safety.content_snapshot,"course_content_hash":"007intsafetycontent","started_at":REFERENCE_NOW-timedelta(days=59),"completed_at":REFERENCE_NOW-timedelta(days=59),"studied_minutes":95,"submitted_at":REFERENCE_NOW-timedelta(days=59),"answer_snapshot":{"score":92},"attempt_count":1,"score":92,"passed":True,"commitment_confirmed":True,"commitment_at":REFERENCE_NOW-timedelta(days=59),"commitment_content_hash":"007intcommitment","evidence_file_id":file_id,"review_mode":"ONLINE_QUIZ","reviewed_by_name":advisor.real_name,"reviewed_by_user_id":str(advisor.id),"reviewed_at":REFERENCE_NOW-timedelta(days=59),"status":"PASSED","rule_version":"2026.1"})
    for r, status in ((rec,"EFFECTIVE"),(rec2,"PENDING_STUDENT"),(rec3,"REJECTED")):
        _put(db, InternshipAgreement, tenant_id, {"internship_id":r.id}, {"student_id":r.student_id,"template_id":template.id,"batch_id":batch.id,"enterprise_name":r.enterprise_name,"position_name":r.position_name,"student_confirm_status":"CONFIRMED" if status=="EFFECTIVE" else "PENDING","student_confirm_at":REFERENCE_NOW-timedelta(days=55) if status=="EFFECTIVE" else None,"enterprise_confirm_status":"CONFIRMED" if status=="EFFECTIVE" else "PENDING","enterprise_confirm_at":REFERENCE_NOW-timedelta(days=54) if status=="EFFECTIVE" else None,"enterprise_confirm_by":"企业人事专员" if status=="EFFECTIVE" else None,"school_confirm_status":"CONFIRMED" if status=="EFFECTIVE" else "PENDING","school_confirm_at":REFERENCE_NOW-timedelta(days=53) if status=="EFFECTIVE" else None,"school_confirm_by":admin.real_name if status=="EFFECTIVE" else None,"status":status,"reject_reason":"企业岗位职责与专业培养要求不匹配，请修改后重交。" if status=="REJECTED" else None,"file_id":file_id,"source_type":"FILE_EVIDENCE","recorded_by_user_id":str(admin.id),"recorded_by_name":admin.real_name,"recorded_at":REFERENCE_NOW-timedelta(days=56),"source_file_id":file_id,"source_remark":"纸质三方协议扫描件经学校核验。","esign_status":"NONE","rendered_body":"基于已确认的学生、企业与岗位生成的协议正文快照。","remark":"007 实习协议状态链。"})
    _put(db, InternshipInsurance, tenant_id, {"internship_id":rec.id}, {"student_id":rec.student_id,"policy_no":"YX-INT-2026-0001","insurer_name":"职业院校学生实习责任险承保机构","coverage_type":"实习责任与意外伤害","effective_date":"2026-07-20","expiry_date":"2027-01-15","file_id":file_id,"status":"VERIFIED","submitted_at":REFERENCE_NOW-timedelta(days=55),"verify_comment":"保障期限覆盖实习批次。","verified_by_name":admin.real_name,"verified_at":REFERENCE_NOW-timedelta(days=54)})
    for r, status in ((rec,"APPROVED"),(rec2,"RETURNED"),(rec3,"PENDING_REVIEW")):
        _put(db, InternshipProcessReport, tenant_id, {"internship_id":r.id,"report_type":"MONTHLY","period_key":"2026-08"}, {"content":"完成岗位业务学习、任务交付与导师沟通，形成当月过程总结。","word_count":180,"submitted_at":REFERENCE_NOW-timedelta(days=2),"status":status,"review_action":status,"review_comment":"请补充量化成果和企业导师反馈。" if status=="RETURNED" else "过程目标达成。" if status=="APPROVED" else None,"reviewed_by_name":advisor.real_name if status!="PENDING_REVIEW" else None,"reviewed_at":REFERENCE_NOW-timedelta(days=1) if status!="PENDING_REVIEW" else None})
    _put(db, InternshipPlanTaskProgress, tenant_id, {"internship_id":rec.id,"plan_id":plan.id,"task_sort_order":1}, {"student_id":rec.student_id,"task_name":"完成岗前安全教育","status":"APPROVED","student_note":"已完成学习并提交承诺。","evidence_file_id":file_id,"submitted_at":REFERENCE_NOW-timedelta(days=59),"reviewed_by_name":advisor.real_name,"reviewed_at":REFERENCE_NOW-timedelta(days=58),"review_comment":"符合要求。"})
    _put(db, InternshipPlanTaskProgress, tenant_id, {"internship_id":rec2.id,"plan_id":plan.id,"task_sort_order":2}, {"student_id":rec2.student_id,"task_name":"提交首月过程报告","status":"RETURNED","student_note":"已提交初稿。","evidence_file_id":file_id,"submitted_at":REFERENCE_NOW-timedelta(days=2),"reviewed_by_name":advisor.real_name,"reviewed_at":REFERENCE_NOW-timedelta(days=1),"review_comment":"请补充岗位产出数据后重交。"})
    _put(db, InternshipGuidance, tenant_id, {"internship_id":rec.id,"student_id":rec.student_id,"topic":"首月岗位适应指导"}, {"advisor_name":advisor.real_name,"method":"ONLINE","content":"核对岗位任务、周报质量和安全打卡情况。","problem_type":"ADAPTATION","suggestion":"每周形成任务清单并与企业导师同步。","next_follow_date":"2026-09-04","to_risk":False,"notify_counselor":False,"file_id":file_id,"status":"NORMAL"})
    visit=_put(db, InternshipVisit, tenant_id, {"internship_id":rec.id,"student_id":rec.student_id}, {"advisor_name":advisor.real_name,"enterprise_name":rec.enterprise_name,"visit_at":REFERENCE_NOW-timedelta(days=4),"method":"ONLINE","enterprise_feedback":"学生到岗稳定，能完成基础岗位任务。","student_feedback":"希望增加代码评审机会。","safety_issue":None,"rectify_require":None,"rectify_deadline":None,"rectify_status":"NONE","monthly_report":"首轮巡访未发现安全隐患。","file_id":file_id})
    _put(db, InternshipVisitPlan, tenant_id, {"batch_id":batch.id,"enterprise_id":company.id,"plan_date":"2026-09-05"}, {"college_id":None,"enterprise_name":company.name,"owner_name":advisor.real_name,"collaborators":admin.real_name,"student_scope":str(rec.student_id),"time_window":"09:00-11:00","method":"ONSITE","location":company.address,"objective":"核验学生岗位、劳动权益和安全条件。","status":"PUBLISHED","plan_type":"VISIT","remind_at":REFERENCE_NOW+timedelta(days=6),"visit_id":visit.id,"completed_at":None,"cancel_reason":None})
    _put(db, InternshipLeave, tenant_id, {"internship_id":rec2.id,"student_id":rec2.student_id,"start_date":"2026-08-29"}, {"end_date":"2026-08-30","reason":"家庭紧急事务，已与企业导师沟通。","status":"PENDING","apply_by_name":"实习学生","review_by_name":None,"review_at":None,"review_comment":None,"file_id":file_id})
    _put(db, InternshipMakeup, tenant_id, {"internship_id":rec3.id,"student_id":rec3.student_id,"checkin_date":"2026-08-25"}, {"makeup_type":"MISSING","reason":"企业园区网络故障导致当日未成功打卡。","status":"REJECTED","apply_by_name":"实习学生","review_by_name":advisor.real_name,"review_at":REFERENCE_NOW-timedelta(days=1),"review_comment":"缺少企业网络故障说明，请补充后重新申请。"})
    _put(db, InternshipChangeRequest, tenant_id, {"internship_id":rec4.id,"student_id":rec4.student_id,"change_type":"POSITION_CHANGE"}, {"reason":"现岗位实际工作内容与专业实践方向不匹配，申请调整。","target_enterprise_id":rec4.enterprise_id,"target_position_id":rec4.position_id,"target_enterprise_name":rec4.enterprise_name,"target_position_name":rec4.position_name,"record_version_snapshot":rec4.version,"status":"PENDING","review_comment":None,"reviewed_by_name":None,"reviewed_at":None})
    _put(db, InternshipCommunicationLog, tenant_id, {"enterprise_id":company.id,"internship_id":rec.id,"communication_type":"PHONE"}, {"student_id":rec.student_id,"position_id":position.id,"direction":"SCHOOL","contact_id":None,"contact_name_snapshot":"企业人事专员","advisor_name":advisor.real_name,"occurred_at":REFERENCE_NOW-timedelta(days=3),"summary":"核对学生到岗、保险和协议确认状态。","result":"企业确认学生状态正常，建议持续跟进岗位能力。","follow_up_required":True,"follow_up_due_at":REFERENCE_NOW+timedelta(days=7),"follow_up_owner_id":advisor.id,"follow_up_done":False,"file_id":file_id,"status":"NORMAL"})
    _put(db, InternshipComplaint, tenant_id, {"complaint_no":f"{MARKER}-COMPLAINT"}, {"source":"STUDENT","target_type":"POSITION","enterprise_id":company.id,"position_id":position.id,"student_id":rec5.student_id,"internship_id":rec5.id,"batch_id":batch.id,"category":"WORK_CONTENT","severity":"MEDIUM","content":"岗位任务说明与宣讲材料存在差异，申请学校核实。","evidence_file_id":file_id,"confidential_level":"NORMAL","status":"ACCEPTED","accepted_by_name":admin.real_name,"owner_name":advisor.real_name,"accept_deadline":"2026-08-29","resolve_deadline":"2026-09-04","conclusion":"已与企业沟通，将补充任务说明并持续跟进。","followup_result":None,"risk_id":None})
    _put(db, InternshipIntention, tenant_id, {"record_id":rec6.id,"student_id":rec6.student_id}, {"batch_id":batch.id,"preferred_city":position.work_location,"preferred_industry":company.industry,"preferred_company_id":company.id,"preferred_position_id":position.id,"intention_note":"希望在当前专业方向岗位持续实习。","status":"SUBMITTED"})
    _put(db, InternshipApplication, tenant_id, {"record_id":rec6.id,"volunteer_no":1}, {"student_id":rec6.student_id,"batch_id":batch.id,"campaign_id":None,"application_type":"SCHOOL_POSITION","position_id":position.id,"company_name":company.name,"position_name":position.title,"work_address":position.work_address,"contact_name":"企业人事专员","contact_phone":None,"evidence_file_id":file_id,"application_note":"提交岗位申请材料。","application_statement":"我的专业课程和实训经历与该岗位要求匹配。","status":"APPROVED","submitted_at":REFERENCE_NOW-timedelta(days=50),"reviewed_by_name":advisor.real_name,"reviewed_at":REFERENCE_NOW-timedelta(days=49),"review_comment":"符合岗位资格。"})
    app=_one(db, InternshipApplication, tenant_id, record_id=rec6.id, volunteer_no=1)
    _put(db, InternshipMatch, tenant_id, {"record_id":rec6.id,"position_id":position.id}, {"student_id":rec6.student_id,"company_id":company.id,"match_type":"MANUAL","score":92,"major_hit":True,"enterprise_hit":True,"conflict_flag":False,"conflict_reason":None,"status":"CONFIRMED","confirmed_by":advisor.real_name,"confirmed_at":REFERENCE_NOW-timedelta(days=49),"remark":"由已审核申请确认匹配。"})
    _put(db, InternshipEnterpriseInspection, tenant_id, {"company_id":company.id,"batch_id":batch.id,"inspection_type":"ONSITE"}, {"inspection_required":True,"inspection_date":REFERENCE_NOW-timedelta(days=75),"inspectors":admin.real_name,"workplace_address":company.address,"safety_condition":"消防与劳动防护符合要求。","accommodation_condition":"企业提供住宿指引。","mentor_condition":"企业导师到岗。","remuneration_condition":"岗位报酬与协议一致。","conclusion":"准入条件满足，批准进入实习岗位库。","risk_items":None,"rectification_items":None,"file_ids":[file_id],"valid_until":REFERENCE_NOW+timedelta(days=180),"status":"APPROVED","review_comment":"企业现场考察通过。","reviewed_by_name":admin.real_name,"reviewed_at":REFERENCE_NOW-timedelta(days=74),"rule_version":"2026.1"})
    _put(db, InternshipConsent, tenant_id, {"internship_id":rec.id,"student_id":rec.student_id,"consent_type":"STUDENT"}, {"batch_id":batch.id,"applicable":True,"participant_name":"实习学生","participant_relation":"SELF","identity_masked":"student","contact_masked":"已脱敏","content_version":"2026.1","content_snapshot":"本人已阅读实习安全、权益和岗位信息。","content_hash":"007intconsent","delivery_channel":"IN_APP","message_id":None,"delivered_at":REFERENCE_NOW-timedelta(days=60),"viewed_at":REFERENCE_NOW-timedelta(days=59),"confirmed_at":REFERENCE_NOW-timedelta(days=59),"confirmation_method":"PORTAL","confirmed_by_user_id":None,"confirmed_student_id":rec.student_id,"file_id":file_id,"status":"VALID","rule_version":"2026.1"})
    _put(db, InternshipEmergencyPlan, tenant_id, {"company_id":company.id,"batch_id":batch.id,"plan_name":f"{MARKER}-企业应急预案"}, {"responsible_person":"企业安全负责人","emergency_contact":"企业应急值班电话（档案留存）","backup_contact":"学校实习管理办公室","hospital_or_support":"属地医院及学校应急联系人","response_steps":"报告、现场处置、学生监护、学校联动、复盘整改。","valid_from":REFERENCE_NOW-timedelta(days=80),"valid_until":REFERENCE_NOW+timedelta(days=100),"file_ids":[file_id],"status":"APPROVED","reviewed_by_name":admin.real_name,"reviewed_at":REFERENCE_NOW-timedelta(days=79),"rule_version":"2026.1"})
    _put(db, InternshipRemunerationRecord, tenant_id, {"internship_id":rec.id,"batch_id":batch.id}, {"position_id":position.id,"agreed_amount":position.remuneration_amount,"agreed_cycle":"MONTHLY","actual_paid_amount":3200,"paid_at":REFERENCE_NOW-timedelta(days=5),"proof_file_id":file_id,"status":"PAID","discrepancy":None,"student_confirmed_at":REFERENCE_NOW-timedelta(days=4),"rule_version":"2026.1"})
    _put(db, InternshipSpecialFiling, tenant_id, {"internship_id":rec5.id,"filing_type":"CROSS_CITY"}, {"batch_id":batch.id,"student_id":rec5.student_id,"applicable":True,"trigger_reason":"实习岗位跨市安排，需办理专项备案。","destination_region":company.city,"work_address":position.work_address,"risk_description":"跨市通勤与住宿安全需持续关注。","student_application":"本人知悉跨市实习安排并提交备案申请。","guardian_consent_required":False,"college_review_by":advisor.real_name,"college_review_at":REFERENCE_NOW-timedelta(days=50),"college_comment":"学院审核通过。","school_review_by":admin.real_name,"school_review_at":REFERENCE_NOW-timedelta(days=49),"school_comment":"学校备案通过。","regulator_filing_no":f"{MARKER}-FILING","status":"APPROVED","requested_by_name":"实习学生","requested_by_user_id":None,"reviewed_by_name":advisor.real_name,"reviewed_at":REFERENCE_NOW-timedelta(days=50),"approved_by_name":admin.real_name,"approved_at":REFERENCE_NOW-timedelta(days=49),"valid_until":batch.end_date,"file_ids":[file_id],"rule_version":"2026.1"})
    _put(db, InternshipComplianceExemption, tenant_id, {"internship_id":rec4.id,"check_code":"SPECIAL_TRANSPORT"}, {"batch_id":batch.id,"reason":"企业夜间班车安排处于核验中，申请短期交通证明补交豁免。","evidence_file_ids":[file_id],"valid_from":REFERENCE_NOW-timedelta(days=1),"valid_until":REFERENCE_NOW+timedelta(days=7),"status":"PENDING_REVIEW","requested_by_name":advisor.real_name,"requested_by_user_id":str(advisor.id),"reviewed_by_name":None,"reviewed_at":None,"rule_version":"2026.1"})
    _put(db, InternshipEvidencePackage, tenant_id, {"package_type":"STUDENT","target_id":rec.id,"package_version":1}, {"batch_id":batch.id,"package_file_id":file_id,"package_sha256":"007intevidencepackage","package_size_bytes":386,"manifest_json":{"agreement":True,"insurance":True,"safety":True},"included_items":["agreement","insurance","safety"],"missing_items":[],"rule_version":"2026.1","metric_version":"2026.1","generated_by_name":admin.real_name,"generated_at":REFERENCE_NOW-timedelta(days=1),"status":"READY","row_count":8,"file_count":1})
    _put(db, InternshipIncident, tenant_id, {"incident_no":f"{MARKER}-INCIDENT"}, {"batch_id":batch.id,"internship_id":rec4.id,"company_id":company.id,"student_id":rec4.student_id,"risk_id":None,"incident_type":"OTHER","severity":"LOW","occurred_at":REFERENCE_NOW-timedelta(days=3),"location":position.work_address,"summary":"学生在岗位适应期出现轻微沟通误解，未造成伤害。","injury_flag":False,"affected_persons":"学生本人","reported_by_name":advisor.real_name,"reported_at":REFERENCE_NOW-timedelta(days=3),"emergency_action":"教师与企业导师完成当日沟通和岗位任务澄清。","guardian_notified_at":None,"school_notified_at":REFERENCE_NOW-timedelta(days=3),"enterprise_notified_at":REFERENCE_NOW-timedelta(days=3),"status":"CLOSED","investigation_conclusion":"属岗位交接信息不充分，不构成安全事故。","responsibility_conclusion":"企业补充交接说明，学校持续跟进。","rectification_plan":"一周内复盘岗位交接流程。","rectification_deadline":REFERENCE_NOW+timedelta(days=4),"closed_at":REFERENCE_NOW-timedelta(days=1),"closed_by_name":admin.real_name,"file_ids":[file_id],"idempotency_key":f"{MARKER}-INCIDENT","rule_version":"2026.1"})
    # 历史暑期行业见习链与当前 2026 秋季全岗实习严格分开：同一批 2024 级学生在 2025
    # 年有真实可归档的短期见习记录，因此终期评价、成绩和归档都落在已结束批次，而非伪造到
    # 当前 RUNNING 批次。
    historical_batch=_put(db,InternshipBatch,tenant_id,{"batch_no":"INT-2025-SUMMER-HIST"},{"batch_name":"2025 年暑期行业见习（历史归档样本）","academic_year":"2024-2025","term":"暑期","start_date":datetime(2025,7,7),"end_date":datetime(2025,8,29),"signup_start_date":datetime(2025,6,10),"signup_end_date":datetime(2025,6,25),"planned_count":3,"status":"ARCHIVED","stage_config":[{"code":"ONBOARD","name":"到岗","startDate":"2025-07-07","endDate":"2025-07-11"},{"code":"ASSESS","name":"总结评价","startDate":"2025-08-18","endDate":"2025-08-29"}],"rules_config":{"checkin":{"required":True},"evaluation":{"required":True}},"rules_version":1,"compliance_template_id":None,"compliance_template_version":None,"previous_status":"CLOSED","last_transition_at":datetime(2025,9,5),"last_transition_by":admin.real_name,"transition_reason":"材料、评价和成绩核验完成后归档。","archive_status":"ARCHIVED","archived_at":datetime(2025,9,5),"archived_by":admin.real_name,"archive_batch_no":"INT-ARCH-2025-01","remark":"用于展示已结束实习的评价、成绩和归档证据；不参与当前批次容量统计。"})
    advisor_loads=dict(db.execute(select(InternshipRecord.advisor_user_id,func.count()).where(InternshipRecord.tenant_id==tenant_id,InternshipRecord.is_deleted.is_(False),InternshipRecord.advisor_user_id.is_not(None)).group_by(InternshipRecord.advisor_user_id)).all())
    historical_advisors=sorted((user for user in db.scalars(select(User).where(User.tenant_id==tenant_id,User.login_name.like("sbx_im%"),User.is_deleted.is_(False))).all() if user.id in advisor_loads),key=lambda user:(advisor_loads.get(user.id,0),user.id))[:3]
    if len(historical_advisors)<3: raise RuntimeError("historical internship seed requires three existing internship mentors")
    historical_position=_put(db,InternshipPosition,tenant_id,{"company_id":company.id,"batch_id":historical_batch.id,"title":position.title},{"company_name":company.name,"campaign_id":None,"source_type":"SCHOOL","category":position.category,"major_requirement":position.major_requirement,"grade_requirement":"2024","work_location":position.work_location,"geofence_lat":position.geofence_lat,"geofence_lng":position.geofence_lng,"geofence_radius_m":position.geofence_radius_m,"salary_range":position.salary_range,"subsidy":position.subsidy,"headcount":3,"allocated_count":0,"mentor_contact_id":None,"mentor_name":"企业见习导师","risk_flag":False,"risk_note":None,"daily_hours":8,"weekly_hours":40,"shift_type":"DAY","night_shift":False,"overtime_allowed":False,"rest_days":"双休","rest_days_per_week":2,"remuneration_type":"MONTHLY","remuneration_amount":3000,"remuneration_cycle":"MONTHLY","accommodation_provided":False,"meal_provided":True,"hazardous_flag":False,"special_equipment":None,"work_content":"2025 年暑期行业见习岗位，完成基础任务、周记与企业鉴定。","work_address":company.address,"prohibited_reason":None,"rights_status":"PASSED","rights_checked_at":datetime(2025,6,20),"rights_rule_version":"2025.1","status":"ARCHIVED","remark":"历史批次岗位快照。","publish_at":datetime(2025,6,25),"archived_at":datetime(2025,9,5),"archived_by":admin.real_name})
    historical_config=_put(db,InternshipScoreConfig,tenant_id,{"batch_id":historical_batch.id},{"active_scope_key":None,"checkin_weight":20,"weekly_weight":20,"monthly_weight":10,"enterprise_weight":30,"school_weight":20,"pass_line":60.0,"status":"RETIRED"})
    for offset,current_record in enumerate((rec,rec2,rec3),1):
        historical_advisor=historical_advisors[offset-1]
        student_profile=db.get(StudentProfile,current_record.student_id)
        hist_record=_put(db,InternshipRecord,tenant_id,{"student_id":current_record.student_id,"batch_id":historical_batch.id},{"enterprise_name":company.name,"position_name":historical_position.title,"advisor_name":historical_advisor.real_name,"enterprise_mentor_name":"企业见习导师","advisor_user_id":historical_advisor.id,"enterprise_id":company.id,"position_id":historical_position.id,"mentor_contact_id":None,"eligibility_status":"QUALIFIED","destination_type":"SELF_ARRANGED","status":"ARCHIVED","risk_level":"NONE","intern_start_date":datetime(2025,7,7),"intern_end_date":datetime(2025,8,29),"insurance_info":"历史见习责任险已核验","agreement_info":"历史见习协议已归档","remark":"2025 暑期行业见习已完成并进入历史归档。"});hist_record.advisor_name=historical_advisor.real_name;hist_record.advisor_user_id=historical_advisor.id
        _put(db,InternshipBatchParticipant,tenant_id,{"batch_id":historical_batch.id,"student_id":hist_record.student_id},{"source":"MANUAL","snapshot_student_no":student_profile.student_no,"snapshot_name":student_profile.real_name,"snapshot_class_name":None,"snapshot_college_name":None,"internship_id":hist_record.id,"status":"ACTIVE","remove_reason":None})
        enterprise_eval=_put(db,InternshipEnterpriseEval,tenant_id,{"internship_id":hist_record.id,"student_id":hist_record.student_id},{"batch_id":historical_batch.id,"position_name":historical_position.title,"mentor_name":"企业见习导师","attendance_score":88+offset,"skill_score":86+offset,"attitude_score":90,"collaboration_score":89,"safety_score":92,"overall_comment":"能按要求完成见习任务，沟通主动，遵守企业安全规范。","recommend_hire":offset!=2,"source":"SCHOOL_RECORDED","source_type":"FILE_EVIDENCE","recorded_by_user_id":str(admin.id),"recorded_by_name":admin.real_name,"recorded_at":datetime(2025,8,28),"source_file_id":file_id,"enterprise_contact_id":None,"source_remark":"企业签署的历史见习鉴定表由学校核验录入。","submit_status":"SUBMITTED","school_review_status":"APPROVED","school_review_comment":"企业签章、岗位和见习期限核验一致。","reviewed_by_name":historical_advisor.real_name,"reviewed_at":datetime(2025,8,30),"file_id":file_id});enterprise_eval.reviewed_by_name=historical_advisor.real_name
        student_eval=_put(db,InternshipStudentEval,tenant_id,{"internship_id":hist_record.id,"student_id":hist_record.student_id},{"batch_id":historical_batch.id,"self_summary":"完成岗位观察、基础业务协作和每周见习记录。","self_harvest":"理解职业规范、服务流程与团队协作要求。","self_problem":"需要继续提升现场沟通和业务表达能力。","advisor_opinion":"过程材料完整，建议将见习收获转化为后续专业学习目标。","mentor_opinion":"工作态度认真，具备继续培养基础。","submit_status":"SUBMITTED","submitted_at":datetime(2025,8,28),"school_review_status":"APPROVED","school_review_comment":"学生总结与企业鉴定相互印证。","reviewed_by_name":historical_advisor.real_name,"reviewed_at":datetime(2025,8,30),"file_id":file_id,"enterprise_rating":4,"position_rating":4,"enterprise_feedback":"导师安排和安全教育到位。","position_feedback":"岗位任务与见习目标匹配。"});student_eval.reviewed_by_name=historical_advisor.real_name
        scores={"checkin_score":90,"weekly_score":88,"monthly_score":87,"enterprise_score":(enterprise_eval.attendance_score+enterprise_eval.skill_score+enterprise_eval.attitude_score+enterprise_eval.collaboration_score+enterprise_eval.safety_score)/5,"school_score":89};total=round(scores["checkin_score"]*.2+scores["weekly_score"]*.2+scores["monthly_score"]*.1+scores["enterprise_score"]*.3+scores["school_score"]*.2,2)
        _put(db,InternshipFinalScore,tenant_id,{"internship_id":hist_record.id},{"student_id":hist_record.student_id,"batch_id":historical_batch.id,"score_config_id":historical_config.id,"score_config_version":historical_config.version,"w_checkin":20,"w_weekly":20,"w_monthly":10,"w_enterprise":30,"w_school":20,"total_score":total,"pass_line":60.0,"is_pass":True,"incomplete":False,"incomplete_reason":None,"status":"ARCHIVED","reviewed_by_name":advisor.real_name,"reviewed_at":datetime(2025,8,30),"published_by_name":admin.real_name,"published_at":datetime(2025,9,1),"remark":"历史暑期见习成绩已发布并随批次归档。",**scores})
        _put(db,InternshipArchive,tenant_id,{"internship_id":hist_record.id},{"student_id":hist_record.student_id,"batch_id":historical_batch.id,"completeness":100,"missing_items":None,"material_snapshot":{"agreement":True,"insurance":True,"checkin":True,"weeklyReport":True,"enterpriseEvaluation":True,"studentEvaluation":True,"finalScore":total},"snapshot_version":1,"status":"ARCHIVED","package_file_id":file_id,"previous_record_status":"ASSESSING","package_invalidated_at":None,"revoked_by_name":None,"revoked_at":None,"revoke_reason":None,"force_reason":None,"force_evidence_file_ids":None,"force_bypassed_items":None,"force_rule_version":None,"force_approved_role":None,"force_approved_by":None})
        db.add(InternshipAuditTrail(tenant_id=tenant_id,target_id=hist_record.id,target_type="RECORD",action="ARCHIVE_COMPLETE",operator_name=admin.real_name,detail_json={"batch":"INT-2025-SUMMER-HIST","score":total,"evidenceFileId":file_id},occurred_at=datetime(2025,9,5)))
    db.commit(); return validate_internship_operational_coverage(db, tenant_id)

def validate_internship_operational_coverage(db, tenant_id: int) -> dict:
    from app.models.internship import (InternshipAgreement, InternshipArchive, InternshipBatch,
                                       InternshipBatchPlan, InternshipBatchScopeRule, InternshipFinalScore)
    from app.models.internship_compliance import InternshipComplianceTemplate
    from app.models.internship_enterprise_portal import InternshipRecruitmentCampaign
    current_batch=_one(db,InternshipBatch,tenant_id,batch_no="INT-2024-2026FALL")
    historical_batch=_one(db,InternshipBatch,tenant_id,batch_no="INT-2025-SUMMER-HIST")
    result={"plan":bool(current_batch and _one(db,InternshipBatchPlan,tenant_id,batch_id=current_batch.id)),"scopeRule":bool(current_batch and _one(db,InternshipBatchScopeRule,tenant_id,batch_id=current_batch.id)),"agreement":bool(current_batch and _one(db,InternshipAgreement,tenant_id,batch_id=current_batch.id,status="EFFECTIVE")),"compliance":bool(_one(db,InternshipComplianceTemplate,tenant_id,template_code=f"{MARKER}-COMPLIANCE")),"recruitment":bool(_one(db,InternshipRecruitmentCampaign,tenant_id,campaign_code=f"{MARKER}-ROUND2",status="OPEN")),"historicalArchive":bool(historical_batch and _one(db,InternshipArchive,tenant_id,batch_id=historical_batch.id,status="ARCHIVED")),"historicalFinalScore":bool(historical_batch and _one(db,InternshipFinalScore,tenant_id,batch_id=historical_batch.id,status="ARCHIVED"))}
    result["passed"]=all(result.values())
    if not result["passed"]: raise RuntimeError(f"internship coverage invalid: {result}")
    return result
