"""Candidate-only MySQL tables. Not a second official timetable authority."""
from sqlalchemy import (MetaData, Table, Column, BigInteger, Integer, String,
    DateTime, Boolean, JSON, LargeBinary, UniqueConstraint, Index, ForeignKeyConstraint)
from sqlalchemy.dialects.mysql import MEDIUMBLOB, DATETIME

metadata = MetaData()
snapshots = Table('t_aa_optimizer_snapshot', metadata,
    Column('id', BigInteger, primary_key=True, autoincrement=True),
    Column('tenant_id', BigInteger, nullable=False),
    Column('term_id', BigInteger, nullable=False),
    Column('batch_id', BigInteger, nullable=False),
    Column('input_hash', String(64), nullable=False),
    Column('source_revision', String(128), nullable=False),
    Column('payload_zlib', LargeBinary().with_variant(MEDIUMBLOB(), 'mysql'), nullable=False),
    Column('payload_bytes', Integer, nullable=False),
    Column('created_at', DATETIME(fsp=6), nullable=False),
    UniqueConstraint('tenant_id', 'input_hash', name='uk_aa_opt_snapshot_hash'),
    UniqueConstraint('tenant_id', 'id', name='uk_aa_opt_snapshot_tenant_id'),
    mysql_engine='InnoDB', mysql_charset='utf8mb4')

jobs = Table('t_aa_optimizer_job', metadata,
    Column('id', BigInteger, primary_key=True, autoincrement=True),
    Column('tenant_id', BigInteger, nullable=False),
    Column('term_id', BigInteger, nullable=False),
    Column('batch_id', BigInteger, nullable=False),
    Column('snapshot_id', BigInteger, nullable=False),
    Column('requested_by', String(128), nullable=False),
    Column('requested_reason', String(500), nullable=False),
    Column('actor_context_json', JSON, nullable=False),
    Column('idempotency_key', String(64), nullable=False),
    Column('request_hash', String(64), nullable=False),
    Column('options_json', JSON, nullable=False),
    Column('state', String(32), nullable=False),
    Column('version', Integer, nullable=False),
    Column('lease_token', String(36)),
    Column('lease_until', DATETIME(fsp=6)),
    Column('attempts', Integer, nullable=False),
    Column('cancel_requested', Boolean, nullable=False),
    Column('result_json', JSON),
    Column('last_error', String(100)),
    Column('created_at', DATETIME(fsp=6), nullable=False),
    Column('updated_at', DATETIME(fsp=6), nullable=False),
    Column('completed_at', DATETIME(fsp=6)),
    UniqueConstraint('tenant_id', 'batch_id', 'idempotency_key',
                     name='uk_aa_opt_job_idempotency'),
    ForeignKeyConstraint(['tenant_id', 'snapshot_id'],
        ['t_aa_optimizer_snapshot.tenant_id', 't_aa_optimizer_snapshot.id'],
        name='fk_aa_opt_job_snapshot_tenant', ondelete='RESTRICT'),
    Index('ix_aa_opt_job_due', 'tenant_id', 'state', 'lease_until', 'id'),
    mysql_engine='InnoDB', mysql_charset='utf8mb4')
