"""Platform Operations routers."""
from . import platform_router as _platform_router
from . import platform_code_first_hardening as _code_first_hardening
from . import platform_cross_authority_hardening as _cross_authority_hardening

_code_first_hardening.install_into_platform_router(_platform_router.router)
_cross_authority_hardening.install_into_platform_router(_platform_router.router)
from . import module_commerce_router as _module_commerce
_module_commerce.install_into_platform_router(_platform_router.router)
from . import module_commerce_finance_router as _module_commerce_finance
_module_commerce_finance.install_into_platform_router(_platform_router.router)
from . import module_commerce_operations_router as _module_commerce_operations
_module_commerce_operations.install_into_platform_router(_platform_router.router)
from . import module_commerce_renewal_router as _module_commerce_renewal
_module_commerce_renewal.install_into_platform_router(_platform_router.router)
router = _platform_router.router

__all__ = ["router"]
