<template><div v-if="state.visible" class="sys-dialog-mask" @click.self="cancel"><section class="sys-dialog" role="dialog" aria-modal="true" aria-labelledby="system-dialog-title" @keydown.esc.prevent="cancel"><header :class="`is-${state.type}`"><span aria-hidden="true">{{ state.type === 'danger' ? '!' : '?' }}</span><h2 id="system-dialog-title">{{ state.title }}</h2></header><main><p>{{ state.message }}</p><textarea v-if="state.mode === 'prompt'" ref="inputEl" v-model="state.value" rows="3" :placeholder="state.placeholder" @input="state.error=''"/><small v-if="state.error" role="alert">{{ state.error }}</small></main><footer><button v-if="state.mode !== 'alert'" type="button" class="sys-dialog-btn" @click="cancel">{{ state.cancelText }}</button><button ref="confirmEl" type="button" class="sys-dialog-btn is-primary" @click="confirm">{{ state.confirmText }}</button></footer></section></div></template>
<script setup>
import { nextTick, ref, watch } from 'vue'
import { finishSystemDialog, systemDialogState as state } from '@/services/systemDialog'
const inputEl=ref(null); const confirmEl=ref(null)
watch(() => state.visible, async visible => { if (!visible) return; await nextTick(); (state.mode === 'prompt' ? inputEl.value : confirmEl.value)?.focus() })
function cancel(){ finishSystemDialog(false) } function confirm(){ finishSystemDialog(true) }
</script>
<style scoped>
.sys-dialog-mask{position:fixed;inset:0;z-index:calc(var(--z-modal) + 50);display:grid;place-items:center;padding:var(--space-6);background:var(--bg-mask);backdrop-filter:blur(2px)}.sys-dialog{width:460px;max-width:100%;overflow:hidden;border:1px solid var(--border-base);border-radius:var(--radius-lg);background:var(--bg-card);box-shadow:var(--shadow-lg)}.sys-dialog header{display:flex;align-items:center;gap:var(--space-2);padding:var(--space-5) var(--space-6) 0}.sys-dialog header span{display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:var(--warning-50);color:var(--warning-600);font-weight:700}.sys-dialog header.is-danger span{background:var(--danger-50);color:var(--danger-600)}.sys-dialog h2{margin:0;color:var(--text-primary);font-size:var(--font-size-lg)}.sys-dialog main{padding:var(--space-4) var(--space-6)}.sys-dialog p{margin:0;color:var(--text-secondary);line-height:var(--line-height-base);white-space:pre-line}.sys-dialog textarea{width:100%;min-height:86px;margin-top:var(--space-3);padding:var(--space-2) var(--space-3);border:1px solid var(--border-base);border-radius:var(--radius-base);color:var(--text-primary);font:inherit;resize:vertical}.sys-dialog textarea:focus{outline:none;border-color:var(--primary-500)}.sys-dialog small{display:block;margin-top:var(--space-1);color:var(--danger-600)}.sys-dialog footer{display:flex;justify-content:flex-end;gap:var(--space-3);padding:var(--space-4) var(--space-6) var(--space-5)}.sys-dialog-btn{height:34px;min-width:88px;padding:0 var(--space-4);border:1px solid var(--border-base);border-radius:var(--radius-base);background:var(--bg-card);color:var(--text-secondary);cursor:pointer}.sys-dialog-btn.is-primary{border-color:var(--primary-600);background:var(--primary-600);color:#fff}
</style>
