/** Help Center V3-05 · 高频故障库第二批：账号、模块、文件、限流、导出、服务异常。 */
import { HELP_AUTHORIZATION_PRINCIPLE } from './helpRoleGuidance.js'

const COMMON_ROLES = ['学生', '任课教师', '辅导员', '学院管理员', '教务处管理员', '学工处管理员', '学校管理员']

export const HIGH_FREQUENCY_TROUBLESHOOTING_V305B_CARDS = [
  {
    id: 'tr-v3-login-auth-401',
    module: '高频故障库 · 登录与身份',
    title: '提示未登录、登录失效或微信授权失效时怎么处理',
    roles: COMMON_ROLES,
    entry: '任意页面出现 401、UNAUTHORIZED、WECHAT_AUTH_REQUIRED 或被要求重新登录时',
    keywords: ['401', 'UNAUTHORIZED', 'WECHAT_AUTH_REQUIRED', '登录失效', '重新登录', '微信授权', 'token'],
    summary: '统一异常合同把 UNAUTHORIZED 和 WECHAT_AUTH_REQUIRED 都作为 401 身份问题处理。身份失效时应重新建立真实会话，不通过刷新旧 token、复制他人链接或前端缓存继续写业务。',
    authorizationPrinciple: HELP_AUTHORIZATION_PRINCIPLE,
    prerequisites: ['记录当前页面和业务对象，避免重新登录后找不到原任务。', '确认是身份失效而不是 403 权限/数据范围问题。'],
    permissions: ['重新登录只恢复当前账号真实身份，不会自动增加角色、permissionCode 或数据范围。'],
    steps: ['停止继续提交当前写操作。', '重新登录或重新完成微信授权。', '回到原业务记录并重新读取服务器最新状态、version 和 allowedActions。', '确认账号、学校和当前角色正确后再继续一次原动作。'],
    successCriteria: ['重新登录后恢复当前账号真实会话，并回到最新业务状态；不会重复生成前一次未知结果。'],
    troubleshooting: ['重新登录后变成 403：按权限/数据范围故障卡继续排查。', '登录后学校或角色不对：不要继续办理原业务。'],
    nextSteps: ['身份恢复后先刷新原记录，再继续业务，不直接重放登录失效前的旧请求。'],
    contactAdminWhen: ['正确账号反复登录后仍立即 401。', '同一账号登录后解析到错误学校、错误人员或错误角色。']
  },
  {
    id: 'tr-v3-module-readonly',
    module: '高频故障库 · 模块授权',
    title: '模块未授权或已过期只读：不要把它当普通按钮权限问题',
    roles: ['学院管理员', '教务处管理员', '学工处管理员', '学校管理员'],
    entry: '进入模块或执行写操作时出现 MODULE_NOT_AUTHORIZED / MODULE_EXPIRED_READONLY',
    keywords: ['MODULE_NOT_AUTHORIZED', 'MODULE_EXPIRED_READONLY', '模块未授权', '模块过期', '只读', '403'],
    summary: '模块级授权与普通动作权限不是一回事。MODULE_NOT_AUTHORIZED 表示当前租户没有该模块授权；MODULE_EXPIRED_READONLY 表示模块已进入过期只读边界。前端不能通过显示按钮绕过租户模块状态。',
    authorizationPrinciple: HELP_AUTHORIZATION_PRINCIPLE,
    prerequisites: ['确认当前学校是否已开通该模块，以及模块当前授权状态。', '区分“模块级不可用”和“用户级无权限”。'],
    permissions: ['即使用户有模块内 permissionCode，租户模块未授权或已进入只读状态时，服务端仍可拒绝写操作。'],
    steps: ['查看错误 bizCode，确认是 MODULE_NOT_AUTHORIZED 还是 MODULE_EXPIRED_READONLY。', '未授权：由学校/平台授权流程确认模块是否应开通。', '过期只读：保留现有可读数据，不通过前端恢复新增、审批、发布等写动作。', '模块状态恢复后重新进入页面并读取 supportedActions/allowedActions。'],
    successCriteria: ['未授权模块不产生正式写入；过期只读模块只保留允许的只读能力；恢复授权后服务端重新下发真实动作。'],
    troubleshooting: ['菜单能看到但写操作被拒绝：先看模块授权状态，不先修改用户角色。', '模块已恢复但页面仍只读：刷新能力与会话缓存。'],
    nextSteps: ['模块状态确认后再处理具体用户权限或业务状态问题。'],
    contactAdminWhen: ['租户授权记录显示有效，但服务端持续返回模块未授权/过期只读。', '过期只读状态下仍能完成正式写入，应按授权缺陷处理。']
  },
  {
    id: 'tr-v3-file-upload',
    module: '高频故障库 · 文件上传',
    title: '文件上传失败：先看类型、大小、上传会话和安全扫描',
    roles: COMMON_ROLES,
    entry: '材料、附件、Excel 等正式文件上传入口出现失败、卡住或上传后不能用于业务时',
    keywords: ['文件上传', 'FILE_TYPE_NOT_ALLOWED', 'FILE_TOO_LARGE', 'UPLOAD_FAILED', '413', '上传会话', '安全扫描', 'scanStatus', 'readyForBusiness'],
    summary: '正式文件链不是“选完文件就算成功”。服务端会校验类型/大小并通过上传会话完成对象核验，上传完成后文件还可能进入安全扫描；只有 readyForBusiness 等正式条件满足后才能被业务消费。',
    authorizationPrinciple: HELP_AUTHORIZATION_PRINCIPLE,
    prerequisites: ['确认使用业务页面允许的文件类型和大小。', '保留上传错误码、文件名、大小和 traceId。'],
    permissions: ['能上传文件不代表能把文件绑定到任意学生/业务记录；绑定仍受租户、本人/业务 owner 和模块权限约束。'],
    steps: ['FILE_TYPE_NOT_ALLOWED：换成页面允许的正式格式，不改扩展名伪装文件。', 'FILE_TOO_LARGE/413：按页面限制压缩或拆分材料，不反复提交同一超限文件。', '上传会话未完成：重新读取会话状态；未知结果时先确认是否已经生成 fileId。', '上传完成但不能提交业务：查询 scanStatus/readyForBusiness，等待安全扫描完成；扫描失败只走正式重试入口。'],
    successCriteria: ['文件形成唯一正式 fileId，状态可查询，安全扫描通过后才进入业务提交；失败不会生成假成功材料。'],
    troubleshooting: ['显示“上传完成”但业务仍不可提交：优先看安全扫描和业务绑定状态。', '网络中断后不要立即重复上传，先确认原会话是否已经完成。'],
    nextSteps: ['文件 readyForBusiness 后再提交对应材料/业务版本，并确认业务端已引用正确 fileId。'],
    contactAdminWhen: ['符合类型和大小要求仍稳定 UPLOAD_FAILED。', '上传会话显示完成但 fileId/扫描状态长期无法查询或文件被错误绑定。']
  },
  {
    id: 'tr-v3-rate-limited-429',
    module: '高频故障库 · 限流与重复操作',
    title: '提示 429 / RATE_LIMITED：停止连续点击，等服务恢复窗口',
    roles: COMMON_ROLES,
    entry: '查询、提交、登录或其他接口出现 429 / RATE_LIMITED 时',
    keywords: ['429', 'RATE_LIMITED', '限流', '请求过多', '重复点击', '稍后重试'],
    summary: 'RATE_LIMITED 表示服务端正在保护系统，不代表当前业务一定失败。连续点击只会延长问题并增加重复请求风险；写操作尤其应先确认前一次是否已经成功。',
    authorizationPrinciple: HELP_AUTHORIZATION_PRINCIPLE,
    prerequisites: ['先停止连续点击。', '如果刚才是写操作，记录业务对象和 traceId。'],
    permissions: ['提高角色权限不能解除限流；限流是系统保护边界。'],
    steps: ['停止重复请求并等待短暂恢复窗口。', '写操作先刷新业务详情，确认前一次是否已经成功形成正式状态。', '确认未成功且已恢复后，只重新提交一次。', '批量/导出等大任务优先查看已有任务，不重复创建。'],
    successCriteria: ['恢复后只产生一次有效业务结果，不因连续点击产生重复任务或重复写入。'],
    troubleshooting: ['429 后刷新看到业务已成功：不要再次提交。', '单个普通查询长期 429：记录 traceId 和发生时间。'],
    nextSteps: ['系统恢复后继续当前业务；频繁批量操作尽量走正式任务中心。'],
    contactAdminWhen: ['低频正常操作也长时间持续 429。', '限流期间仍产生多笔重复正式业务事实。']
  },
  {
    id: 'tr-v3-export-job',
    module: '高频故障库 · 异步导出',
    title: '导出一直处理中、下载不了或文件已过期时怎么处理',
    roles: ['任课教师', '辅导员', '学院管理员', '教务处管理员', '学工处管理员', '学校管理员'],
    entry: '发起正式导出后，到统一数据交换/任务中心查看导出任务详情',
    keywords: ['导出', 'ExportJob', '导出任务', 'SUCCEEDED', 'FAILED', 'EXPIRED', 'download-ticket', '下载票据', '任务中心'],
    summary: '正式导出应以 ExportJob/任务中心为权威，不以浏览器“已点击下载”判断完成。任务成功后下载还要经过短时一次性 download ticket；任务过期或被撤销后旧票据不能继续使用。',
    authorizationPrinciple: HELP_AUTHORIZATION_PRINCIPLE,
    prerequisites: ['保留导出 jobId，并确认自己有权查看该任务。', '不要因页面暂时没有文件就重复创建相同导出。'],
    permissions: ['查看任务、下载文件、撤销任务分别受对应权限和 OWN/MODULE/TENANT 可见范围约束。'],
    steps: ['先打开导出任务详情确认真实状态。', '任务尚未成功时继续查看原 jobId，不重复创建。', 'SUCCEEDED 后通过正式 download-ticket 创建短时一次性票据，再下载文件。', '任务 EXPIRED、已撤销或下载票据失效时，按页面允许动作重新生成任务/票据，不使用旧链接。', '若任务失败，保留 jobId 和错误信息，由正式失败恢复/重试链处理。'],
    successCriteria: ['每次导出都有可查询任务记录；只有成功任务能下载；下载受短时一次性票据和权限范围保护。'],
    troubleshooting: ['点击导出后没有立即下载不等于失败，先看任务中心。', '下载链接很快失效属于安全设计，应重新申请票据，不长期保存直链。'],
    nextSteps: ['下载后核对文件范围和筛选条件；敏感导出按用途保存和审计要求处理。'],
    contactAdminWhen: ['同一 jobId 长期停留且状态不再推进。', 'SUCCEEDED 且权限/范围正确，但无法创建或消费下载票据。']
  },
  {
    id: 'tr-v3-service-5xx',
    module: '高频故障库 · 服务异常',
    title: '出现 500 / 503 或“服务异常”时先保留 traceId，不重复写业务',
    roles: COMMON_ROLES,
    entry: '任意页面出现 SERVER_ERROR、500、503 或明确“服务异常”提示时',
    keywords: ['500', '503', 'SERVER_ERROR', 'TENANT_GUARD_UNAVAILABLE', '服务异常', 'traceId', '稍后重试'],
    summary: '统一异常处理会把未处理异常转换为 SERVER_ERROR，并保留 traceId；部分关键安全依赖不可用时会 503 fail-closed。未知写结果时最危险的动作是连续重复提交。',
    authorizationPrinciple: HELP_AUTHORIZATION_PRINCIPLE,
    prerequisites: ['记录错误时间、页面、业务对象、bizCode/message 和 traceId。', '如果刚才执行的是写操作，先把结果视为“未知”，不要立即再次提交。'],
    permissions: ['500/503 不是通过增加权限解决；安全依赖 503 时更不能绕过 fail-closed。'],
    steps: ['停止连续点击或刷新重放写请求。', '重新读取业务详情，确认刚才动作是否已成功落库/推进状态。', '若业务未变化，可在服务恢复后重新执行一次；若已变化，以服务器最新状态继续。', '涉及敏感数据、租户守卫等 503 时等待依赖恢复，不通过缓存、数据库旁路或前端 fallback 获取数据。'],
    successCriteria: ['最终业务事实可确认且只写一次；错误可通过 traceId 定位；安全依赖失败期间保持 fail-closed。'],
    troubleshooting: ['查询页偶发 500：可稍后刷新；写操作 500 必须先查结果再重试。', '503 后刷新仍失败：不要切换成管理员账号试图绕过安全守卫。'],
    nextSteps: ['服务恢复并确认业务状态后继续流程。'],
    contactAdminWhen: ['同一合法操作稳定复现 500/503。', '错误没有 traceId，或服务异常后出现重复写入、越权数据或状态半成功。']
  }
]
