<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import CandidateCard from '../components/applicant/CandidateCard.vue'
import ApplicantDetailView from './ApplicantDetailView.vue'
import { enterpriseInternshipApi } from '../services/enterpriseInternshipApi'
import { useEnterpriseContextStore } from '../stores/enterpriseContext'
const route=useRoute(),router=useRouter(),context=useEnterpriseContextStore(),loading=ref(true),error=ref(''),items=ref([]),counts=ref({}),pipeline=ref('ALL'),keyword=ref(''),positionId=ref(''),major=ref(''),grade=ref(''),volunteerNo=ref(''),match=ref('')
const page=ref(1),pageSize=50,total=ref(null),hasNext=ref(false),positionOptions=ref([])
const selectedId=computed(()=>route.params.id||'')
const selectedApplicant=computed(()=>items.value.find(item=>String(item.applicationId||item.id)===String(selectedId.value))||null)
const tabs=[['ALL','全部'],['PENDING','待处理'],['INTERESTED','感兴趣'],['INTERVIEW','面试'],['ACCEPT_INTENT','拟接收'],['REJECTED','不合适']]
const pageInfo=computed(()=>total.value===null?`第 ${page.value} 页`:`第 ${page.value} 页 · 共 ${total.value} 人`)
async function load(){
  loading.value=true;error.value=''
  try{
    const data=await enterpriseInternshipApi.applications({page:page.value,pageSize,pipeline:pipeline.value==='ALL'?'':pipeline.value,keyword:keyword.value,positionId:positionId.value,major:major.value,grade:grade.value,volunteerNo:volunteerNo.value,match:match.value})
    items.value=Array.isArray(data)?data:(data?.items||[]);counts.value=Array.isArray(data)?{}:(data?.counts||{})
    total.value=Array.isArray(data)||data?.total===undefined||data?.total===null?null:Number(data.total)
    hasNext.value=Array.isArray(data)?false:(data?.hasNext===true||(Number.isFinite(total.value)&&page.value*pageSize<total.value))
    if(!selectedId.value&&items.value.length&&window.innerWidth>=1000)router.replace(`/applications/${items.value[0].applicationId||items.value[0].id}`)
  }catch(e){items.value=[];total.value=null;hasNext.value=false;error.value=e.message||'报名学生加载失败'}finally{loading.value=false}
}
async function loadPositions(){try{const data=await enterpriseInternshipApi.positions();positionOptions.value=Array.isArray(data)?data:(data?.items||[])}catch{positionOptions.value=[]}}
function select(item){router.push(`/applications/${item.applicationId||item.id}`)}
function refresh(){load()}
function backToCandidates(){router.push('/applications')}
function applyFilters(){page.value=1;load()}
function previousPage(){if(page.value<=1)return;page.value-=1;load()}
function nextPage(){if(!hasNext.value)return;page.value+=1;load()}
onMounted(()=>{load();loadPositions()});watch(pipeline,()=>{page.value=1;load()})
</script>
<template><section class="ep-page wide"><div class="ep-page-head"><div><h1 class="ep-title">报名学生</h1><p class="ep-subtitle">只处理本企业岗位的正式 InternshipApplication；右侧材料固定读取 ApplicationMaterialSnapshot。</p></div></div><div v-if="context.historyMode" class="history-note">历史招聘季：申请材料与企业 Decision 记录保留只读，新的候选人处理动作已关闭。</div><div class="pipeline"><button v-for="tab in tabs" :key="tab[0]" type="button" :class="{active:pipeline===tab[0]}" @click="pipeline=tab[0]">{{ tab[1] }} <span>{{ counts[tab[0]]??'—' }}</span></button></div><div class="filters"><input v-model.trim="keyword" class="ep-input" placeholder="搜索姓名/岗位"><select v-model="positionId" class="ep-select"><option value="">全部岗位</option><option v-for="position in positionOptions" :key="position.id" :value="position.id">{{ position.title||position.name }}</option></select><input v-model.trim="major" class="ep-input" placeholder="专业"><input v-model.trim="grade" class="ep-input" placeholder="年级"><select v-model="volunteerNo" class="ep-select"><option value="">志愿顺序</option><option value="1">第1志愿</option><option value="2">第2志愿</option><option value="3">第3志愿</option></select><select v-model="match" class="ep-select"><option value="">匹配程度</option><option value="HIGH">高匹配</option><option value="MEDIUM">一般</option><option value="LOW">低匹配</option></select><button class="ep-btn" @click="applyFilters">筛选</button></div><div v-if="error" class="ep-error">{{ error }}</div><div class="workbench ep-card" :class="{showDetail:Boolean(selectedId)}"><aside class="candidates"><div v-if="loading" class="ep-empty">正在加载报名学生…</div><div v-else-if="!items.length" class="ep-empty">暂无报名学生</div><CandidateCard v-for="item in items" :key="item.applicationId||item.id" :applicant="item" :selected="String(selectedId)===String(item.applicationId||item.id)" @select="select" /><div v-if="!loading&&items.length" class="pager"><button class="ep-btn" :disabled="page<=1" @click="previousPage">上一页</button><span>{{ pageInfo }}</span><button class="ep-btn" :disabled="!hasNext" @click="nextPage">下一页</button></div></aside><main class="detail-pane"><button v-if="selectedId" type="button" class="mobile-back" @click="backToCandidates">← 返回候选列表</button><ApplicantDetailView :application-id="selectedId" :summary="selectedApplicant" :campaign-writable="context.recruitmentWritable" @changed="refresh" /></main></div></section></template>
<style scoped>.wide{max-width:1400px}.history-note{padding:12px 14px;margin-bottom:12px;background:var(--warn-bg);color:var(--warn-fg);border-radius:8px;font-size:13px}.pipeline{display:flex;gap:2px;border-bottom:1px solid var(--line);margin-bottom:12px;background:#fff;border-radius:10px 10px 0 0;overflow:auto}.pipeline button{border:0;background:transparent;min-height:46px;padding:0 14px;color:var(--t2);border-bottom:2px solid transparent;white-space:nowrap}.pipeline button.active{color:var(--pri);border-bottom-color:var(--pri);font-weight:700}.pipeline span{font-size:11px;color:var(--t3)}.filters{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.filters .ep-input,.filters .ep-select{width:150px}.workbench{display:grid;grid-template-columns:420px minmax(0,1fr);min-height:650px;overflow:hidden}.candidates{border-right:1px solid var(--line);max-height:calc(100vh - 245px);overflow:auto}.pager{position:sticky;bottom:0;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:10px;border-top:1px solid var(--line);background:#fff;font-size:12px;color:var(--t3)}.pager .ep-btn{min-height:34px;padding:0 10px}.detail-pane{position:relative;min-width:0;min-height:650px;background:#fff}.mobile-back{display:none}@media(max-width:1279px) and (min-width:1000px){.workbench{grid-template-columns:360px minmax(0,1fr)}}@media(max-width:999px){.workbench{display:block}.candidates{max-height:none;border-right:0}.detail-pane{display:none}.workbench.showDetail .candidates{display:none}.workbench.showDetail .detail-pane{display:block}.mobile-back{display:block;width:100%;height:44px;border:0;border-bottom:1px solid var(--line);background:#fff;text-align:left;padding:0 16px;color:var(--pri);font-weight:600}.filters .ep-input,.filters .ep-select{width:calc(50% - 4px)}}@media(max-width:600px){.filters .ep-input,.filters .ep-select{width:100%}}</style>
