<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import CandidateCard from '../components/applicant/CandidateCard.vue'
import ApplicantDetailView from './ApplicantDetailView.vue'
import { enterpriseInternshipApi } from '../services/enterpriseInternshipApi'
const route=useRoute(),router=useRouter(),loading=ref(true),error=ref(''),items=ref([]),counts=ref({}),pipeline=ref('ALL'),keyword=ref(''),positionId=ref(''),major=ref(''),grade=ref(''),volunteerNo=ref(''),match=ref('')
const selectedId=computed(()=>route.params.id||'')
const tabs=[['ALL','全部'],['PENDING','待处理'],['INTERESTED','感兴趣'],['INTERVIEW','面试'],['ACCEPT_INTENT','拟接收'],['REJECTED','不合适']]
async function load(){loading.value=true;error.value='';try{const data=await enterpriseInternshipApi.applications({pipeline:pipeline.value==='ALL'?'':pipeline.value,keyword:keyword.value,position_id:positionId.value,major:major.value,grade:grade.value,volunteer_no:volunteerNo.value,match:match.value});items.value=Array.isArray(data)?data:(data?.items||[]);counts.value=data?.counts||{};if(!selectedId.value&&items.value.length) router.replace(`/applications/${items.value[0].application_id||items.value[0].applicationId||items.value[0].id}`)}catch(e){error.value=e.message||'报名学生加载失败'}finally{loading.value=false}}
function select(item){router.push(`/applications/${item.application_id||item.applicationId||item.id}`)}
function refresh(){load()}
onMounted(load);watch(pipeline,load)
</script>
<template><section class="ep-page wide"><div class="ep-page-head"><div><h1 class="ep-title">报名学生</h1><p class="ep-subtitle">只处理本企业岗位的正式 InternshipApplication；右侧材料固定读取 ApplicationMaterialSnapshot。</p></div></div><div class="pipeline"><button v-for="tab in tabs" :key="tab[0]" type="button" :class="{active:pipeline===tab[0]}" @click="pipeline=tab[0]">{{ tab[1] }} <span>{{ counts[tab[0]]??'—' }}</span></button></div><div class="filters"><input v-model="keyword" class="ep-input" placeholder="搜索姓名/岗位"><input v-model="positionId" class="ep-input" placeholder="岗位"><input v-model="major" class="ep-input" placeholder="专业"><input v-model="grade" class="ep-input" placeholder="年级"><select v-model="volunteerNo" class="ep-select"><option value="">志愿顺序</option><option value="1">第1志愿</option><option value="2">第2志愿</option><option value="3">第3志愿</option></select><select v-model="match" class="ep-select"><option value="">匹配程度</option><option value="HIGH">高匹配</option><option value="MEDIUM">一般</option><option value="LOW">低</option></select><button class="ep-btn" @click="load">筛选</button></div><div v-if="error" class="ep-error">{{ error }}</div><div class="workbench ep-card"><aside class="candidates"><div v-if="loading" class="ep-empty">正在加载报名学生…</div><div v-else-if="!items.length" class="ep-empty">暂无报名学生</div><CandidateCard v-for="item in items" :key="item.application_id||item.applicationId||item.id" :applicant="item" :selected="String(selectedId)===String(item.application_id||item.applicationId||item.id)" @select="select" /></aside><main class="detail-pane"><ApplicantDetailView :application-id="selectedId" @changed="refresh" /></main></div></section></template>
<style scoped>.wide{max-width:1400px}.pipeline{display:flex;gap:2px;border-bottom:1px solid var(--line);margin-bottom:12px;background:#fff;border-radius:10px 10px 0 0}.pipeline button{border:0;background:transparent;min-height:46px;padding:0 14px;color:var(--t2);border-bottom:2px solid transparent}.pipeline button.active{color:var(--pri);border-bottom-color:var(--pri);font-weight:700}.pipeline span{font-size:11px;color:var(--t3)}.filters{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.filters .ep-input{width:150px}.workbench{display:grid;grid-template-columns:420px minmax(0,1fr);min-height:650px;overflow:hidden}.candidates{border-right:1px solid var(--line);max-height:calc(100vh - 245px);overflow:auto}.detail-pane{position:relative;min-width:0;min-height:650px;background:#fff}@media(max-width:1000px){.workbench{grid-template-columns:360px minmax(0,1fr)}}@media(max-width:820px){.workbench{display:block}.candidates{max-height:none;border-right:0}.detail-pane{display:none}.workbench:has(.candidate.selected) .candidates{display:none}.workbench:has(.candidate.selected) .detail-pane{display:block}.filters .ep-input{width:calc(50% - 4px)}}</style>
