<script setup>
import { computed,onMounted,ref } from 'vue'
import { useRouter } from 'vue-router'
import { enterpriseInternshipApi } from '../services/enterpriseInternshipApi'
import { setSelectedCampaignId } from '../services/request'
// Authority contract: this screen may select campaign only; 不允许选择 companyId，企业范围由登录成员关系决定。
const router=useRouter(),loading=ref(true),error=ref(''),items=ref([])
const activeItems=computed(()=>items.value.filter(item=>!['CLOSED','ARCHIVED'].includes(String(item.status||''))))
const historyItems=computed(()=>items.value.filter(item=>['CLOSED','ARCHIVED'].includes(String(item.status||''))))
async function load(){loading.value=true;error.value='';try{const data=await enterpriseInternshipApi.campaigns();items.value=Array.isArray(data)?data:(data?.items||[])}catch(e){items.value=[];error.value=e.message||'招聘季列表加载失败'}finally{loading.value=false}}
async function enter(item){const id=item.id||item.campaignId;if(!id)return;setSelectedCampaignId(id);await router.push('/home')}
onMounted(load)
</script>
<template><main class="select-page"><section class="panel"><div class="brand">跃科 · 企业协同中心</div><h1>选择招聘季</h1><p>你的企业范围由登录账号和学校授权确定；这里只选择要进入的招聘季。历史招聘季可进入只读视图，后续实习协同功能是否开放以学校授权为准。</p><div v-if="error" class="ep-error">{{ error }}。当前没有可确认的招聘季时，页面不会自动生成或猜测数据。</div><div v-if="loading" class="ep-card ep-empty">正在读取当前企业可参与招聘季…</div><template v-else><section><div class="section-head"><h2>当前招聘季</h2><span>{{ activeItems.length }} 个</span></div><div v-if="!activeItems.length" class="ep-card ep-empty">当前没有可进入的招聘季</div><div v-else class="campaigns"><button v-for="item in activeItems" :key="item.id||item.campaignId" class="campaign ep-card" type="button" @click="enter(item)"><div><strong>{{ item.campaignName||item.name||`招聘季 #${item.id||item.campaignId}` }}</strong><span>{{ item.status||'状态未知' }}</span></div><p>{{ item.phaseLabel||'当前阶段以学校发布信息为准' }}</p><small>进入招聘工作台 →</small></button></div></section><section class="history-section"><div class="section-head"><h2>历史招聘季</h2><span>{{ historyItems.length }} 个</span></div><div v-if="!historyItems.length" class="ep-card ep-empty">暂无历史招聘季</div><div v-else class="campaigns"><button v-for="item in historyItems" :key="item.id||item.campaignId" class="campaign history ep-card" type="button" @click="enter(item)"><div><strong>{{ item.campaignName||item.name||`招聘季 #${item.id||item.campaignId}` }}</strong><span>{{ item.status }}</span></div><p>招聘操作已关闭；岗位、申请和企业处理记录仍保留查看。</p><small>进入历史只读视图 →</small></button></div></section></template><button class="back" type="button" @click="router.push('/login')">返回登录</button></section></main></template>
<style scoped>.select-page{min-height:100vh;background:var(--page);padding:56px 20px}.panel{width:min(900px,100%);margin:0 auto}.brand{color:var(--pri);font-weight:800}.panel>h1{margin:12px 0 6px;font-size:28px}.panel>p{margin:0 0 22px;color:var(--t3);line-height:1.7}.section-head{display:flex;align-items:center;justify-content:space-between;margin:22px 0 10px}.section-head h2{margin:0;font-size:16px}.section-head span{font-size:12px;color:var(--t3)}.history-section{margin-top:28px;padding-top:6px;border-top:1px solid var(--line)}.campaigns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.campaign{text-align:left;padding:18px;border-color:var(--line)}.campaign:hover{border-color:var(--pri-100);box-shadow:0 8px 24px rgba(47,107,255,.08)}.campaign>div{display:flex;justify-content:space-between;gap:12px}.campaign strong{font-size:16px}.campaign span{font-size:11px;color:var(--pri);background:var(--pri-50);padding:3px 7px;border-radius:4px}.campaign p{color:var(--t3);font-size:13px;line-height:1.6}.campaign small{color:var(--pri);font-weight:600}.campaign.history span{color:var(--warn-fg);background:var(--warn-bg)}.back{margin-top:22px;border:0;background:transparent;color:var(--t3)}@media(max-width:700px){.campaigns{grid-template-columns:1fr}}</style>
