<script setup>
import { onMounted, reactive, ref } from 'vue'
import { enterpriseInternshipApi } from '../services/enterpriseInternshipApi'
const loading=ref(true), saving=ref(false), error=ref(''), message=ref('')
const form=reactive({logoFileId:null,coverFileId:null,shortName:'',shortIntro:'',website:'',mainBusiness:'',establishedYear:null,address:''})
const school=reactive({qualificationStatus:'—',coopStatus:'—',accessValidUntil:'—',blacklist:false,schoolReview:'—'})
onMounted(async()=>{try{const data=await enterpriseInternshipApi.company();Object.assign(form,{logoFileId:data?.logoFileId??null,coverFileId:data?.coverFileId??null,shortName:data?.shortName||'',shortIntro:data?.shortIntro||'',website:data?.website||'',mainBusiness:data?.mainBusiness||'',establishedYear:data?.establishedYear??null,address:data?.address||''});Object.assign(school,{qualificationStatus:data?.qualificationStatus||'—',coopStatus:data?.coopStatus||'—',accessValidUntil:data?.accessValidUntil||'—',blacklist:Boolean(data?.blacklist),schoolReview:data?.schoolReview||data?.reviewComment||'—'})}catch(e){error.value=e.message||'企业资料加载失败'}finally{loading.value=false}})
async function save(){saving.value=true;error.value='';message.value='';try{await enterpriseInternshipApi.updateCompany({...form});message.value='企业公开资料已保存'}catch(e){error.value=e.message||'保存失败'}finally{saving.value=false}}
</script>
<template><section class="ep-page"><div class="ep-page-head"><div><h1 class="ep-title">企业资料</h1><p class="ep-subtitle">只维护对学生公开的企业介绍；学校准入结论始终只读。</p></div><button class="ep-btn ep-btn-primary" :disabled="loading||saving" @click="save">{{ saving?'保存中…':'保存公开资料' }}</button></div><div v-if="error" class="ep-error">{{ error }}</div><div v-if="message" class="notice">{{ message }}</div><div class="grid"><div class="ep-card panel"><h2 class="ep-section-title">公开资料</h2><label>企业简称<input v-model="form.shortName" class="ep-input"></label><label>Logo 文件 ID<input v-model.number="form.logoFileId" type="number" class="ep-input" placeholder="由正式文件中心选择器接入"></label><label>官网<input v-model="form.website" class="ep-input"></label><label>成立年份<input v-model.number="form.establishedYear" type="number" min="1800" max="2100" class="ep-input"></label><label>主营业务<textarea v-model="form.mainBusiness" class="ep-textarea" rows="3" /></label><label>一句话介绍<textarea v-model="form.shortIntro" class="ep-textarea" rows="3" /></label><label>办公地址<input v-model="form.address" class="ep-input"></label></div><aside class="ep-card panel"><h2 class="ep-section-title">学校控制信息 · 只读</h2><dl><div><dt>资质状态</dt><dd>{{ school.qualificationStatus }}</dd></div><div><dt>合作状态</dt><dd>{{ school.coopStatus }}</dd></div><div><dt>准入有效期</dt><dd>{{ school.accessValidUntil }}</dd></div><div><dt>黑名单</dt><dd>{{ school.blacklist?'是':'否' }}</dd></div><div><dt>学校审核</dt><dd>{{ school.schoolReview }}</dd></div></dl><p class="ep-muted">资质、合作状态、准入有效期、黑名单与学校审核结论均由学校 Authority 控制。</p></aside></div></section></template>
<style scoped>.grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:16px}.panel{padding:20px}label{display:flex;flex-direction:column;gap:7px;font-size:13px;color:var(--t2);margin-bottom:15px}.ep-input,.ep-textarea{width:100%}dl{margin:0}dl div{display:flex;justify-content:space-between;gap:20px;padding:13px 0;border-bottom:1px solid var(--line)}dt{color:var(--t3)}dd{margin:0;font-weight:600}.notice{padding:12px 14px;background:var(--ok-bg);color:var(--ok-fg);border-radius:8px;margin-bottom:14px}@media(max-width:900px){.grid{grid-template-columns:1fr}}</style>
