<script setup>
import { onMounted, reactive, ref } from 'vue'
import { enterpriseInternshipApi } from '../services/enterpriseInternshipApi'
const loading=ref(true), saving=ref(false), error=ref(''), message=ref('')
const form=reactive({logo:'',short_name:'',short_intro:'',website:'',main_business:'',introduction:'',address:''})
const school=reactive({qualification_status:'—',coop_status:'—',access_valid_until:'—',blacklist:false,school_review:'—'})
onMounted(async()=>{try{const data=await enterpriseInternshipApi.company();Object.assign(form,{logo:data?.logo||'',short_name:data?.short_name||'',short_intro:data?.short_intro||'',website:data?.website||'',main_business:data?.main_business||'',introduction:data?.introduction||'',address:data?.address||''});Object.assign(school,{qualification_status:data?.qualification_status||'—',coop_status:data?.coop_status||'—',access_valid_until:data?.access_valid_until||'—',blacklist:Boolean(data?.blacklist),school_review:data?.school_review||'—'})}catch(e){error.value=e.message||'企业资料加载失败'}finally{loading.value=false}})
async function save(){saving.value=true;error.value='';message.value='';try{await enterpriseInternshipApi.updateCompany({...form});message.value='企业公开资料已保存'}catch(e){error.value=e.message||'保存失败'}finally{saving.value=false}}
</script>
<template><section class="ep-page"><div class="ep-page-head"><div><h1 class="ep-title">企业资料</h1><p class="ep-subtitle">只维护对学生公开的企业介绍；学校准入结论始终只读。</p></div><button class="ep-btn ep-btn-primary" :disabled="loading||saving" @click="save">{{ saving?'保存中…':'保存公开资料' }}</button></div><div v-if="error" class="ep-error">{{ error }}</div><div v-if="message" class="notice">{{ message }}</div><div class="grid"><div class="ep-card panel"><h2 class="ep-section-title">公开资料</h2><label>企业简称<input v-model="form.short_name" class="ep-input"></label><label>Logo / 文件引用<input v-model="form.logo" class="ep-input" placeholder="由正式文件中心适配"></label><label>官网<input v-model="form.website" class="ep-input"></label><label>主营业务<textarea v-model="form.main_business" class="ep-textarea" rows="3" /></label><label>一句话介绍<textarea v-model="form.short_intro" class="ep-textarea" rows="2" /></label><label>企业介绍<textarea v-model="form.introduction" class="ep-textarea" rows="7" /></label><label>办公地址<input v-model="form.address" class="ep-input"></label></div><aside class="ep-card panel"><h2 class="ep-section-title">学校控制信息 · 只读</h2><dl><div><dt>资质状态</dt><dd>{{ school.qualification_status }}</dd></div><div><dt>合作状态</dt><dd>{{ school.coop_status }}</dd></div><div><dt>准入有效期</dt><dd>{{ school.access_valid_until }}</dd></div><div><dt>黑名单</dt><dd>{{ school.blacklist?'是':'否' }}</dd></div><div><dt>学校审核</dt><dd>{{ school.school_review }}</dd></div></dl><p class="ep-muted">企业不能修改 qualification / coop / access validity / blacklist / school review。</p></aside></div></section></template>
<style scoped>.grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:16px}.panel{padding:20px}label{display:flex;flex-direction:column;gap:7px;font-size:13px;color:var(--t2);margin-bottom:15px}.ep-input,.ep-textarea{width:100%}dl{margin:0}dl div{display:flex;justify-content:space-between;gap:20px;padding:13px 0;border-bottom:1px solid var(--line)}dt{color:var(--t3)}dd{margin:0;font-weight:600}.notice{padding:12px 14px;background:var(--ok-bg);color:var(--ok-fg);border-radius:8px;margin-bottom:14px}@media(max-width:900px){.grid{grid-template-columns:1fr}}</style>
