<script setup>
import { computed,onMounted,reactive,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { enterpriseAuthApi } from '../services/authApi'
const route=useRoute(),router=useRouter(),loading=ref(true),submitting=ref(false),error=ref(''),preview=ref(null)
const token=computed(()=>String(route.query.token||''));const form=reactive({identity:'',password:''})
onMounted(async()=>{if(!token.value){error.value='邀请链接缺少 token';loading.value=false;return}try{preview.value=await enterpriseAuthApi.invitePreview(token.value)}catch(e){error.value=e.message||'邀请已失效或无权访问'}finally{loading.value=false}})
async function accept(){submitting.value=true;error.value='';try{await enterpriseAuthApi.acceptInvite({token:token.value,...form});await router.push('/home')}catch(e){error.value=e.message||'邀请激活失败'}finally{submitting.value=false}}
</script>
<template><main class="auth"><section class="ep-card card"><div class="logo">跃科</div><h1>企业邀请承接</h1><div v-if="loading" class="ep-empty">正在校验学校邀请…</div><div v-else-if="!preview" class="ep-error">{{ error||'邀请不可用' }}</div><template v-else><dl><div><dt>邀请学校</dt><dd>{{ preview.schoolName||preview.school_name }}</dd></div><div><dt>招聘季</dt><dd>{{ preview.campaignName||preview.campaign_name }}</dd></div><div><dt>企业名称</dt><dd>{{ preview.companyName||preview.company_name }}</dd></div><div><dt>邀请联系人</dt><dd>{{ preview.contactName||preview.contact_name }}</dd></div><div><dt>有效期</dt><dd>{{ preview.expiresAt||preview.expires_at }}</dd></div></dl><p>学校上下文已由邀请 token 锁定，无需再次选择租户。</p><form @submit.prevent="accept"><label>手机号 / 登录身份验证<input v-model.trim="form.identity" class="ep-input" required></label><label>设置或验证密码<input v-model="form.password" type="password" class="ep-input" autocomplete="new-password" required></label><div v-if="error" class="ep-error">{{ error }}</div><button class="ep-btn ep-btn-primary submit" :disabled="submitting">{{ submitting?'激活中…':'接受邀请并进入企业协同中心' }}</button></form></template></section></main></template>
<style scoped>.auth{min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(520px,100%);padding:34px}.logo{color:var(--pri);font-size:22px;font-weight:800}.card h1{margin:12px 0 18px}dl{margin:0 0 18px}dl div{display:flex;justify-content:space-between;gap:20px;padding:11px 0;border-bottom:1px solid var(--line)}dt{color:var(--t3);font-size:13px}dd{margin:0;font-weight:600}.card p{color:var(--t3);font-size:13px;line-height:1.7}label{display:flex;flex-direction:column;gap:7px;margin-bottom:14px;font-size:13px;color:var(--t2)}.submit,.ep-input{width:100%}</style>
