<script setup>
import { computed,onMounted,reactive,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { enterpriseAuthApi } from '../services/authApi'
const route=useRoute(),router=useRouter(),loading=ref(true),submitting=ref(false),error=ref(''),preview=ref(null)
const token=computed(()=>String(route.query.token||'')),tenantCode=computed(()=>String(route.query.tenantCode||route.query.tenant||''));const form=reactive({phone:'',password:''})
onMounted(async()=>{if(!token.value||!tenantCode.value){error.value='邀请链接缺少学校编码或 token';loading.value=false;return}try{preview.value=await enterpriseAuthApi.inspectInvite({tenantCode:tenantCode.value,token:token.value})}catch(e){error.value=e.message||'邀请已失效或无权访问'}finally{loading.value=false}})
async function accept(){submitting.value=true;error.value='';try{await enterpriseAuthApi.acceptInvite({tenantCode:tenantCode.value,token:token.value,phone:form.phone,password:form.password});await router.push('/home')}catch(e){error.value=e.message||'邀请激活失败'}finally{submitting.value=false}}
</script>
<template><main class="auth"><section class="ep-card card"><div class="logo">跃科</div><h1>企业邀请承接</h1><div v-if="loading" class="ep-empty">正在校验学校邀请…</div><div v-else-if="!preview" class="ep-error">{{ error||'邀请不可用' }}</div><template v-else><dl><div><dt>邀请学校</dt><dd>{{ preview.schoolName }}</dd></div><div><dt>招聘季</dt><dd>{{ preview.campaignName }}</dd></div><div><dt>企业名称</dt><dd>{{ preview.companyName }}</dd></div><div><dt>邀请联系人</dt><dd>{{ preview.inviteeName }}</dd></div><div><dt>受邀手机号</dt><dd>{{ preview.phoneMasked }}</dd></div><div><dt>成员角色</dt><dd>{{ preview.memberRole }}</dd></div><div><dt>有效期</dt><dd>{{ preview.expiresAt }}</dd></div></dl><p>学校租户、企业与招聘季均由同一 tenantCode + 邀请 token 在服务端校验；接受邀请时页面不会再次提交 campaignId 或 companyId。</p><form @submit.prevent="accept"><label>验证受邀手机号<input v-model.trim="form.phone" inputmode="tel" class="ep-input" required></label><label>设置密码（至少 8 位）<input v-model="form.password" type="password" minlength="8" class="ep-input" autocomplete="new-password" required></label><div v-if="error" class="ep-error">{{ error }}</div><button class="ep-btn ep-btn-primary submit" :disabled="submitting">{{ submitting?'激活中…':'接受邀请并进入企业协同中心' }}</button></form></template></section></main></template>
<style scoped>.auth{min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(520px,100%);padding:34px}.logo{color:var(--pri);font-size:22px;font-weight:800}.card h1{margin:12px 0 18px}dl{margin:0 0 18px}dl div{display:flex;justify-content:space-between;gap:20px;padding:11px 0;border-bottom:1px solid var(--line)}dt{color:var(--t3);font-size:13px}dd{margin:0;font-weight:600}.card p{color:var(--t3);font-size:13px;line-height:1.7}label{display:flex;flex-direction:column;gap:7px;margin-bottom:14px;font-size:13px;color:var(--t2)}.submit,.ep-input{width:100%}</style>
