<script setup>
import { computed, onMounted, ref } from 'vue'
import { enterpriseInternshipApi } from '../services/enterpriseInternshipApi'
import { useEnterpriseContextStore } from '../stores/enterpriseContext'
const context=useEnterpriseContextStore(),loading=ref(true),error=ref(''),items=ref([]),active=ref('ALL'),keyword=ref('')
const tabs=[['ALL','全部'],['DRAFT','草稿'],['PENDING','待学校审核'],['PUBLISHED','已发布'],['OFFLINE','已下线'],['RISK','风险']]
const filtered=computed(()=>items.value.filter(item=>{if(active.value==='RISK'&&!item.riskFlag&&!item.risk_flag)return false;if(active.value!=='ALL'&&active.value!=='RISK'&&item.status!==active.value)return false;const q=keyword.value.trim().toLowerCase();return !q||String(item.name||item.title||'').toLowerCase().includes(q)}))
onMounted(async()=>{try{const data=await enterpriseInternshipApi.positions();items.value=Array.isArray(data)?data:(data?.items||[])}catch(e){error.value=e.message||'岗位加载失败'}finally{loading.value=false}})
</script>
<template><section class="ep-page"><div class="ep-page-head"><div><h1 class="ep-title">我的岗位</h1><p class="ep-subtitle">企业创建 DRAFT、提交 PENDING；只有学校拥有 PUBLISH Authority。</p></div><RouterLink v-if="context.recruitmentWritable" to="/positions/new" class="ep-btn ep-btn-primary">+ 创建实习岗位</RouterLink></div><div v-if="context.historyMode" class="history-note">招聘季已关闭：岗位记录保留为历史只读，不再允许创建、编辑、提交或撤回。</div><div class="ep-toolbar bar"><input v-model="keyword" class="ep-input" placeholder="搜索岗位"><button v-for="tab in tabs" :key="tab[0]" class="tab" :class="{active:active===tab[0]}" @click="active=tab[0]">{{ tab[1] }}</button></div><div v-if="error" class="ep-error">{{ error }}</div><div v-if="loading" class="ep-card ep-empty">正在加载岗位…</div><div v-else-if="!filtered.length" class="ep-card ep-empty">暂无符合条件的岗位</div><div v-else class="list"><article v-for="item in filtered" :key="item.id" class="position ep-card"><div class="row"><div><h3>{{ item.name||item.title }}</h3><p>{{ item.city||'—' }} · 招{{ item.headcount??'—' }}人 · {{ item.major_requirement||item.majorRequirement||'专业不限/以学校核验为准' }}</p></div><div class="ep-money">{{ item.salary_display||item.salaryDisplay||'薪酬待完善' }}</div></div><div class="meta"><span class="ep-tag" :class="{warn:item.status==='PENDING',ok:item.status==='PUBLISHED',danger:item.risk_flag||item.riskFlag}">{{ item.risk_flag||item.riskFlag?'风险':item.status }}</span><span>报名 {{ item.applicant_count??item.applicantCount??0 }}</span><span>拟接收 {{ item.accept_intent_count??item.acceptIntentCount??0 }}</span><span>已落实 {{ item.placement_count??item.placementCount??0 }}</span><RouterLink v-if="context.recruitmentWritable" :to="`/positions/${item.id}/edit`" class="manage">管理岗位</RouterLink><span v-else class="manage muted">历史只读</span></div></article></div></section></template>
<style scoped>.history-note{padding:12px 14px;margin-bottom:14px;background:var(--warn-bg);color:var(--warn-fg);border-radius:8px;font-size:13px}.bar{margin-bottom:16px}.tab{min-height:38px;border:0;background:transparent;color:var(--t2);padding:0 10px;border-bottom:2px solid transparent}.tab.active{color:var(--pri);border-bottom-color:var(--pri);font-weight:600}.list{display:grid;gap:12px}.position{padding:18px 20px}.row{display:flex;justify-content:space-between;gap:20px}.row h3{margin:0 0 7px;font-size:17px}.row p{margin:0;color:var(--t3);font-size:13px}.meta{display:flex;align-items:center;gap:18px;margin-top:16px;padding-top:14px;border-top:1px solid var(--line);font-size:13px;color:var(--t3)}.manage{margin-left:auto;color:var(--pri);text-decoration:none;font-weight:600}.muted{color:var(--t3)}@media(max-width:760px){.row{flex-direction:column}.meta{flex-wrap:wrap}.manage{margin-left:0}}</style>
