import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {parse,compileTemplate} from '@vue/compiler-sfc'
import {gradeError} from '../src/modules/academicAffairs/views/parallel-c/grade-review.js'
const source=readFileSync(new URL('../src/modules/academicAffairs/views/AaMajorSplitView.vue',import.meta.url),'utf8')
const ok=data=>({code:0,data}),denied={code:403002,bizCode:'NO_DATA_SCOPE'}
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}}
const original={batchId:'9007199254740993',batchName:'分流甲',grade:'2026',maxChoices:3,sourceMajorId:'9007199254740995',status:'DRAFT'}
function mount(overrides={}){
 const batch={...original};let volunteers=[]
 const api={listBatches:async()=>ok({list:[{...batch}],total:1}),listOptions:async()=>ok({items:[]}),listVolunteers:async()=>ok({list:volunteers.map(r=>({...r})),total:volunteers.length}),...overrides}
 const script=source.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/import [\s\S]*? from ['"][^'"\n]+['"]\s*\n/g,'').replace(/components\s*:\s*\{[^}]*\},?/,'').replace('export default','return')
 const component=new Function('api','currentUserFromToken','matchPermission','gradeError',script)(api,()=>({}),patterns=>patterns.includes('*'),gradeError)
 const vm={ctx:{permissionPatterns:['*'],currentRole:{},dataScope:{}},identity:'I1',...component.data()}
 for(const [k,v] of Object.entries(component.methods))vm[k]=v.bind(vm)
 for(const [k,v] of Object.entries(component.computed))if(k!=='identity')Object.defineProperty(vm,k,{get:()=>v.call(vm)})
 vm.current={...batch};vm.rows=[{...batch}];vm.detailReady=true;vm.loading=false
 return {vm,batch,api,component,setVolunteers:v=>{volunteers=v;vm.volunteers=v.map(r=>({...r}))}}
}
test('专业分流模板编译，统计缺值和缺志愿排名不冒充零或null志愿',()=>{const {descriptor,errors}=parse(source);assert.deepEqual(errors,[]);assert.deepEqual(compileTemplate({source:descriptor.template.content,filename:'major.vue',id:'major'}).errors,[]);assert.match(source,/row\.remain \?\? '待核对'/);assert.match(source,/志愿序号待核对/);assert.match(source,/v-if="detailReady"/ )})
test('无管理权限或明细读取失败时不开放动作',async()=>{let writes=0;const {vm}=mount({open:async()=>{writes++},listOptions:async()=>ok({})});vm.ctx.permissionPatterns=[];vm.act('open','开放');assert.equal(vm.command,null);vm.ctx.permissionPatterns=['*'];await vm.refresh();assert.equal(vm.detailReady,false);vm.act('open','开放');assert.equal(vm.command,null);vm.openAddOption();assert.equal(vm.optionVisible,false);assert.equal(writes,0)})
test('第5页批次原对象可复核，双击只发一次开放写入并正式回读',async()=>{let writes=0;const gate=deferred(),pages=[];const {vm,batch,api}=mount();vm.batchPage=5;api.listBatches=async q=>{pages.push(q.page);return ok({list:q.page===5?[{...batch}]:[],total:81})};api.open=async id=>{writes++;assert.equal(id,original.batchId);await gate.promise;batch.status='OPEN';return ok({...batch})};vm.act('open','开放');const task=vm.onConfirm();await vm.onConfirm();gate.resolve();await task;assert.equal(writes,1);assert.ok(pages.every(p=>p===5));assert.equal(vm.receipt.verified,true);assert.equal(vm.current.status,'OPEN')})
test('确认后批次阶段已变则取消旧确认，不写新状态',async()=>{let writes=0;const {vm,batch}=mount({open:async()=>{writes++}});vm.act('open','开放');batch.status='OPEN';await vm.onConfirm();assert.equal(writes,0);assert.equal(vm.command,null);assert.match(vm.error,/变化/)})
test('未知写响应即使GET已到目标阶段也不能归为本次成功或重放',async()=>{let writes=0;const {vm,batch,api}=mount();api.open=async()=>{writes++;batch.status='OPEN';throw Error('timeout')};vm.act('open','开放');await vm.onConfirm();await vm.verify();await vm.onConfirm();assert.equal(writes,1);assert.ok(vm.pending);assert.equal(vm.receipt.verified,false)})
test('写后复合403清旧批次、学生、草稿及回执',async()=>{const {vm,api}=mount();let reads=0;api.listBatches=async()=>++reads===1?ok({list:[{...original}],total:1}):denied;api.open=async()=>ok({...original,status:'OPEN'});vm.volunteers=[{studentName:'私有学生'}];vm.reassignForm.reason='私有原因';vm.act('open','开放');await vm.onConfirm();assert.equal(vm.current,null);assert.deepEqual(vm.volunteers,[]);assert.equal(vm.receipt,null);assert.equal(vm.reassignForm.reason,'')})
test('快速切批次使旧明细403和finally失效',async()=>{const gate=deferred();const {vm,api,batch}=mount();api.listOptions=id=>id===original.batchId?gate.promise:Promise.resolve(ok({items:[]}));const task=vm.refresh();batch.batchId='B2';await vm.select({...batch});gate.resolve(denied);await task;assert.equal(vm.current.batchId,'B2');assert.equal(vm.error,'');assert.equal(vm.detailReady,true);assert.equal(vm.detailLoading,false)})
test('切换批次取消尚未提交的旧确认',async()=>{const {vm,batch}=mount();vm.act('open','开放');batch.batchId='B2';await vm.select({...batch});assert.equal(vm.command,null);assert.equal(vm.confirmVisible,false)})
test('试分只发送dryRun=true且不把预览当正式分配',async()=>{const args=[];const {vm,batch}=mount({allocate:async(id,dry)=>{args.push([id,dry]);return ok({batchId:id,dryRun:true,allocated:0,unallocated:2})}});batch.status='CLOSED';vm.current={...batch};await vm.allocate(true);assert.deepEqual(args,[[original.batchId,true]]);assert.equal(vm.allocPreview.allocated,0);assert.equal(vm.current.status,'CLOSED');assert.equal(vm.receipt,null)})
test('正式分配需要单独确认，错误dryRun回执不能确认已落库',async()=>{let writes=0;const {vm,batch,api}=mount();batch.status='CLOSED';vm.current={...batch};api.allocate=async(_id,dry)=>{writes++;assert.equal(dry,false);batch.status='ALLOCATED';return ok({batchId:batch.batchId,dryRun:true})};await vm.allocate(false);assert.equal(writes,0);assert.equal(vm.confirmVisible,true);await vm.onConfirm();assert.equal(writes,1);assert.equal(vm.receipt.verified,false);assert.ok(vm.pending)})
test('人工调剂冻结长ID与原因，第4页原志愿精确回读',async()=>{const {vm,batch,api,setVolunteers}=mount();batch.status='ALLOCATED';vm.current={...batch};vm.volPage=4;const row={volunteerId:'9007199254740997',batchId:batch.batchId,studentId:'S1',choices:['9007199254740999'],status:'UNALLOCATED',resultMajorId:null,adjustReason:null};setVolunteers([row]);const pages=[];api.listVolunteers=async(_id,q)=>{pages.push(q.page);return ok({list:q.page===4?[{...row}]:[],total:61})};api.reassign=async(id,major,reason)=>{assert.equal(id,'9007199254740997');assert.equal(major,'9007199254740999');Object.assign(row,{resultMajorId:major,adjustReason:reason,status:'ALLOCATED'});return ok({...row})};vm.openReassign(row);vm.reassignForm={majorId:'9007199254740999',reason:'已与学生沟通同意调剂'};await vm.submitReassign();assert.ok(pages.every(p=>p===4));assert.equal(vm.receipt.verified,true);assert.equal(vm.volunteers[0].adjustReason,'已与学生沟通同意调剂')})
test('人工调剂原志愿已被别人修改时保留理由，不提交旧目标',async()=>{let writes=0;const {vm,batch,api,setVolunteers}=mount();batch.status='ALLOCATED';vm.current={...batch};const row={volunteerId:'V1',studentId:'S1',choices:['M1'],status:'UNALLOCATED'};setVolunteers([row]);vm.openReassign(row);row.choices=['M2'];api.reassign=async()=>{writes++};vm.reassignForm={majorId:'M2',reason:'需要保留的调剂原因'};await vm.submitReassign();assert.equal(writes,0);assert.equal(vm.reassignForm.reason,'需要保留的调剂原因');assert.equal(vm.pending,null)})
test('新建批次超时无ID不按同名草稿确认成功',async()=>{let writes=0;const {vm}=mount({createBatch:async()=>{writes++;throw Error('timeout')}});vm.form={batchName:'分流甲',grade:'2026',maxChoices:3,sourceMajorId:''};await vm.submitCreate();await vm.submitCreate();assert.equal(writes,1);assert.equal(vm.receipt.verified,false);assert.ok(vm.pending)})
test('路由保留精确批次和分页，刷新后重新读当前正式对象',async()=>{const {vm,api}=mount();vm.$route={query:{batchId:original.batchId,page:'5',volPage:'4'}};const pages=[];api.listBatches=async q=>{pages.push(q.page);return ok({list:[{...original}],total:81})};await vm.restoreRoute();assert.equal(vm.current.batchId,original.batchId);assert.equal(vm.batchPage,5);assert.equal(vm.volPage,4);assert.ok(pages.every(p=>p===5));let target;vm.$router={replace:q=>{target=q;return Promise.resolve()}};vm.writeQuery();assert.equal(target.query.batchId,original.batchId);assert.equal(target.query.volPage,'4')})
test('身份切换即使有未决写也清旧学生和回执',async()=>{const {vm,component}=mount({listBatches:async()=>denied});vm.pending={...vm.capture(),kind:'open'};vm.receipt={verified:false};vm.volunteers=[{studentName:'旧身份学生'}];vm.identity='I2';component.watch.identity.call(vm);assert.equal(vm.pending,null);assert.equal(vm.current,null);assert.deepEqual(vm.volunteers,[]);assert.equal(vm.receipt,null)})
