import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {parse,compileTemplate} from '@vue/compiler-sfc'
import * as review from '../src/modules/academicAffairs/views/parallel-c/grade-review.js'
import * as changes from '../src/modules/academicAffairs/views/parallel-c/grade-change-recovery.js'
import * as commands from '../src/modules/academicAffairs/views/parallel-c/grade-command-recovery.js'
const names=['AaGradeChangeView','AaGradeRecheckView']
const sources=Object.fromEntries(names.map(n=>[n,readFileSync(new URL('../src/modules/academicAffairs/views/'+n+'.vue',import.meta.url),'utf8')]))
const ok=data=>({code:0,data})
const unresolved=async(commandKey,operation)=>ok({commandKey,operation,state:'UNRESOLVED',result:null})
function mount(name,api={}){
 const store=new Map();globalThis.window={sessionStorage:{getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)}}
 const source=sources[name].match(/<script>([\s\S]*?)<\/script>/)[1]
 const bindings=[...source.matchAll(/^import\s+([\s\S]*?)\s+from\s+['"][^'"]+['"]\s*$/gm)].flatMap(([,v])=>v.trim().startsWith('{')?v.replace(/[{}]/g,'').split(',').map(x=>x.trim()).filter(Boolean):[v.trim()])
 const notices=[],deps={...review,...changes,...commands,academicAffairsApi:{getGradeCommandReceipt:unresolved,...api},fileSdk:{},currentUserFromToken:()=>({tenantId:'1',userId:'2',currentRoleCode:'SCHOOL_ADMIN',activeContextId:'3'}),matchPermission:(p,k)=>p.includes('*')||p.includes(k),toast:{error:m=>notices.push(m),success:m=>notices.push(m)}}
 const options=new Function(...bindings,source.replace(/^import\s+[\s\S]*?\s+from\s+['"][^'"]+['"]\s*$/gm,'').replace('export default','return'))(...bindings.map(n=>deps[n]??{}))
 const vm={ctx:{permissionPatterns:['*'],currentRole:{},dataScope:{}},$route:{query:{},path:'/corrections',fullPath:'/corrections'},$router:{replace:async()=>{}},notices}
 Object.assign(vm,options.data.call(vm));for(const[k,v]of Object.entries(options.methods))vm[k]=v.bind(vm);for(const[k,v]of Object.entries(options.computed))Object.defineProperty(vm,k,{get:()=>v.call(vm)})
 return vm
}
const application=(status='SUBMITTED')=>({recheckId:'11',studentName:'测试甲',courseName:'课程甲',originalScore:70,status,recordVersion:1})
const source=()=>({gradeTaskId:'21',gradeRecordId:'31',currentGradeId:'41',recordVersion:2,taskStatus:'PUBLISHED',schemeMode:'FIXED',usualScore:70,midtermScore:null,finalScore:80,totalScore:77,usualRatio:30,midtermRatio:0,finalRatio:70,canApply:true,blockers:[],authorityEvidenceHash:'a'.repeat(64)})
function changeVM(api={},facts=source()){const vm=mount('AaGradeChangeView',{getGradeChangeSource:async()=>ok(facts),...api});vm.source=facts;vm.selectedTaskId=facts.gradeTaskId;vm.selectedRecordId=facts.gradeRecordId;vm.applyForm={newUsualScore:'75',newMidtermScore:'',newFinalScore:'',reason:'核对试卷后更正',attachments:[]};return vm}
for(const name of names)test(name+'完整模板可编译',()=>{const {descriptor,errors}=parse(sources[name]);assert.deepEqual(errors,[]);assert.deepEqual(compileTemplate({source:descriptor.template.content,filename:name+'.vue',id:name}).errors,[])})
test('复查空白分不变零，实际零分有依据才可冻结',()=>{const vm=mount('AaGradeRecheckView');vm.active=application();vm.form.action='ADJUST';vm.openConfirm();assert.equal(vm.confirmVisible,false);assert.equal(vm.notices.length,1);vm.form.newScore='0';vm.openConfirm();assert.equal(vm.confirmVisible,false);assert.equal(vm.command,null);vm.form.note='核对正式试卷后更正';vm.openConfirm();assert.equal(vm.command.newScore,0)})
test('学期封存明确拒绝不会困在未知回执，意见保留且不重发',async()=>{let writes=0;const vm=mount('AaGradeRecheckView',{getGradeRecheck:async()=>ok(application()),reviewGradeRecheck:async()=>{writes++;return {code:500001,bizCode:'TERM_ARCHIVED',httpStatus:409,message:'该学期已归档封存，禁止修改'}}});vm.active=application();vm.form.action='ADJUST';vm.form.newScore='87';vm.form.note='复核试卷后调整总评';vm.openConfirm();await vm.doReview();assert.equal(writes,1);assert.equal(vm.pending,null);assert.equal(vm.receipt,null);assert.equal(vm.form.note,'复核试卷后调整总评');assert.match(vm.error,/已归档封存/);await vm.verifyReceipt();assert.equal(writes,1)})
test('复查换对象后旧确认不写，写前流转不写',async()=>{let writes=0;const vm=mount('AaGradeRecheckView',{getGradeRecheck:async()=>ok(application('UPHELD')),reviewGradeRecheck:async()=>{writes++}});vm.active=application();vm.openConfirm();vm.active={...application(),recheckId:'12'};await vm.doReview();assert.equal(writes,0);vm.active=application();vm.openConfirm();await vm.doReview();assert.equal(writes,0);assert.match(vm.error,/已变化/)})
test('复查超时及重复点击不重放，当前状态不能冒充原回执',async()=>{let writes=0;const vm=mount('AaGradeRecheckView',{getGradeRecheck:async()=>ok(application()),reviewGradeRecheck:async()=>{writes++;throw Error('timeout')}});vm.active=application();vm.openConfirm();await vm.doReview();await vm.doReview();await vm.verifyReceipt();assert.equal(writes,1);assert.ok(vm.pending);assert.equal(vm.receipt.verified,false)})
test('复查必须读取原回执和精确正式记录',async()=>{let written=false;const result={...application('UPHELD'),reviewNote:'已复核原试卷'};const vm=mount('AaGradeRecheckView',{getGradeRecheck:async()=>ok(written?result:application()),reviewGradeRecheck:async()=>{written=true;return ok(result)},getGradeCommandReceipt:async(commandKey,operation)=>ok({commandKey,operation,state:'SUCCESS',result})});vm.active=application();vm.form.note=result.reviewNote;vm.openConfirm();await vm.doReview();assert.equal(vm.receipt.verified,true);assert.equal(vm.receipt.commandStatus,'UPHELD');assert.equal(vm.pending,null)})
test('复查回执403清除人员和意见',async()=>{const vm=mount('AaGradeRecheckView',{getGradeRecheck:async()=>ok(application()),reviewGradeRecheck:async()=>ok({}),getGradeCommandReceipt:async()=>({code:403001})});vm.rows=[application()];vm.active=application();vm.form.note='私有意见';vm.openConfirm();await vm.doReview();assert.deepEqual(vm.rows,[]);assert.equal(vm.active,null);assert.equal(vm.form.note,'');assert.equal(vm.receipt,null)})
test('更正换任务清空拟值和原记录定位',()=>{const vm=changeVM();let patch;vm.navigate=p=>{patch=p};vm.onTaskChange('22');assert.equal(vm.applyForm.newUsualScore,'');assert.equal(patch.taskId,'22');assert.equal(patch.recordId,undefined)})
test('缺名单策略、正式版本或动态分项证据均阻止更正',()=>{const vm=changeVM();vm.source.authorityEvidenceHash='';assert.equal(vm.canSubmitApply,false);vm.source=source();vm.source.recordVersion=null;assert.equal(vm.canSubmitApply,false);vm.source={...source(),schemeMode:'DYNAMIC'};assert.equal(vm.canSubmitApply,false)})
test('确认后源成绩变化不发送旧更正',async()=>{let writes=0;const vm=changeVM({getGradeChangeSource:async()=>ok({...source(),usualScore:71,recordVersion:3}),requestGradeChange:async()=>{writes++}});vm.openApplyConfirm();await vm.submitCommand();assert.equal(writes,0);assert.match(vm.error,/已变化/)})
test('更正携带实际版本，超时保留原分并阻止重放',async()=>{let writes=0,body;const vm=changeVM({requestGradeChange:async(_t,_r,p)=>{writes++;body=p;throw Error('timeout')}});vm.openApplyConfirm();await vm.submitCommand();await vm.submitCommand();await vm.verifyPending();assert.equal(writes,1);assert.equal(body.newUsualScore,75);assert.equal(body.expectedCurrentGradeId,'41');assert.equal(vm.source.usualScore,70);assert.equal(vm.source.totalScore,77);assert.equal(vm.receipt.verified,false);assert.ok(vm.pending)})
test('动态更正改一项也发送完整方案中的未改分数',async()=>{const facts={...source(),schemeMode:'DYNAMIC',componentEvidenceHash:'b'.repeat(64),componentScores:{PRACTICE:60,THEORY:80},components:[{code:'PRACTICE',name:'实操',weight:60},{code:'THEORY',name:'理论',weight:40}]};let body;const vm=changeVM({requestGradeChange:async(_t,_r,p)=>{body=p;return{code:503001}}},facts);vm.applyForm={component_PRACTICE:'70',component_THEORY:'',reason:'实操项目评分复核',attachments:[]};vm.openApplyConfirm();await vm.submitCommand();assert.deepEqual(body.newComponentScores,{PRACTICE:70,THEORY:80});assert.equal(body.newUsualScore,undefined);assert.deepEqual(vm.source.componentScores,{PRACTICE:60,THEORY:80})})
test('更正写回403清除学生和拟更正分数',async()=>{const vm=changeVM({requestGradeChange:async()=>({code:403001})});vm.openApplyConfirm();await vm.submitCommand();assert.equal(vm.source,null);assert.deepEqual(vm.rows,[]);assert.equal(vm.applyForm.reason,'')})
