import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
const root=path.resolve(import.meta.dirname,'..')
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8')
const exists=(p)=>fs.existsSync(path.join(root,p))
const surfaces=['SystemDashboardView.vue','SystemUserListView.vue','SystemTeacherImportView.vue','SystemStudentImportView.vue','SystemRoleListView.vue','SystemRoleAssignmentView.vue','SystemDataScopeView.vue','SystemIamWorkspaceView.vue','SystemOrgView.vue','SystemModuleFeatureView.vue','SystemSecurityChangeView.vue','SystemLogView.vue','SystemDataExchangeView.vue','SystemImplementationWorkspaceView.vue','SystemConfigView.vue','SystemAcademicCalendarView.vue','SystemIntegrationView.vue']
test('approved page families keep real production surfaces',()=>{for(const f of surfaces)assert.equal(exists(`src/modules/system/views/${f}`),true,f);const r=read('src/modules/system/system.routes.js');for(const s of ["path: 'overview'","path: 'accounts/staff'","path: 'accounts/students'","path: 'identity-import/teachers'","path: 'identity-import/students'","path: 'roles'","path: 'scopes'","path: 'org'","path: 'module-entitlements'","path: 'security-changes'","path: 'logs'","path: 'data-exchange'","path: 'implementation/overview'","path: 'config'","path: 'academic-calendar'","path: 'integrations'"])assert.ok(r.includes(s),s)})
test('one portal shell and module-local visual language',()=>{const l=read('src/modules/system/views/AdminSystemLayout.vue'),c=read('src/modules/system/styles/system-ui-polish.css');assert.match(l,/class="system-ui-polish"/);assert.equal((l.match(/<BasePortalLayout/g)||[]).length,1);assert.match(c,/\.system-ui-polish \.mp-card/);assert.match(c,/\.system-ui-polish \.su-metrics/);assert.match(c,/@media \(max-width:720px\)/)})
test('overview quick tasks are permission filtered',()=>{const s=read('src/modules/system/views/SystemDashboardView.vue');assert.match(s,/quickTasks/);assert.match(s,/matchPermission/);for(const p of ['systemAdmin.user.view','systemAdmin.role.view','systemAdmin.scope.view','systemAdmin.org.view','systemAdmin.config.feature.view','systemAdmin.audit.view'])assert.match(s,new RegExp(p.replaceAll('.','\\.')));assert.match(s,/当前没有服务端返回的待处理项/);assert.match(s,/不替代上线验收/)})
test('data scope is one-rule workbench with bounded evidence',()=>{const s=read('src/modules/system/views/SystemDataScopeView.vue');for(const p of [/ds-workbench/,/受影响成员 · 受限预览/,/最多返回 200 条/,/未取得时明确显示，不补 0/,/DENY 优先于 ALLOW/,/getScopeAffectedUsers/,/getScopePolicies/,/createRequestFence/])assert.match(s,p)})
test('implementation never turns missing evidence into zero',()=>{const s=read('src/modules/system/views/SystemImplementationWorkspaceView.vue');for(const p of [/checksLoaded/,/runtimeLoaded/,/previewEvidenceReady/,/待检查/,/待读取/,/待预览/,/页面不会把“没检查”解释成“0 个问题”/])assert.match(s,p);assert.doesNotMatch(s,/<strong>\{\{\s*blockingChecks\.length\s*\}\}<\/strong>/)})
test('integration separates connection testing from sync outcomes',()=>{const s=read('src/modules/system/views/SystemIntegrationView.vue');for(const p of [/matchPermission/,/systemAdmin\.integration\.manage/,/连通性测试通过不代表同步任务已经成功/,/不代表任何同步任务已成功/,/syncError/,/syncLoading/,/retrySync/,/cancelSync/])assert.match(s,p)})
test('mature retained surfaces keep stronger contracts',()=>{const b=read('src/modules/system/views/SystemConfigView.vue'),cal=read('src/modules/system/views/SystemAcademicCalendarView.vue'),sec=read('src/modules/system/views/SystemSecurityChangeView.vue'),audit=read('src/modules/system/views/SystemLogView.vue'),dx=read('src/modules/system/views/SystemDataExchangeView.vue');for(const k of ['schoolShortName','brandColor','loginSlogan','watermarkText','watermarkDensity','footerText'])assert.match(b,new RegExp(k));assert.match(cal,/wired/);assert.match(sec,/只有激活才/);assert.match(audit,/审计日志不提供删除/);assert.match(dx,/强敏感、24 小时有效、一次性下载/)})
