const labels = {
  QUEUED:'等待试排', RUNNING:'正在智能试排', SUCCEEDED:'候选方案已生成', APPLIED:'已采用至课表草稿',
  INFEASIBLE:'当前条件无法排齐', UNKNOWN:'暂未找到完整方案', REJECTED:'排课条件未通过',
  STALE:'学校数据已变化，请重新智能试排。', CANCELLED:'已取消', FAILED:'试排失败，请重试',
  WEEKDAYS_REQUIRED:'请先在排课规则中保存允许排课星期', FORMAL_ROSTER_REQUIRED:'教学任务缺少正式名单，请先确认教学班名单',
  HEADCOUNT_BELOW_ROSTER:'预计人数少于正式名单人数，请修正教学任务',
  INTEGER_REQUIRED:'教学任务人数、课时或周次不完整，请先补齐',
  TERM_DATES_REQUIRED:'请补齐学期正式起止日期', SOURCE_CLOCK_INVALID:'请补齐作息节次的真实起止时间',
  TASK_WEEK_RANGE_REQUIRED:'请核对教学任务起止周', TEACHER_ASSIGNMENT_REQUIRED:'请为教学任务分配主讲教师',
  SLOT_SCOPE_AMBIGUOUS:'作息节次缺失或重复，请核对学校作息',
  NO_SCHEDULABLE_ROOMS:'没有允许排课的可用教室，请核对维修、停用及专用状态',
  HARD_RULE_DISABLED:'请启用容量、教室类型和教师不可排时间检查',
  UNSUPPORTED_SOURCE_RULE:'存在未支持的排课规则，请先核对规则配置',
  SPECIAL_CALENDAR_ADAPTER_REQUIRED:'校历含特殊教学安排，需要先核对可排日期',
  MYSQL_AND_WORKER_ACCEPTANCE_REQUIRED:'智能试排尚未开放，请联系学校管理员',
  PATTERN_PERIODS_MISMATCH:'连排课时合计必须等于剩余周学时', MEETING_PATTERN_INVALID:'请按 2+2 等格式填写连排规则',
  SOURCE_VERSION_CONFLICT:'学校数据已变化，请重新智能试排。',
  CAPACITY:'没有满足容量的教室', ROOM_TYPE:'没有符合课程类型的可用教室',
  ROOM_OVERLAP:'教室已被其他课程或预约占用', PERSON_OVERLAP:'教师或教学班时间冲突',
  FIXED_ROOM_OVERLAP:'已有课表与教室预约或其他课位重叠，请先核对资源占用',
  FIXED_PERSON_OVERLAP:'已有课表的教师或学生时间重叠，请先核对冲突台账',
  FIXED_DAILY_LIMIT:'已有课位已超过每天课时上限，请先调整已有安排',
  EXISTING_ROOM_UNRESOLVED:'已有课位未绑定可核实的教室，请先补齐教室字典和关联',
  EXISTING_TASK_ROSTER_UNRESOLVED:'已有课位缺少有效教学任务或正式名单，请先核对原课表',
  EXISTING_CALENDAR_UNRESOLVED:'已有课位节次与当前作息不一致，请先核对原课表',
  ROSTER_HASH_MISMATCH:'正式名单人数或成员与版本不一致，请先核对教学班名单',
  BOOKING_CLOCK_UNRESOLVED:'已批准的预约缺少可核实的作息时间，请先核对预约',
  BATCH_NOT_EDITABLE:'该课表已发布，修改请走原调停课或纠错流程',
  NO_READY_TASKS:'当前批次没有可自动排课的已就绪教学任务',
  HEADCOUNT_MISSING:'部分教学任务尚未填写人数，请先补齐',
  PROCESS_DEADLINE:'本次计算未在时限内找到完整方案，可调整连排规则后重试',
  NO_CALENDAR_CANDIDATE:'校历或连续节次不足，找不到完整上课时段', EMPTY_DOMAIN:'当前任务没有可用时段',
  SUFFICIENT_CONFLICT_SET:'这些课程无法同时满足教师、学生和教室时段要求，请调整条件后重试',
  DAILY_LIMIT:'超过教师或教学班每日课时限制', LOCKED:'已有锁定安排必须保留',
  TRAVEL_TIME_UNKNOWN:'跨校区通行时间尚未确认', TRAVEL_TIME_SHORT:'跨校区通行时间不足',
  COMMAND_STORAGE_UNAVAILABLE:'无法保存请求回执，请检查浏览器存储后重试',
  UNRESOLVED_COMMAND_CHANGED_INPUT:'上次提交结果待确认，请先核对上次请求',
  CANDIDATE_POLL_LIMIT_REFRESH_MANUALLY:'计算仍在处理中，请点击核对上次请求',
  PREVIEW_FILTER_REQUIRED:'候选课位较多，请选择单门课程查看',
  CREATOR_AUTHORIZATION_LOST:'创建人的岗位或权限已失效，请由有权限的教务员重新试排',
  SEGMENTED_ACTIVITY_PLAN_REQUIRED:'总课时与教学周、周学时不一致，请核对教学任务',
}
export const optimizerLabel = value => labels[value] || '排课条件待核对，请检查教学任务、校历和排课规则'
export function diagnosticLabels(diagnostic) {
  const reasons = Object.keys(diagnostic.rejectedBy || {})
  return (reasons.length ? reasons : [diagnostic.code]).map(optimizerLabel).join('；')
}
