"""System-generated graduation snapshot staging file authorization.

The public upload contract always creates TEMP_PRIVATE objects. Structured graduation
snapshots are different: they are generated by the server, carry an explicit
GraduationStudent id, and are immediately promoted into an immutable material version.
This resolver permits only that narrow bind transition after the caller passes the
normal graduation student scope check. Staging bytes are never directly previewable or
downloadable through the generic file API.
"""
from __future__ import annotations

from sqlalchemy import select

from app.core.permissions import has_permission
from app.services.file_access_service import register_file_resolver


_BIND_PERMISSIONS = (
    "graduationDesign.archive.file",
    "graduationDesign.material.manage",
    "graduationDesign.student.manage",
    "graduationDesign.view",
)


@register_file_resolver("GRADUATION_SNAPSHOT_STAGING")
def graduation_snapshot_staging_resolver(db, file_obj, bindings, user: dict, action: str) -> bool:
    """Authorize only the immediate server-generated snapshot bind transition."""
    if db is None or action != "bind":
        return False
    if str(getattr(file_obj, "upload_source", "") or "").upper() != "SYSTEM":
        return False
    gd_student_id = str(getattr(file_obj, "biz_id", None) or "").strip()
    if not gd_student_id.isdigit():
        return False

    try:
        from app.models import GraduationStudent
        from app.modules.graduation.services.graduation_record_resolver import resolve_current_gd_student
        from app.modules.graduation.services.graduation_scope_service import assert_student_access

        student = db.scalars(select(GraduationStudent).where(
            GraduationStudent.id == int(gd_student_id),
            GraduationStudent.tenant_id == int(file_obj.tenant_id),
            GraduationStudent.record_status == "ACTIVE",
            GraduationStudent.is_deleted.is_(False),
        )).first()
        if not student:
            return False

        if str((user or {}).get("userType") or "").upper() == "STUDENT":
            current = resolve_current_gd_student(db, user or {})
            return bool(current and int(current.id) == int(student.id))

        if not any(has_permission(user or {}, code) for code in _BIND_PERMISSIONS):
            return False
        assert_student_access(db, student, "structured.snapshot.bind")
        return True
    except Exception:
        return False
