#!/usr/bin/env python3
"""Generate and verify the student-affairs production surface and permission contract."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend" / "app"
OUTPUT = ROOT / "artifacts" / "student-affairs"
FRONTEND_CATALOG = ROOT / "frontend" / "src" / "modules" / "studentAffairs" / "config" / "permissionCatalog.generated.js"
CODE_RE = re.compile(r"[\"'](studentAffairs\.[A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)+)[\"']")
INSTALL_RE = re.compile(r"from app\.services\.([A-Za-z0-9_]+) import install as ([A-Za-z0-9_]+)")

sys.path.insert(0, str(ROOT / "backend"))
from app.core.student_affairs_permission_registry import (  # noqa: E402
    STUDENT_AFFAIRS_MOBILE_DIRECT_PERMISSIONS,
    STUDENT_AFFAIRS_PERMISSION_CODES,
    export_catalog,
)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def production_files() -> list[dict]:
    roots = {
        "backend": ROOT / "backend" / "app",
        "admin-pc": ROOT / "frontend" / "src" / "modules" / "studentAffairs",
        "student-pc": ROOT / "student-portal" / "src",
        "miniapp": ROOT / "miniapp" / "src",
    }
    rows = []
    for surface, base in roots.items():
        if not base.exists():
            continue
        for path in sorted(p for p in base.rglob("*") if p.is_file()):
            if any(part in {"__pycache__", "node_modules", "dist", "unpackage"} for part in path.parts):
                continue
            if path.suffix in {".pyc", ".pyo"}:
                continue
            text_path = path.as_posix().lower()
            if surface != "backend" and "affairs" not in text_path and "studentaffairs" not in text_path:
                continue
            if surface == "backend" and not any(token in path.name.lower() for token in ("affairs", "student_affairs")):
                continue
            rows.append({"surface": surface, "path": path.relative_to(ROOT).as_posix(), "sha256": sha256(path)})
    return rows


def used_permission_codes() -> set[str]:
    """Read production references, excluding the registry declaration itself."""
    codes: set[str] = set()
    registry = BACKEND / "core" / "student_affairs_permission_registry.py"
    for path in BACKEND.rglob("*.py"):
        if path == registry:
            continue
        codes.update(CODE_RE.findall(path.read_text(encoding="utf-8", errors="ignore")))
    return codes


def patch_graph() -> list[dict]:
    router = (BACKEND / "api" / "v1" / "router.py").read_text(encoding="utf-8")
    return [
        {
            "module": module,
            "installer": alias,
            "invoked": bool(re.search(rf"\b{re.escape(alias)}\s*\(", router)),
        }
        for module, alias in INSTALL_RE.findall(router)
    ]


def role_template_permission_codes() -> set[str]:
    path = BACKEND / "core" / "permissions.py"
    return set(CODE_RE.findall(path.read_text(encoding="utf-8", errors="ignore")))


def render_frontend_catalog() -> str:
    payload = json.dumps(export_catalog(), ensure_ascii=False, indent=2)
    return "// Generated by scripts/audit_student_affairs_surface.py; do not edit.\n" + \
        f"export const STUDENT_AFFAIRS_PERMISSION_CATALOG = {payload}\n"


def current_sha() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception:
        return "UNKNOWN"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--generate", action="store_true")
    args = parser.parse_args()
    OUTPUT.mkdir(parents=True, exist_ok=True)
    files = production_files()
    graph = patch_graph()
    used = used_permission_codes()
    missing = sorted(used - STUDENT_AFFAIRS_PERMISSION_CODES)
    unused = sorted(STUDENT_AFFAIRS_PERMISSION_CODES - used - {"studentAffairs.orientation.view"})
    role_codes = role_template_permission_codes()
    role_missing = sorted(role_codes - STUDENT_AFFAIRS_PERMISSION_CODES)
    invoked_installers = [item["installer"] for item in graph if item["invoked"]]
    forbidden_installers = {
        "install_teacher_workbench_guard", "install_self_scope_guard",
        "install_sensitive_audit_guard", "install_aid_list_argument_guard",
        "install_counselor_handover_guard", "install_appeal_todo_reconciliation",
        "install_appeal_repair", "install_appeal_repair_scheduler",
    }
    critical_installer_regressions = sorted(forbidden_installers.intersection(invoked_installers))
    expected_catalog = render_frontend_catalog()
    catalog_drift = not FRONTEND_CATALOG.exists() or FRONTEND_CATALOG.read_text(encoding="utf-8") != expected_catalog
    application_source = (BACKEND / "services" / "affairs_student_contract_service.py").read_text(encoding="utf-8")
    application_block = application_source[application_source.index("def _build_my_applications"):
                                           application_source.index("def _patch_discipline_actions")]
    application_batch_projection = all(token in application_source for token in (
        "def _batch_workflow_contexts", "def _batch_timelines", "def _batch_materials",
    )) and all(token not in application_block for token in (
        "_workflow_context(db", "_timeline(db", "_materials(db, biz_types=",
    ))
    stats_source = (BACKEND / "services" / "affairs_stats_integrity_guard.py").read_text(encoding="utf-8")
    stats_sql_aggregates = all(token not in stats_source for token in (
        "db.scalars(select(AffairsActivity).where",
        "db.scalars(select(FundingDisbursement).join",
        "db.scalars(package_stmt).all()", "db.scalars(work_stmt).all()",
        "db.scalars(family_stmt).all()",
    )) and "func.count" in stats_source and "func.sum" in stats_source
    funding_source = (BACKEND / "services" / "affairs_funding_service.py").read_text(encoding="utf-8")
    config_source = (BACKEND / "services" / "effective_config_service.py").read_text(encoding="utf-8")
    funding_rule_versioned = all(token in funding_source for token in (
        "def _eligibility_rules", '"ruleVersion"', '"projectOverrides"', "project.condition_json",
    )) and "AFFAIRS_FUNDING_ELIGIBILITY_JSON" in config_source
    repair_source = (BACKEND / "services" / "affairs_appeal_repair_service.py").read_text(encoding="utf-8")
    repair_requeue_immediate = "row.next_run_at = now - timedelta(seconds=1)" in repair_source
    archive_source = (BACKEND / "services" / "affairs_archive_service.py").read_text(encoding="utf-8")
    archive_model = (BACKEND / "models" / "affairs_archive.py").read_text(encoding="utf-8")
    scheduler_source = (ROOT / "backend" / "scripts" / "run_scheduled_jobs.py").read_text(encoding="utf-8")
    main_source = (BACKEND / "main.py").read_text(encoding="utf-8")
    archive_collect_block = archive_source[archive_source.index("def collect"):
                                           archive_source.index("def advance")]
    archive_async_packages = all(token in archive_source for token in (
        "def _claim_pending_packages", "def run_pending_packages", "with_for_update(skip_locked=True)",
        'package.status = "GENERATING"', "generation_lease_token", "generation_lease_until",
    )) and all(token in archive_model for token in (
        "generation_attempts", "generation_error", "generation_lease_token", "generation_lease_until",
    )) and "_package_bytes(" not in archive_collect_block \
        and "archive.run_pending_packages(limit=2)" in scheduler_source \
        and "affairs_archive_service.run_pending_packages(limit=2)" in main_source
    archive_batch_queries = all(token in archive_source for token in (
        "package_counts = (", ".outerjoin(package_counts", "existing_ids = set(db.scalars(",
        "student_map = {", "students = {",
    ))
    risk_source = (BACKEND / "services" / "affairs_risk_service.py").read_text(encoding="utf-8")
    risk_api_source = (BACKEND / "api" / "v1" / "student_affairs.py").read_text(encoding="utf-8")
    risk_owner_pagination = all(token in risk_source for token in (
        "def list_owner_candidates", "select(func.count())", ".offset((page - 1) * page_size).limit(page_size)",
    )) and 'pageSize: int = Query(50, ge=1, le=100)' in risk_api_source
    dorm_api_source = (BACKEND / "api" / "v1" / "affairs_student_dorm.py").read_text(encoding="utf-8")
    mini_contract_source = (ROOT / "miniapp" / "src" / "services" / "affairsContractApi.js").read_text(encoding="utf-8")
    portal_contract_source = (ROOT / "student-portal" / "src" / "services" / "affairsFourEndApi.js").read_text(encoding="utf-8")
    dorm_transfer_pagination = all(token in dorm_api_source for token in (
        "page: int = Query(1, ge=1)", "pageSize: int = Query(100, ge=1, le=200)", '"hasMore": page * pageSize < total',
    )) and all("loadAllTransferPages" in source for source in (mini_contract_source, portal_contract_source))
    dorm_view_source = (ROOT / "frontend" / "src" / "modules" / "studentAffairs" / "views" / "dorm" / "DormTransferView.vue").read_text(encoding="utf-8")
    mental_view_source = (ROOT / "frontend" / "src" / "modules" / "studentAffairs" / "views" / "mental" / "MentalReferralFollowView.vue").read_text(encoding="utf-8")
    workstudy_view_source = (ROOT / "frontend" / "src" / "modules" / "studentAffairs" / "views" / "funding" / "WorkStudyView.vue").read_text(encoding="utf-8")
    loan_view_source = (ROOT / "frontend" / "src" / "modules" / "studentAffairs" / "views" / "funding" / "StudentLoanView.vue").read_text(encoding="utf-8")
    fee_view_source = (ROOT / "frontend" / "src" / "modules" / "studentAffairs" / "views" / "funding" / "FeeReductionView.vue").read_text(encoding="utf-8")
    admin_actions_fail_closed = (
        "Array.isArray(row.allowedActions) && row.allowedActions.includes(action)" in dorm_view_source
        and "Array.isArray(row.allowedActions) ? row.allowedActions : []" in mental_view_source
        and "FALLBACK_ACTIONS" not in mental_view_source
        and "Array.isArray(row?.allowedActions) ? row.allowedActions : []" in workstudy_view_source
        and "Array.isArray(row?.allowedActions) && row.allowedActions.includes('ADVANCE')" in loan_view_source
        and "Array.isArray(row?.allowedActions) && row.allowedActions.includes(action)" in fee_view_source
    )
    activity_source = (BACKEND / "services" / "affairs_activity_service.py").read_text(encoding="utf-8")
    activity_guard_source = (BACKEND / "services" / "affairs_activity_reconfirm_guard.py").read_text(encoding="utf-8")
    router_source = (BACKEND / "api" / "v1" / "router.py").read_text(encoding="utf-8")
    activity_reconfirm_formal = all(token in activity_source for token in (
        'source="MANUAL_ADJUST"', 'event_stage = "ACTIVITY_RECONFIRMED"', '"ACTIVITY_RECONFIRM" if restored',
    )) and "install_activity_reconfirm_guard" not in router_source and "def install()" in activity_guard_source
    class_source = (BACKEND / "services" / "affairs_class_service.py").read_text(encoding="utf-8")
    class_collect_block = class_source[class_source.index("def collect_assessments"):class_source.index("def _recompute_ranks")]
    class_assessment_batch_queries = all(token in class_collect_block for token in (
        "select(SchoolClass.counselor_id, func.count(StudentProfile.id))",
        "select(SchoolClass.counselor_id, func.count(CsLeave.id))",
        "select(SchoolClass.counselor_id, func.count(AffairsRiskRecord.id))",
        "existing = {", "counselor_names = {",
    )) and "for counselor_id, cls in by_counselor.items()" not in class_collect_block
    funding_ext_source = (BACKEND / "services" / "affairs_funding_ext_service.py").read_text(encoding="utf-8")
    funding_ext_guard_source = (BACKEND / "services" / "affairs_funding_ext_guard.py").read_text(encoding="utf-8")
    funding_ext_formal = (
        "install_funding_ext_guard" not in router_source
        and "Compatibility shim" in funding_ext_guard_source
        and all(token in funding_ext_source for token in (
            '"allowedActions": {', '"allowedActions": ["ADVANCE"]',
            "with_for_update()).first()", "岗位录用人数已满", "累计补贴超过金额上限",
            ".offset((page - 1) * page_size).limit(page_size)", 'status_counts["ALL"]',
        ))
    )
    class_hot_lists_sql = all(token in class_source for token in (
        "base.order_by(SchoolClass.id).offset(",
        "select(func.count()).select_from(AffairsClassMaterial)",
        "AffairsClassMaterial.id.desc()).offset((page - 1) * page_size).limit(page_size)",
    ))
    funding_hot_lists_sql = all(token in funding_source for token in (
        "select(func.count()).select_from(FundingProject)",
        "FundingProject.id.desc()).offset((page - 1) * page_size).limit(page_size)",
        "select(func.count()).select_from(FundingBatch)",
        "FundingBatch.id.desc()).offset((page - 1) * page_size).limit(page_size)",
    ))
    counselor_eval_guard_source = (BACKEND / "services" / "affairs_counselor_eval_guard.py").read_text(encoding="utf-8")
    counselor_eval_formal = (
        "install_counselor_eval_guard" not in router_source
        and "Compatibility shim" in counselor_eval_guard_source
        and all(token in class_source for token in (
            "def _allowed_counselor_ids", "expected_version = int(p.version or 0)",
            'raise AppException("NO_DATA_SCOPE"', 'scope_type != "TENANT_ALL"',
            'row.status != "SCORED" or row.college_score is None',
        ))
    )
    publicity_rules_source = (BACKEND / "services" / "affairs_publicity_rules.py").read_text(encoding="utf-8")
    publicity_guard_source = (BACKEND / "services" / "affairs_publicity_guard.py").read_text(encoding="utf-8")
    publicity_formal = (
        "install_publicity_guard" not in router_source
        and "Compatibility shim" in publicity_guard_source
        and all(token in publicity_rules_source for token in (
            "正式公示天数应为1-30天", "学年格式应为YYYY-YYYY", "申请结束时间必须晚于开始时间",
        ))
        and all("with_for_update(skip_locked=True)" in source for source in (
            (BACKEND / "services" / "affairs_aid_service.py").read_text(encoding="utf-8"),
            funding_source,
        ))
    )
    credit_appeal_guard_source = (BACKEND / "services" / "affairs_credit_appeal_reliability.py").read_text(encoding="utf-8")
    activity_source = (BACKEND / "services" / "affairs_activity_service.py").read_text(encoding="utf-8")
    accounting_guard_source = (BACKEND / "services" / "affairs_activity_accounting_guard.py").read_text(encoding="utf-8")
    credit_appeal_formal = (
        "install_credit_appeal_reliability" not in router_source
        and "install_activity_accounting_guard" not in router_source
        and "Compatibility shim" in credit_appeal_guard_source
        and "Compatibility shim" in accounting_guard_source
        and all(token in activity_source for token in (
            "def submit_credit_appeal", '_decimal(getattr(body, "claimValue", None), "主张数值")',
            "def review_credit_appeal", "adjustment = claim if appeal.appeal_type == \"MISSING\" else claim - current",
            "def unconfirm_activity", "撤销确认只追加冲正流水", "source=\"MANUAL_ADJUST\"",
            "该记录已有待审核申诉", "require_submission_assignee", "sync_after_submit",
        ))
        and "db.delete(" not in activity_source[activity_source.index("def unconfirm_activity"):activity_source.index("def archive_activity")]
    )
    report = {
        "commitSha": current_sha(),
        "productionFileCount": len(files),
        "permissionRegistryCount": len(STUDENT_AFFAIRS_PERMISSION_CODES),
        "usedPermissionCount": len(used),
        "missingRegistryCodes": missing,
        "unusedRegistryCodes": unused,
        "roleTemplateMissingRegistryCodes": role_missing,
        "frontendCatalogDrift": catalog_drift,
        "runtimeInstallerCount": len(invoked_installers),
        "runtimeInstallerBudget": 27,
        "criticalInstallerRegressions": critical_installer_regressions,
        "applicationBatchProjection": application_batch_projection,
        "statsSqlAggregates": stats_sql_aggregates,
        "fundingRuleVersioned": funding_rule_versioned,
        "repairRequeueImmediate": repair_requeue_immediate,
        "archiveAsyncPackages": archive_async_packages,
        "archiveBatchQueries": archive_batch_queries,
        "riskOwnerPagination": risk_owner_pagination,
        "dormTransferPagination": dorm_transfer_pagination,
        "adminActionsFailClosed": admin_actions_fail_closed,
        "activityReconfirmFormal": activity_reconfirm_formal,
        "classAssessmentBatchQueries": class_assessment_batch_queries,
        "fundingExtensionFormal": funding_ext_formal,
        "classHotListsSql": class_hot_lists_sql,
        "fundingHotListsSql": funding_hot_lists_sql,
        "counselorEvaluationFormal": counselor_eval_formal,
        "publicityFormal": publicity_formal,
        "creditAppealFormal": credit_appeal_formal,
    }
    (OUTPUT / "production_files.json").write_text(json.dumps(files, ensure_ascii=False, indent=2), encoding="utf-8")
    (OUTPUT / "patch_dependency_graph.json").write_text(json.dumps(graph, ensure_ascii=False, indent=2), encoding="utf-8")
    (OUTPUT / "mobile_permission_matrix.json").write_text(
        json.dumps(STUDENT_AFFAIRS_MOBILE_DIRECT_PERMISSIONS, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (OUTPUT / "permission_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    if args.generate:
        FRONTEND_CATALOG.parent.mkdir(parents=True, exist_ok=True)
        FRONTEND_CATALOG.write_text(expected_catalog, encoding="utf-8")
        report["frontendCatalogDrift"] = False
        (OUTPUT / "permission_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    failed = (
        missing or role_missing or report["frontendCatalogDrift"]
        or report["runtimeInstallerCount"] > report["runtimeInstallerBudget"]
        or critical_installer_regressions
        or not application_batch_projection or not stats_sql_aggregates
        or not funding_rule_versioned or not repair_requeue_immediate
        or not archive_async_packages or not archive_batch_queries
        or not risk_owner_pagination or not dorm_transfer_pagination
        or not admin_actions_fail_closed or not activity_reconfirm_formal
        or not class_assessment_batch_queries or not funding_ext_formal
        or not class_hot_lists_sql or not funding_hot_lists_sql
        or not counselor_eval_formal or not publicity_formal
        or not credit_appeal_formal
    )
    return 1 if args.check and failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
