#!/usr/bin/env python3
"""Generate and verify the student-affairs production surface and permission contract."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend" / "app"
OUTPUT = ROOT / "artifacts" / "student-affairs"
FRONTEND_CATALOG = ROOT / "frontend" / "src" / "modules" / "studentAffairs" / "config" / "permissionCatalog.generated.js"
CODE_RE = re.compile(r"[\"'](studentAffairs\.[A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)+)[\"']")
INSTALL_RE = re.compile(r"from app\.services\.([A-Za-z0-9_]+) import install as ([A-Za-z0-9_]+)")

sys.path.insert(0, str(ROOT / "backend"))
from app.core.student_affairs_permission_registry import (  # noqa: E402
    STUDENT_AFFAIRS_MOBILE_DIRECT_PERMISSIONS,
    STUDENT_AFFAIRS_PERMISSION_CODES,
    export_catalog,
)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def production_files() -> list[dict]:
    roots = {
        "backend": ROOT / "backend" / "app",
        "admin-pc": ROOT / "frontend" / "src" / "modules" / "studentAffairs",
        "student-pc": ROOT / "student-portal" / "src",
        "miniapp": ROOT / "miniapp" / "src",
    }
    rows = []
    for surface, base in roots.items():
        if not base.exists():
            continue
        for path in sorted(p for p in base.rglob("*") if p.is_file()):
            if any(part in {"__pycache__", "node_modules", "dist", "unpackage"} for part in path.parts):
                continue
            if path.suffix in {".pyc", ".pyo"}:
                continue
            text_path = path.as_posix().lower()
            if surface != "backend" and "affairs" not in text_path and "studentaffairs" not in text_path:
                continue
            if surface == "backend" and not any(token in path.name.lower() for token in ("affairs", "student_affairs")):
                continue
            rows.append({"surface": surface, "path": path.relative_to(ROOT).as_posix(), "sha256": sha256(path)})
    return rows


def used_permission_codes() -> set[str]:
    """Read production references, excluding the registry declaration itself."""
    codes: set[str] = set()
    registry = BACKEND / "core" / "student_affairs_permission_registry.py"
    for path in BACKEND.rglob("*.py"):
        if path == registry:
            continue
        codes.update(CODE_RE.findall(path.read_text(encoding="utf-8", errors="ignore")))
    return codes


def patch_graph() -> list[dict]:
    router = (BACKEND / "api" / "v1" / "router.py").read_text(encoding="utf-8")
    return [
        {
            "module": module,
            "installer": alias,
            "invoked": bool(re.search(rf"\b{re.escape(alias)}\s*\(", router)),
        }
        for module, alias in INSTALL_RE.findall(router)
    ]


def role_template_permission_codes() -> set[str]:
    path = BACKEND / "core" / "permissions.py"
    return set(CODE_RE.findall(path.read_text(encoding="utf-8", errors="ignore")))


def render_frontend_catalog() -> str:
    payload = json.dumps(export_catalog(), ensure_ascii=False, indent=2)
    return "// Generated by scripts/audit_student_affairs_surface.py; do not edit.\n" + \
        f"export const STUDENT_AFFAIRS_PERMISSION_CATALOG = {payload}\n"


def current_sha() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception:
        return "UNKNOWN"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--generate", action="store_true")
    args = parser.parse_args()
    OUTPUT.mkdir(parents=True, exist_ok=True)
    files = production_files()
    graph = patch_graph()
    used = used_permission_codes()
    missing = sorted(used - STUDENT_AFFAIRS_PERMISSION_CODES)
    unused = sorted(STUDENT_AFFAIRS_PERMISSION_CODES - used - {"studentAffairs.orientation.view"})
    role_codes = role_template_permission_codes()
    role_missing = sorted(role_codes - STUDENT_AFFAIRS_PERMISSION_CODES)
    invoked_installers = [item["installer"] for item in graph if item["invoked"]]
    forbidden_installers = {
        "install_teacher_workbench_guard", "install_self_scope_guard",
        "install_sensitive_audit_guard", "install_aid_list_argument_guard",
        "install_counselor_handover_guard", "install_appeal_todo_reconciliation",
        "install_appeal_repair", "install_appeal_repair_scheduler",
    }
    critical_installer_regressions = sorted(forbidden_installers.intersection(invoked_installers))
    expected_catalog = render_frontend_catalog()
    catalog_drift = not FRONTEND_CATALOG.exists() or FRONTEND_CATALOG.read_text(encoding="utf-8") != expected_catalog
    report = {
        "commitSha": current_sha(),
        "productionFileCount": len(files),
        "permissionRegistryCount": len(STUDENT_AFFAIRS_PERMISSION_CODES),
        "usedPermissionCount": len(used),
        "missingRegistryCodes": missing,
        "unusedRegistryCodes": unused,
        "roleTemplateMissingRegistryCodes": role_missing,
        "frontendCatalogDrift": catalog_drift,
        "runtimeInstallerCount": len(invoked_installers),
        "runtimeInstallerBudget": 33,
        "criticalInstallerRegressions": critical_installer_regressions,
    }
    (OUTPUT / "production_files.json").write_text(json.dumps(files, ensure_ascii=False, indent=2), encoding="utf-8")
    (OUTPUT / "patch_dependency_graph.json").write_text(json.dumps(graph, ensure_ascii=False, indent=2), encoding="utf-8")
    (OUTPUT / "mobile_permission_matrix.json").write_text(
        json.dumps(STUDENT_AFFAIRS_MOBILE_DIRECT_PERMISSIONS, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    (OUTPUT / "permission_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    if args.generate:
        FRONTEND_CATALOG.parent.mkdir(parents=True, exist_ok=True)
        FRONTEND_CATALOG.write_text(expected_catalog, encoding="utf-8")
        report["frontendCatalogDrift"] = False
        (OUTPUT / "permission_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    failed = (
        missing or role_missing or report["frontendCatalogDrift"]
        or report["runtimeInstallerCount"] > report["runtimeInstallerBudget"]
        or critical_installer_regressions
    )
    return 1 if args.check and failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
