<script setup>
import { computed } from 'vue'
const props=defineProps({ applicant:{type:Object,required:true}, selected:Boolean })
const emit=defineEmits(['select'])
const statusLabel=computed(()=>({PENDING:'待处理',INTERESTED:'感兴趣',INTERVIEW:'面试',ACCEPT_INTENT:'拟接收',REJECTED:'不合适'}[props.applicant.decisionStatus]||'待处理'))
const statusClass=computed(()=>String(props.applicant.decisionStatus||'PENDING').toLowerCase())
function displayDateTime(value){return value?String(value).replace('T',' ').slice(0,16):'申请时间待加载'}
</script>
<template><button type="button" class="candidate" :class="{selected}" @click="emit('select',applicant)"><div class="top"><div class="identity"><span class="avatar">{{ (applicant.name || '学').slice(0,1) }}</span><div><strong>{{ applicant.name || '学生' }}</strong><div class="school">{{ applicant.major || '专业待加载' }} · {{ applicant.grade || '年级待加载' }}</div></div></div><span class="volunteer">第{{ applicant.volunteerNo ?? '—' }}志愿</span></div><div class="position">{{ applicant.positionName || '申请岗位' }}</div><div class="meta"><span class="decision" :class="statusClass">{{ statusLabel }}</span><span class="time">{{ displayDateTime(applicant.appliedAt) }}</span></div></button></template>
<style scoped>
.candidate{width:100%;text-align:left;border:0;border-bottom:1px solid var(--line);background:#fff;padding:16px 18px;color:var(--t1);transition:background .15s ease,box-shadow .15s ease}.candidate:hover{background:#fafcff}.candidate.selected{background:linear-gradient(90deg,var(--pri-50),#fbfcff);box-shadow:inset 3px 0 var(--pri)}
.top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.identity{display:flex;align-items:center;gap:10px;min-width:0}.avatar{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;flex:0 0 34px;background:var(--surface-blue);border:1px solid var(--pri-100);color:var(--pri);font-size:13px;font-weight:800}.top strong{display:block;font-size:15px;line-height:1.25}.volunteer{font-size:11px;color:var(--pri);background:var(--pri-50);border:1px solid var(--pri-100);padding:3px 7px;border-radius:999px;white-space:nowrap}.school{font-size:12px;color:var(--t3);margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.position{font-size:13px;font-weight:700;margin:12px 0 0;padding-left:44px;color:#303d52;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.meta{display:flex;justify-content:space-between;gap:12px;align-items:center;color:var(--t3);font-size:11px;margin-top:10px;padding-left:44px}.decision{font-weight:700;padding:3px 7px;border-radius:999px;background:var(--pri-50);color:var(--pri)}.decision.rejected{background:var(--danger-bg);color:var(--danger-fg)}.decision.accept_intent{background:var(--ok-bg);color:var(--ok-fg)}.decision.interview{background:var(--warn-bg);color:var(--warn-fg)}.time{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
</style>
