/**
 * 高校业务选择器：AppRemoteSelect 基座 + 语义实体 Picker + 组织级联 + 学年/学期。
 * 支持布局级统一适配器、页面显式 remoteSearch 和本地 options 三种数据来源。
 */
export { default as AppRemoteSelect } from './AppRemoteSelect.vue'
export { default as AppOrgCascader } from './AppOrgCascader.vue'
export { default as AppAcademicYearPicker } from './AppAcademicYearPicker.vue'
export { default as AppTermPicker } from './AppTermPicker.vue'
export {
  AppStudentPicker,
  AppTeacherPicker,
  AppMentorPicker,
  AppClassPicker,
  AppMajorPicker,
  AppCollegePicker,
  AppCoursePicker,
  AppRolePicker,
  AppTenantPicker,
  AppCompanyPicker,
  AppPositionPicker,
  AppBatchPicker,
  AppTermEntityPicker,
  AppTermCodePicker,
  AppTeachingTaskPicker,
  AppTeachingClassPicker,
  AppClassroomPicker,
  AppLabPicker,
  AppEquipmentPicker,
  AppTimeSlotPicker,
  AppScheduleBatchPicker,
  AppGradeTaskPicker,
  AppGradeRecordPicker,
  AppGraduationBatchPicker,
  AppRegistrationBatchPicker,
  AppExamBatchPicker,
  AppProgramPicker,
  AppSelectionBatchPicker,
  AppMakeupBatchPicker,
  AppArchiveBatchPicker,
  AppRiskOwnerPicker,
  AppAidBatchPicker,
  AppFundingProjectPicker,
  AppFundingBatchPicker,
  AppStudentArchiveBatchPicker,
  AppCounselorAssessmentPeriodPicker,
  AppDormBuildingPicker,
  AppDormRoomPicker,
  AppDormBedPicker,
  AppGraduationCandidateStudentPicker,
  AppGraduationStudentPicker,
  AppGraduationMentorPicker,
  AppAvailableGraduationMentorPicker,
  AppGraduationDesignBatchPicker,
  AppGraduationTopicPicker,
  AppDefenseGroupPicker,
  AppInternshipCandidateStudentPicker,
  AppInternshipStudentPicker,
  AppUnassignedInternshipStudentPicker,
  AppInternshipPositionPicker,
  AppInternshipEnterprisePicker,
  AppInternshipAdvisorPicker,
  AppInternshipBatchPicker,
  AppEnterpriseMentorPicker
} from './entityPickers'
