/**
 * 学生 PC 门户 · API 门面。只暴露门户允许调用的接口（严格边界）。
 */
import { downloadFile, request, uploadFile } from './request'
import fileSdk from './fileSdk'

const q = (obj) => {
  const parts = Object.entries(obj || {})
    .filter(([, v]) => v != null && v !== '')
    .map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`)
  return parts.length ? `?${parts.join('&')}` : ''
}

let renderedGraduationTaskbookVersion = null

export const portalApi = {
  login: (loginName, password, tenantCode) =>
    request('/auth/login', { method: 'POST', auth: false, body: { loginName, password, ...(tenantCode ? { tenantCode } : {}), clientType: 'PC' } }),
  portalConfig: () => request('/mobile/me/portal-config'),
  overview: () => request('/mobile/me/overview'),
  profile: () => request('/mobile/me/profile'),
  todos: () => request('/mobile/me/todos'),
  messages: () => request('/mobile/me/messages'),
  domainMy: (domain) => request(`/mobile/${domain}/my`),
  homeOverview: () => request('/portal/home/overview'),

  profileEnrollment: () => request('/portal/profile/enrollment'),
  profileSensitive: (field, reason) => request('/portal/profile/sensitive', { method: 'POST', body: { field, reason } }),
  listGuardians: () => request('/portal/parent/guardians'),
  bindGuardian: (body) => request('/portal/parent/guardians', { method: 'POST', body }),
  revokeGuardian: (linkId) => request(`/portal/parent/guardians/${encodeURIComponent(linkId)}/revoke`, { method: 'POST' }),

  academicTranscript: () => request('/portal/academic/transcript'),
  academicTranscriptPrint: (body) => request('/portal/academic/transcript/print', { method: 'POST', body }),
  academicSchedule: () => request('/portal/academic/schedule'),
  academicSchedulePrint: (body) => request('/portal/academic/schedule/print', { method: 'POST', body }),
  academicCourseSelection: (batchId) => request(`/portal/academic/course-selection${q({ batchId })}`),
  academicEnroll: (body) => request('/portal/academic/course-selection/enroll', { method: 'POST', body }),
  academicDrop: (body) => request('/portal/academic/course-selection/drop', { method: 'POST', body }),
  academicSelectionRecords: (batchId) => request(`/portal/academic/course-selection/records${q({ batchId })}`),
  academicStatus: () => request('/portal/academic/status'),
  academicTransferOptions: () => request('/portal/academic/transfer-options'),
  academicStatusChange: (body) => request('/portal/academic/status-change', { method: 'POST', body }),
  academicStatusChangePrint: (body) => request('/portal/academic/status-change/print', { method: 'POST', body }),
  academicExam: () => request('/portal/academic/exam'),
  academicExamDefer: (status) => request(`/portal/academic/exam/defer${q({ status })}`),
  academicExamDeferApply: (body) => request('/portal/academic/exam/defer/apply', { method: 'POST', body }),
  academicExamDeferResubmit: (deferId) => request(`/portal/academic/exam/defer/${encodeURIComponent(deferId)}/resubmit`, { method: 'POST' }),
  academicMakeup: () => request('/portal/academic/makeup'),
  academicMakeupOptions: () => request('/portal/academic/makeup/options'),
  academicRetakeApply: (body) => request('/portal/academic/retake/apply', { method: 'POST', body }),
  academicExemptionApply: (body) => request('/portal/academic/exemption/apply', { method: 'POST', body }),
  academicRegistration: () => request('/portal/academic/registration'),
  academicRegistrationRegister: (batchId) => request(`/portal/academic/registration/${encodeURIComponent(batchId)}/register`, { method: 'POST' }),
  academicRegistrationDefer: (batchId, body) => request(`/portal/academic/registration/${encodeURIComponent(batchId)}/defer`, { method: 'POST', body }),
  academicAttendance: () => request('/portal/academic/attendance'),
  academicCalendar: () => request('/portal/academic/calendar'),
  academicClearance: () => request('/portal/academic/clearance'),
  academicExamTicketPrint: (body) => request('/portal/academic/exam/ticket/print', { method: 'POST', body }),
  academicGraduationAudit: () => request('/portal/academic/graduation-audit'),
  academicEvaluationTasks: () => request('/portal/academic/evaluation/tasks'),
  academicEvaluationSubmit: (body) => request('/portal/academic/evaluation/submit', { method: 'POST', body }),
  academicExamDeferOptions: () => request('/portal/academic/exam/defer/options'),
  academicGradeRecheck: () => request('/portal/academic/grade-recheck'),
  academicGradeRecheckSubmit: (body) => request('/portal/academic/grade-recheck', { method: 'POST', body }),
  academicTextbook: () => request('/portal/academic/textbook'),
  academicTextbookSign: (recordId) => request(`/portal/academic/textbook/${encodeURIComponent(recordId)}/sign`, { method: 'POST' }),
  academicLevelExam: () => request('/portal/academic/level-exam'),
  academicLevelRegister: (examId) => request(`/portal/academic/level-exam/${encodeURIComponent(examId)}/register`, { method: 'POST' }),
  academicLevelCancel: (examId) => request(`/portal/academic/level-exam/${encodeURIComponent(examId)}/cancel`, { method: 'POST' }),
  academicMajorSplit: () => request('/portal/academic/major-split'),
  academicMajorSplitSubmit: (body) => request('/portal/academic/major-split/submit', { method: 'POST', body }),
  academicCredits: () => request('/portal/academic/credits'),
  academicWarning: () => request('/portal/academic/warning'),
  academicRecognition: () => request('/portal/academic/recognition'),
  academicRecognitionSubmit: (body) => request('/portal/academic/recognition', { method: 'POST', body }),

  affairsOverview: () => request('/portal/affairs/overview'),
  affairsLeave: () => request('/portal/affairs/leave'),
  affairsLeaveApply: (body) => request('/portal/affairs/leave', { method: 'POST', body }),
  affairsLeaveResubmit: (leaveId, body = {}) => request(`/portal/affairs/leave/${encodeURIComponent(leaveId)}/resubmit`, { method: 'POST', body }),
  affairsLeaveCancel: (leaveId, body = {}) => request(`/portal/affairs/leave/${encodeURIComponent(leaveId)}/cancel`, { method: 'POST', body }),
  affairsLeaveExtend: (leaveId, body = {}) => request(`/portal/affairs/leave/${encodeURIComponent(leaveId)}/extension`, { method: 'POST', body }),
  affairsDorm: () => request('/portal/affairs/dorm'),
  affairsTalk: () => request('/portal/affairs/talk'),
  affairsFunding: () => request('/portal/affairs/funding'),
  affairsAid: () => request('/portal/affairs/aid'),
  affairsDiscipline: () => request('/portal/affairs/discipline'),
  affairsApplications: () => request('/portal/affairs/applications'),
  affairsServiceApply: (body) => request('/portal/affairs/service-apply', { method: 'POST', body }),
  affairsPrint: (body) => request('/portal/affairs/print', { method: 'POST', body }),
  affairsPsyQuestions: () => request('/portal/affairs/psy/questions'),
  affairsPsySubmit: (body) => request('/portal/affairs/psy/submit', { method: 'POST', body }),
  affairsPsyHistory: () => request('/portal/affairs/psy/history'),
  affairsDisciplineAppeal: (body) => request('/portal/affairs/discipline/appeal', { method: 'POST', body }),
  affairsFundingBatches: () => request('/portal/affairs/funding/batches'),
  affairsFundingApply: (body) => request('/portal/affairs/funding/apply', { method: 'POST', body }),
  affairsFundingAppeal: (body) => request('/portal/affairs/funding/appeal', { method: 'POST', body }),
  affairsAidBatches: () => request('/portal/affairs/aid/batches'),
  affairsAidApply: (body) => request('/portal/affairs/aid/apply', { method: 'POST', body }),
  affairsAidObjection: (body) => request('/portal/affairs/aid/objection', { method: 'POST', body }),
  affairsActivities: (page = 1, pageSize = 20) => request(`/portal/affairs/activities${q({ page, pageSize })}`),
  affairsActivitiesMy: () => request('/portal/affairs/activities/my'),
  affairsActivityEnroll: (activityId) => request(`/portal/affairs/activities/${encodeURIComponent(activityId)}/enroll`, { method: 'POST' }),

  internshipMy: () => request('/portal/internship/my'),
  internshipCompliance: (operation = 'ONBOARD', batchId = '') => request(`/portal/internship/compliance${q({ operation, batchId })}`),
  internshipConsents: () => request('/portal/internship/consents'),
  internshipConsentDetail: (id) => request(`/portal/internship/consents/${encodeURIComponent(id)}`),
  internshipConsentView: (id) => request(`/portal/internship/consents/${encodeURIComponent(id)}/view`, { method: 'POST' }),
  internshipConsentConfirm: (id, body) => request(`/portal/internship/consents/${encodeURIComponent(id)}/confirm`, { method: 'POST', body }),
  internshipConsentReject: (id, body) => request(`/portal/internship/consents/${encodeURIComponent(id)}/reject`, { method: 'POST', body }),
  internshipSafetyCourses: () => request('/portal/internship/safety/courses'),
  internshipSafetyCompletions: () => request('/portal/internship/safety/completions'),
  internshipSafetyDetail: (id) => request(`/portal/internship/safety/courses/${encodeURIComponent(id)}/detail`),
  internshipSafetyStart: (id) => request(`/portal/internship/safety/courses/${encodeURIComponent(id)}/start`, { method: 'POST' }),
  internshipSafetySubmit: (id, body) => request(`/portal/internship/safety/courses/${encodeURIComponent(id)}/submit`, { method: 'POST', body }),
  internshipSafetyCommit: (id, body) => request(`/portal/internship/safety/completions/${encodeURIComponent(id)}/commit`, { method: 'POST', body }),
  internshipWeeklySubmit: (body) => request('/portal/internship/weekly/submit', { method: 'POST', body }),
  internshipReportSubmit: (body) => request('/portal/internship/report/submit', { method: 'POST', body }),
  internshipAgreementPrint: (body) => request('/portal/internship/agreement/print', { method: 'POST', body }),
  internshipScoreAppeal: (body) => request('/portal/internship/score/appeal', { method: 'POST', body }),
  internshipLeaves: () => request('/portal/internship/leaves'),
  internshipLeaveApply: (body) => request('/portal/internship/leaves/apply', { method: 'POST', body }),
  internshipLeaveReturn: (leaveId, body) => request(`/portal/internship/leaves/${encodeURIComponent(leaveId)}/return`, { method: 'POST', body }),
  internshipLeaveWithdraw: (leaveId) => request(`/portal/internship/leaves/${encodeURIComponent(leaveId)}/withdraw`, { method: 'POST' }),
  internshipCheckin: (body) => request('/portal/internship/checkin', { method: 'POST', body }),
  internshipSelfEval: (body) => request('/portal/internship/self-eval', { method: 'POST', body }),
  internshipMakeupApply: (body) => request('/portal/internship/makeup', { method: 'POST', body }),
  internshipMakeups: () => request('/portal/internship/makeup'),
  internshipMakeupWithdraw: (id) => request(`/portal/internship/makeup/${encodeURIComponent(id)}/withdraw`, { method: 'POST' }),
  internshipIntentionMy: () => request('/portal/internship/intention'),
  internshipIntentionSave: (body) => request('/portal/internship/intention', { method: 'POST', body }),
  internshipIntentionSubmit: () => request('/portal/internship/intention/submit', { method: 'POST' }),
  internshipIntentionWithdraw: () => request('/portal/internship/intention/withdraw', { method: 'POST' }),
  internshipApplications: () => request('/portal/internship/applications'),
  internshipApplicationSubmit: (body) => request('/portal/internship/applications', { method: 'POST', body }),
  internshipChangeApply: (body) => request('/portal/internship/change', { method: 'POST', body }),
  internshipChanges: () => request('/portal/internship/change'),
  internshipAgreements: () => request('/portal/internship/agreements'),
  internshipAgreementDetail: (id) => request(`/portal/internship/agreements/${encodeURIComponent(id)}`),
  internshipAgreementConfirm: (id, body) => request(`/portal/internship/agreements/${encodeURIComponent(id)}/confirm`, { method: 'POST', body }),
  internshipInsurance: () => request('/portal/internship/insurance'),
  internshipInsuranceSave: (body) => request('/portal/internship/insurance', { method: 'POST', body }),
  internshipPlan: () => request('/portal/internship/plan'),
  internshipPlanAck: () => request('/portal/internship/plan/acknowledge', { method: 'POST' }),
  internshipEnterprises: (city = '') => request(`/portal/internship/enterprises${city ? `?city=${encodeURIComponent(city)}` : ''}`),
  internshipHelp: (body) => request('/portal/internship/help', { method: 'POST', body }),

  employmentMy: () => request('/portal/employment/my'),
  employmentDestination: (body) => request('/portal/employment/destination', { method: 'POST', body }),
  employmentDestinationPrint: (body) => request('/portal/employment/destination/print', { method: 'POST', body }),
  orientationMy: () => request('/portal/orientation/my'),
  orientationCollect: (body) => request('/portal/orientation/collect', { method: 'POST', body }),
  orientationGreenChannel: (body) => request('/portal/orientation/green-channel', { method: 'POST', body }),
  orientationPrint: (body) => request('/portal/orientation/print', { method: 'POST', body }),
  serviceHallCatalog: () => request('/portal/service-hall/catalog'),
  messagesInbox: (page = 1, pageSize = 20) => request(`/portal/messages${q({ page, pageSize })}`),
  messageRead: (messageId) => request(`/portal/messages/${encodeURIComponent(messageId)}/read`, { method: 'POST' }),
  messagesReadAll: () => request('/portal/messages/read-all', { method: 'POST' }),
  messageReceipt: (messageId) => request(`/portal/messages/${encodeURIComponent(messageId)}/receipt`, { method: 'POST' }),
  messagePreferences: () => request('/portal/messages/preferences'),
  messageSetPreference: (body) => request('/portal/messages/preferences', { method: 'POST', body }),
  commonSign: (body) => request('/portal/common/sign', { method: 'POST', body }),
  commonPrintLog: (body) => request('/portal/common/print-log', { method: 'POST', body }),
  commonExportLog: (body) => request('/portal/common/export-log', { method: 'POST', body }),

  graduationTaskbook: async () => {
    const data = await request('/portal/graduation/taskbook')
    renderedGraduationTaskbookVersion = data?.hasData ? data.taskbookVersion : null
    return data
  },
  signGraduationTaskbook: (taskbookVersion = renderedGraduationTaskbookVersion) => request('/portal/graduation/taskbook/sign', { method: 'POST', body: { confirm: true, taskbookVersion } }),
  graduationProposal: () => request('/portal/graduation/proposal'),
  submitGraduationProposal: (body) => request('/portal/graduation/proposal/submit', { method: 'POST', body }),
  graduationMidterm: () => request('/portal/graduation/midterm'),
  rectifyGraduationMidterm: (content) => request('/portal/graduation/midterm/rectify', { method: 'POST', body: { content } }),
  graduationFinal: () => request('/portal/graduation/final'),
  submitGraduationFinal: (body) => request('/portal/graduation/final/submit', { method: 'POST', body }),
  graduationDefense: () => request('/portal/graduation/defense'),
  graduationGrade: () => request('/portal/graduation/grade'),
  graduationGradeAppeal: (reason) => request('/portal/graduation/grade/appeal', { method: 'POST', body: { reason } }),
  graduationPeerTasks: () => request('/mobile/graduation/peer-tasks'),
  submitGraduationPeer: (pid, opinion) => request(`/mobile/graduation/peer/${encodeURIComponent(pid)}/submit`, { method: 'POST', body: { opinion } }),
  rectifyGraduationPeer: (pid, note) => request(`/mobile/graduation/peer/${encodeURIComponent(pid)}/rectify`, { method: 'POST', body: { note } }),
  graduationArchive: () => request('/mobile/graduation/archive'),
  graduationActiveRound: () => request('/mobile/graduation/active-round'),
  graduationTopics: (batchId) => request(`/mobile/graduation/topics${batchId ? `?batchId=${encodeURIComponent(batchId)}` : ''}`),
  submitGraduationChoices: (roundId, choices) => request('/mobile/graduation/choices', { method: 'POST', body: { roundId, choices } }),
  withdrawGraduationChoices: (roundId) => request('/mobile/graduation/withdraw-choices', { method: 'POST', body: { roundId } }),
  requestGraduationTopicChange: (newTopicId, reason) => request('/mobile/graduation/change-request', { method: 'POST', body: { newTopicId, reason } }),
  graduationChangeRequests: () => request('/mobile/graduation/change-requests/my'),
  graduationMaterialLibrary: () => request('/mobile/graduation/material-center/library'),
  graduationMaterialManifest: () => request('/mobile/graduation/material-center/manifest'),
  submitGraduationMaterial: (materialCode, fileId, expectedVersion) => request(`/mobile/graduation/material-center/materials/${encodeURIComponent(materialCode)}/submit`, { method: 'POST', body: { fileId, expectedVersion, clientSurface: 'STUDENT_PC' } }),
  issueGraduationMaterialTicket: (fileId, action) => request(`/mobile/graduation/material-center/files/${encodeURIComponent(fileId)}/ticket`, { method: 'POST', body: { action } }),
  uploadGraduationMaterial: (file) => fileSdk.upload(file, { bizType: 'GRADUATION_MATERIAL' }),
  async downloadGraduationMaterial(fileId, fileName) {
    const ticket = await this.issueGraduationMaterialTicket(fileId, 'download')
    return fileSdk.downloadFrom(ticket, fileName)
  },
  async previewGraduationMaterial(fileId, fileName) {
    const ticket = await this.issueGraduationMaterialTicket(fileId, 'preview')
    return fileSdk.previewFrom(ticket, fileName)
  }
}

export default portalApi
